### ISSUE TITLE
Is the license of this repository "MIT" or "ISC" ?

### ISSUE THREAD

**Issue by lcd78706** [codeofsumit/leaflet.pm#102]
Hello @codeofsumit ,
I am the member of cdnjs project.
I want to add this library, but the license mentioned in README.md https://github.com/codeofsumit/leaflet.pm#license is different from the package.json and also on npm. The first is MIT and second is ISC. 
I want to confirm with you which one is the correct license.

https://github.com/cdnjs/cdnjs/issues/9799
https://github.com/cdnjs/cdnjs/pull/9880

**Comment by codeofsumit** [comment]
Hi @lcd78706,
*the License is MIT* - The package.json was auto generated, sorry about that I'll have that updated in the next release - please leave this issue open as a reference. I'll close it as soon as it's fixed.

**Comment by lcd78706** [comment]
Thanks for your reply.
