### ISSUE TITLE
Showing Measurement on Line and Polygon

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#114]
Hello, first, I want to show this is a great plugin. I am able to show measurement on line and polyon by integrating this with leaflet plugin (Leaflet Measure Path by ProminentEdge) in the option.

map.pm.setPathOptions({
    showMeasurements: true,
});

But, I do not know how to update those measurements when I edit a line or polygon. I am new to leaflet. Could you please help me?

**Comment by codeofsumit** [comment]
This isn't an issue with leaflet.pm so I close this but I tried this for you:
I haven't been able to make @prominentEdge's plugin [Leaflet Measure Path](https://github.com/ProminentEdge/leaflet-measure-path) working but from what I understand something like this should work, provided his plugin works:

```
map.on('pm:create', function(e) {
  // the layer you just created
  var layer = e.layer;

  // show measurements
  layer.showMeasurements();

  // update measurements on edit
  layer.on('pm:edit', function() {
    layer.updateMeasurements();
  });
});
```

**Comment by leekosal** [comment]
thank you. It works great.
