### ISSUE TITLE
Cannot adjust other vertex after one vertex is deleted.

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#118]
After enabling edit, i delete one vertex and then I cannot adjust other vertex.

**Comment by codeofsumit** [comment]
I'd be great if you could provide a demo with the issue. Preferably on jsfiddle or codepen but you can also just send me a working demo. If I see the issue, I'll help and/or fix it asap.

**Comment by leekosal** [comment]
You can test on your demo link. It has the same issues.

**Comment by codeofsumit** [comment]
holy shit I didn't see this! Thanks! Will have it fixed by tomorrow!

**Comment by codeofsumit** [comment]
hmm even the map isn't draggable anymore

**Comment by codeofsumit** [comment]
ok @leekosal this is a leaflet issue and was fixed in 1.0.2. Update to leaflet 1.0.2 and it should be fixed. I'll update the demo asap.

**Comment by leekosal** [comment]
thank you.

**Comment by codeofsumit** [comment]
@leekosal did it work?

**Comment by leekosal** [comment]
Yes it works now. Thank you.
