### ISSUE TITLE
Is it possible to show mouse cross cursor when on mobile?

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#120]
It will be handy when using on mobile screen since we can drag that cursor on mobile screen.

**Comment by codeofsumit** [comment]
uhm I don't understand what you mean? A mousecursor on mobile? I don't thank any website has that... mobile is for touch. Is there a specific problem with leaflet.pm?

**Comment by leekosal** [comment]
There is no problem with leaflet.pm. It works great. But, I am just wondering if there are anyway we can draw polygon or line more accurately when we are on mobile device with touch screen. As there is no cursor pointer on screen, our best guess is to put our big thump on a screen :D

**Comment by codeofsumit** [comment]
😉 I don't think that'd be much better. Maybe you can try scaling the whole map up with CSS transforms. Not sure if it messes with the dragging positions but well... 
Another idea would be to create a bigger marker as the drag handle for polygons so it can be dragged more easily.
I'll close this open even though it's an improvement suggestion but I probably won't build this anytime soon as it's way too much trial-and-error until there is a solution that'd be appropriate for this usecase.
