### ISSUE TITLE
how can I get the line points?

### ISSUE THREAD

**Issue by pomarc** [codeofsumit/leaflet.pm#121]
The plugin works beautfully, but after I end drawing a polyline, I'd like to know the array of vertex of the line.
I've handled the on:end event but I could not extract the points from the passed parameter. Could  you please show an example? thank you,

**Comment by codeofsumit** [comment]
```
map.on('pm:create', function(e) {
  var coords = e.layer.getLatLngs();
  console.log(coords);
});
```

does this work?

**Comment by pomarc** [comment]
perfectly, thanks.

**Comment by codeofsumit** [comment]
@pomarc Ah i see. There are events on each marker for existing layers that you edit.
But for newly drawn ones there is no event current during the drawing.
I'll think about how to approach this, thanks for the suggestion 👍
