### ISSUE TITLE
deleting poly coordinate disables edit mode

### ISSUE THREAD

**Issue by fyyyyy** [codeofsumit/leaflet.pm#122]
after deleting a polygon coordinate, other coordinates are no longer editable

Cheers :D

**Comment by codeofsumit** [comment]
@fyyyyy what version? I think this was fixed in 0.13.0

**Comment by fyyyyy** [comment]
0.13.0

**Comment by codeofsumit** [comment]
http://leaflet.pm.kaumgeschlafen.com/

does it work here?

**Comment by fyyyyy** [comment]
yep

**Comment by codeofsumit** [comment]
you have to update leaflet ;-)

**Comment by fyyyyy** [comment]
ok thx :D
