### ISSUE TITLE
L.Circle support (WIP)

### ISSUE THREAD

**Issue by lgzajac** [codeofsumit/leaflet.pm#123]
just in case - notification, if someone is in a dire need ;)
https://github.com/lgzajac/leaflet.pm/tree/circle_wip

**Comment by codeofsumit** [comment]
@lgzajac cool! But why not create a Pull Request? Circle Support was on my list anyway and this might saves me some time!

**Comment by lgzajac** [comment]
@codeofsumit - well, it is still work in progress ;) . 
Especially that I am using one geodesic function from external library (probably can be replaced with internal Leaflet stuff) 
I will try to create clean PR asap, but before that i have to finish some other stuff.

**Comment by codeofsumit** [comment]
@lgzajac never mind man, I'm on it :-)
![circle_support](https://cloud.githubusercontent.com/assets/2399810/23160313/4822438c-f826-11e6-876a-82143cb01293.gif)

**Comment by lgzajac** [comment]
cool :)
