### ISSUE TITLE
Prevent deletion of polygon vertices if < 3

### ISSUE THREAD

**Issue by fyyyyy** [codeofsumit/leaflet.pm#124]
Currently its possible to create 2-vertice or 1-vertice polygons by deleting vertices with right click.
There should be a way to prevent this.

**Comment by codeofsumit** [comment]
mhh, at least in edit mode: I agree.
But during initial draw you might need to delete the markers you just created to fix errors or something. What do you think?

**Comment by fyyyyy** [comment]
Sounds good ;)

**Comment by codeofsumit** [comment]
will do it this week!
