### ISSUE TITLE
Add snapping when drawing

### ISSUE THREAD

**Issue by gouroujo** [codeofsumit/leaflet.pm#125]
Hi !
Thanks for your awesome work, it's much cleaner than leaflet.draw in my opinion.
I have hacked your lib with the following snippet to add the snapping functionality when you draw a polygon. It's a **very** dirty hack but it could be a start to see what need to be done for this addon.

```javascript
L.PM.Draw.include({ // add the Snap Mixin
  _initSnappableMarkers: L.PM.Edit.prototype._initSnappableMarkers,
  _unsnap: L.PM.Edit.prototype._unsnap,
  _cleanupSnapping: L.PM.Edit.prototype._cleanupSnapping,
  _handleSnapping: L.PM.Edit.prototype._handleSnapping,
  _checkPrioritiySnapping: L.PM.Edit.prototype._checkPrioritiySnapping,
  _createSnapList: L.PM.Edit.prototype._createSnapList,
  _calcClosestLayer: L.PM.Edit.prototype._calcClosestLayer,
  _calcLayerDistances: L.PM.Edit.prototype._calcLayerDistances,
  _getClosestPointOnSegment: L.PM.Edit.prototype._getClosestPointOnSegment,
  _getDistanceToSegment: L.PM.Edit.prototype._getDistanceToSegment,
  _getDistance: L.PM.Edit.prototype._getDistance
});
L.PM.Draw.Line.include({
  _onMarkerDrag(e) { // dumb function to avoid error
    return;
  },
  _syncHintLine(e) {
    this.options.snapDistance = 10;
    this._layer = { // very ugly binding
      _map: this._map,
      fire: () => { return null } // dumb function to avoid error
    };
    const polyPoints = this._polyline.getLatLngs();

    if(polyPoints.length > 0) {
      const lastPolygonPoint = polyPoints[polyPoints.length - 1];
      this._hintline.setLatLngs([lastPolygonPoint, e.latlng]);
    }
    e.target = this._createMouseMarker(e.latlng); // add mouse marker to see the snap in action
    this._handleSnapping(e); // add snap

  },
  _createPolygonPoint(e) {
    const latlng = this.mouseMarker.getLatLng(); // use the marker latlng instead of event
    const first = this._polyline.getLatLngs().length === 0;

    this._polyline.addLatLng(latlng);
    this._createMarker(latlng, first);

    this._hintline.setLatLngs([latlng, latlng]);
  },
  _createMouseMarker(latlng) { // add mouse pointer
    if (!this.mouseMarker) {
      this.mouseMarker = new L.Marker(latlng, {
          draggable: false,
          icon: L.divIcon({ className: 'marker-icon' }),
      });
      this.mouseMarker._pmTempLayer = true;
    } else {
      this.mouseMarker.setLatLng(latlng);
    }
    // add it to the map
    this._layerGroup.addLayer(this.mouseMarker);
    return this.mouseMarker;
  },
});
```

**Comment by codeofsumit** [comment]
hey @gouroujo, glad to hear you like it. Thanks for your snippet! I'll add the functionality to leaflet.pm in some way or another.

Just have to think about the usability for a bit, or if it should be standard behaviour when you enable drawing via the toolbar. What do you think about it?
Should the draw-button in the toolbar enable drawing with snap or without snap?

**Comment by gouroujo** [comment]
Hey,
In my project it is the default behaviour (you disabled it by pressing the "alt" key). The snapping is limited to 10px so it's pretty easy to not link polygon if you want to.

Moreover, I don't use the toolbar for editing because I need more control on which polygon the user want to edit. It also solves the problem of overlapped markers and polygons.

<img width="716" alt="screen shot 2017-01-25 at 10 07 14" src="https://cloud.githubusercontent.com/assets/6749520/22284229/850aac12-e2e6-11e6-851b-55948d2ee41f.png">

**Comment by codeofsumit** [comment]
Ah I meant the drawing button, not the edit button. When you click the "draw-polygon" button, you have snapping enabled (with your snippet) and can disable it by pressing "alt", just like the current snap feature 👍

Ok, thanks for the clarification. I'll work on it now

**Comment by codeofsumit** [comment]
soon:
![snap_at_drag](https://cloud.githubusercontent.com/assets/2399810/22296650/28b78806-e31b-11e6-8b0e-d9a099760a2a.gif)

**Comment by codeofsumit** [comment]
I'm almost finished.
Hard part was this: clicking beside a snapped marker and still finish the polygon.
![snap_at_drag](https://cloud.githubusercontent.com/assets/2399810/22377177/27aa229c-e4b1-11e6-8a28-c375e9c19151.gif)

Will probably release tonight or sunday. Not sure.

**Comment by codeofsumit** [comment]
found another issue that needs fixin. I'm on it.

**Comment by themre** [comment]
I looked at the demo, works nice, however when going back into edit mode, snapping isn't activated.

**Comment by codeofsumit** [comment]
thanks, fixed.

**Comment by codeofsumit** [comment]
wait a minute, saw a second issue with that. I'm on it

**Comment by codeofsumit** [comment]
@themre NOW it's fixed 😅
Do you mind testing the branch #127 ?

**Comment by themre** [comment]
hm, I created simple jsfiddle https://jsfiddle.net/9d9cn83f/3/ and put min version inside, but it doesn't work. only first time, when drawing it does snap, when edit back and drag, it doesn't snap.

**Comment by codeofsumit** [comment]
@themre try it like this:
https://jsfiddle.net/9d9cn83f/4/

**Comment by leekosal** [comment]
hello, it works only on vertex that is not snapped during draw. for vertex which was snapped during draw, it wont work.

**Comment by themre** [comment]
perhaps we don't understand each other.
![snap](https://cloud.githubusercontent.com/assets/10845050/22423897/3009bf52-e6f4-11e6-9225-0b8b541ed5ae.gif)

**Comment by codeofsumit** [comment]
ah, thanks for the gif, now I was able to reproduce. It seems to be a problem with the mix of polyLines and polygons, I'm on it!

**Comment by codeofsumit** [comment]
@themre @leekosal
I think it's fixed. Can you try with the new version?

**Comment by leekosal** [comment]
it works. However, i have one issue. For example, point A is snapped to point B. When in edit mode, I can only move point A. I cant move point B under point A. How to adjust point B without moving point A away first?. It would be great if in edit mode, we can select a polygon/line to make it active first and adjust its points.

**Comment by themre** [comment]
I don't see merging B into A as an issue, if it's from the same shape. You can still create new point from edge middle or if you have some Redux you perform undo.

**Comment by codeofsumit** [comment]
@leekosal that's a separate issue discussed here #80.
Let's continue the conversation about that in #80 and focus here on the snap-during-draw feature.

**Comment by leekosal** [comment]
thanks. got it. i test on my iphone. Seems i still cannot draw any polygon/line

**Comment by codeofsumit** [comment]
@leekosal was able to reproduce. Will check it out tomorrow 👍

**Comment by codeofsumit** [comment]
@leekosal wops, fixed it already ¯\_(ツ)_/¯
Can you try again please?

**Comment by leekosal** [comment]
hello. still not working yet.

**Comment by codeofsumit** [comment]
@leekosal https://jsfiddle.net/9d9cn83f/7/
this works on my iPhone 6 ☝️

I need more info to reproduce.

**Comment by leekosal** [comment]
your link is working on my iphone...i just know that i suddenly cant draw anything on my site even if i did not change any code. www.cambomap.com

**Comment by themre** [comment]
code on jsfiddle is updated with new fixes, your code doesn't has this fixes until it's deployed.

**Comment by codeofsumit** [comment]
correct 👍

**Comment by codeofsumit** [comment]
so @themre @leekosal you guys haven't found additional bugs?

**Comment by leekosal** [comment]
no more bug. 👍

**Comment by codeofsumit** [comment]
version 0.14.0 is out and adds this feature!

**Comment by gouroujo** [comment]
awesome thanks guys

**Comment by mohammedzamakhan** [comment]
is there a way, where I don't want to snap, suppose it snaps normally, but if I press `shift` or some key, it will not snap?

**Comment by gouroujo** [comment]
You should be able to disable the snap functionality by holding "alt" pressed.
