### ISSUE TITLE
Double click to close polygon

### ISSUE THREAD

**Issue by mdomnita** [codeofsumit/leaflet.pm#128]
Hello, 
Is it possible to close a polygon on double click with the mouse rather than clicking on the first point? 
It's a lot easier to do it like this and prevents the user from created unnecessary nodes by mistake.
Thanks.

**Comment by codeofsumit** [comment]
Hi @mdomnite, thanks for the input. That would be possible.
Before I implement this, I'd suggest you try the new version (coming this week). The cursor point snaps to the first point so it's very easy to close the polygon.
(try it here: https://jsfiddle.net/9d9cn83f/7/ )
If that's still not enough, I'll implement double-click to close.

**Comment by mdomnita** [comment]
Hello @codeofsumit , thanks for the answer. The way the new version works is better but from my point of view double click to close (maybe even a preview of the polygon with w semi-transparent color) would be nice. Anyway, let's see if anyone else agrees to this and I will also take a look through the code these days when I get some time, I didn't have time to try everything out yet.

**Comment by codeofsumit** [comment]
@mdomnita new version is out. Let me know if it works for you

**Comment by codeofsumit** [comment]
I'll close this until @mdomnita or other uses need support for double click to close polygon
