### ISSUE TITLE
How to save such polygon?

### ISSUE THREAD

**Issue by AlexSenchenko** [codeofsumit/leaflet.pm#134]
Could you please tell me how to save such polygon?

**Comment by codeofsumit** [comment]
what do you mean with "save" ? How do you want to save it?

**Comment by AlexSenchenko** [comment]
Save to localstorage or any file format  - and after new session show again

**Comment by codeofsumit** [comment]
you have to program it yourself. This is just a drawing library. You can store your data however you want - localStorage, backend server / database, etc - but this has nothing to do with this library.
