### ISSUE TITLE
Change Marker icon

### ISSUE THREAD

**Issue by giomarino** [codeofsumit/leaflet.pm#135]
I used to define new types of marker with Leaflet.Draw, each one with different options, that feature was very useful and scalable, It will be great to implement a similiar mechanism in this library. 

Actually I'm searching a way (elegant) to set a new marker icon for markers drawn by user.
Any suggestion?

**Comment by codeofsumit** [comment]
mhh I understand what you want. This would be possible with custom options (including CSS classes and icon images).
Can you post a screenshot about the dialog that leaflet.draw uses so you can pass options during draw (without coding)?

**Comment by giomarino** [comment]
@codeofsumit I didn't get what you asked me. I don't use Leaflet.Draw anymore, because it doesn't work well for touch event instead this library works very well on mobile device. 
I just say that was good idea to extends Marker class to realize custom Marker instance.

Now I just want to apply a new icon for a marker, I tried to do this, but doesn't work:
`
var options = {
icon: 'img/newicon.png'
}
map.pm.enableDraw('Marker', options);
`

**Comment by codeofsumit** [comment]
ahh ok sorry I misunderstood. I'll implement it as soon as I find the time (hopefully this week) 👍  thanks for the suggestion!

**Comment by codeofsumit** [comment]
you can soon do this via

```
// optional options for line style during draw. These are the defaults
var options = {
    // custom marker style (only for Marker draw)
    markerStyle: {
        opacity: 0.5,
        draggable: true,
    }
};

// enable drawing mode for shape - e.g. Poly or Line
map.pm.enableDraw('Marker', options);
```

you can try it out with the `develop` branch. I'll implement one more feature before I release

**Comment by VCodepp** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <script src="https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js"></script>
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.css"
    />
    <style>
      html,
      body {
        padding: 0;
        margin: 0;
      }

      #map {
        width: 100%;
        height: 100ch;
      }
    </style>
  </head>

  <body>
    <div id="map"></div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"
    ></script>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.min.js"></script>

    <script>
      // constructor map
      var map = L.map('map').setView([40.992609, 29.055509], 17);
      // set map tile
      L.tileLayer(
        'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',
        {
          attribution:
            'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
          maxZoom: 18,
          id: 'mapbox.streets',
          accessToken:
            'pk.eyJ1Ijoidm9sa2FuY29kZSIsImEiOiJjanRpbDI2ZmIyYmgzNDVtdW56dmVmYnhhIn0.1wCNGjoyadRgZV4lgDdpVQ'
        }
      ).addTo(map);
      // get geojson
      var geoJsonMap = {};
      $.getJSON('geo.json', { async: false }, function(data) {
        L.geoJSON(data, { style: polystyle, pmIgnore: true }).addTo(map);
      });

      // tools
      map.pm.addControls({
        drawMarker: true, // marker
        drawPolyline: true, // çizgi
        drawRectangle: false, // kare
        drawPolygon: false, // poligon
        drawCircle: false, // yuvarlak
        editMode: true, // çizimi değiştirme
        dragMode: false, // çizim yeri değişimi
        cutPolygon: true,
        removalMode: true
      });

      // geojson change different color
      function polystyle(feature) {
        geometryType = feature.geometry.type;
        geometryPropName = feature.properties.name;

        var style = {};
        if (geometryType == 'Point') {
          var icon = L.icon({
            iconUrl: 'rock.svg',
            iconSize: [50, 50],
            iconAnchor: [25, 55]
          });
          style.icon = icon;
        }
        return style;
      }
      var options = {
        // custom marker style (only for Marker draw)
        markerStyle: {
          opacity: 0.5,
          draggable: true
        }
      };
      map.on('pm:drawstart', function(e) {});
    </script>
  </body>
</html>

**Comment by jziggas** [comment]
@codeofsumit The above solves for when you call `map.pm.enableDraw('Marker', options);` manually in code. But what about when a user clicks on the 'Draw Marker' button from the map?

**Comment by codeofsumit** [comment]
I think you can pass this to global options now (check the docs) and it will apply also to the toolbar. 

Can’t test right now I’m on the phone
