### ISSUE TITLE
Autoclose path on double click

### ISSUE THREAD

**Issue by Dahkon** [codeofsumit/leaflet.pm#136]
Would be nice to consider closing drawing path on double click action or escape Key.
Got myself stuck with an unclosable path when markers are too close or on top of each other.

Nice tool either way.

**Comment by codeofsumit** [comment]
@Dahkon I'm aware of the problem, someone else requested this too. I think I'll implement double click. ESC key usually is like a cancel, not a "complete action" key.
Thanks for the feedback - I hope I can push a release by next week including this change.

**Comment by Dahkon** [comment]
You're right for escape key.
Looking forward for double click.

**Comment by codeofsumit** [comment]
@Dahkon it's released now. It created another problem though which is described here:
https://github.com/codeofsumit/leaflet.pm/issues/147

I'd welcome your input on it.

**Comment by kanmaytacker** [comment]
@codeofsumit is the cancel operation on ESC key implemented?

**Comment by codeofsumit** [comment]
@kanmaytacker no, if you would like to add it as a feature request, please open a new issue or feel free to submit a PR 👍 
Have a good start into the new week!
