### ISSUE TITLE
delete mode

### ISSUE THREAD

**Issue by Dahkon** [codeofsumit/leaflet.pm#137]
Is there a way to enter delete mode with code. I'm not using your toolbar.
Or do I have to listen for clicks myself ?
Thanks,

**Comment by codeofsumit** [comment]
Mhh there is a function for it but it won't work calling it from the code. I'll definitely implement this, should be fairly easy.

Until then you can use this:
```
map.eachLayer((layer) => {
  layer.on('click', this.removeLayer);
});
```

**Comment by Dahkon** [comment]
Thanks for the fast reply.
