### ISSUE TITLE
Question for delete function

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#142]
Hello. Will there be any function like:

layer.on('pm:delete', function() {
});

I want to fire some events when a polygon layer is deleted.

thanks.

**Comment by codeofsumit** [comment]
@leekosal that is already built into leaflet itself

```
map.on('layerremove', function() { /* ... */ });
```

API Reference:
http://leafletjs.com/reference-1.0.3.html#map-layerremove
