### ISSUE TITLE
Add support for Multipolylines 

### ISSUE THREAD

**Issue by maxamante** [codeofsumit/leaflet.pm#143]
I load saved polylines from other drawing sessions. Can't figure out how to add them to PM to be editable and snappable. Is there a way to do this?

**Comment by maxamante** [comment]
Nevermind I figured out that the 'MultiPolyline's I'm saving need to loaded as Polylines to avoid the errors.

**Comment by codeofsumit** [comment]
@maxamante good point, I haven't added a hook for MultiPolylines or MultiPolygons yet. To be honest I'm not sure how to handle MultiPolygons compared to a LayerGroup of Polygons. Guess it's basically the same?
I'll check this and add the feature in the future so leave this issue open please 👍

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed

**Comment by Falke-Design** [comment]
We hace implemented this in the current develop branch and will be in the next release
