### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by Burakhan** [codeofsumit/leaflet.pm#144]
I want to add new buttons, such as wall, car, home ... I have no idea how to do it

**Comment by codeofsumit** [comment]
what should these buttons do?

**Comment by Burakhan** [comment]
These buttons can be "marker", "polyline". I want to show on the map and the menu with different icons.
Another issue is;
How can I make a selected element passive if it is a new object? @codeofsumit

**Comment by codeofsumit** [comment]
ok your first issue is: you want the same buttons of leaflet.pm, just with different icons? You can change the CSS style. Just check what classes they have and overwrite from your own CSS.

Regarding your second issue: all buttons have a toggle function - you can trigger the toggle for, let's say the delete button like this:
`map.pm.Toolbar.getButtons().deleteLayer.toggle()`
