### ISSUE TITLE
Draw rectangle

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#146]
Hi, I saw there is already Circle support. Could this be also implemented for Rectangle? Thanks!

**Comment by codeofsumit** [comment]
yes, going to implement it. Need a bit time though.

**Comment by Mesonyx** [comment]
I have this implemented!

If I can be made a contributor, I'm more than happy to PR it, so you can approve/suggest changes!

**Comment by codeofsumit** [comment]
hey @Mesonyx. If you forked the repo and implemented this you can simply create a PR :-). You'll become a contributor automatically once it's merged.
Sorry that it's taking so long, I'm currently working on support for holes.

**Comment by Mesonyx** [comment]
Ahhhh... That's my mistake.

I cloned the repo, not forked it. Didn't realize there was a difference.

HOW DO I OPEN SOURCE, GUYZ?
