### ISSUE TITLE
Redundant coordinate when finish polygon with double click

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/leaflet.pm#147]
Double Click in leaflet will (of course) always fire the regular click twice.

When double clicking to finish a polygon, these are the events firing in order:

Current behavior:
- click (creates vertex)
- click (creates vertex)
- double click (finishes shape).

This behavior means we have two vertexes on the same coordinates - one is redundant.

Desired behaviour:
a)
- click (creates vertex)
- click (does nothing or not fired)
- double click (finishes shape)

or b)
- click (creates vertex)
- click (creates vertex)
- double click (finishes shape).
- cleanup removes the redundant vertex.

b) is kind of hacky while a) needs debounce / delay in the click handler. I might go with a), and devs who want to enable `finishOnDoubleClick` have to live with the delay for the clicks.

I'd like feedback from users on this one.

**Comment by Dahkon** [comment]
Hello,

I agree with B being a little hacky but delay with clicks would be awful with solution A.
So i would go with B anyway and remove the last created vertex on double click.

You must keep good performances you got so far.

**Comment by codeofsumit** [comment]
thanks for the feedback. I can definitely understand that. 🤔  it's a tough one. I have to think a bit more about the solution before implementing it.

**Comment by leekosal** [comment]
Currently, i just snap. I draw three point polygon but when I export it as geojson it has four points (first and last are duplicate)

**Comment by codeofsumit** [comment]
@leekosal that's the geojson spec
http://geojson.org/geojson-spec.html#linestring
It's not the issue discussed here.

**Comment by leekosal** [comment]
i see. thanks 👍

**Comment by themre** [comment]
I tried double click, but it doesn't work. I set up a demo: http://jsfiddle.net/LnzN2/1225/. Could we solve it with right click button (so there is no problem with clicking and adding vertex?

**Comment by codeofsumit** [comment]
@themre finishOnDouble click generally works: http://jsfiddle.net/LnzN2/1226/

The problem in your fiddle is, that the Toolbar doesn't accept the same options as the API.
So you can't pass "finishOnDoubleClick" to it. The relevant issue is #117. Could you add your need in there so we can discuss solutions?

**Comment by themre** [comment]
Could we provide option `finishOn` as name of the event? because then someone could decide to handle closing polygon on different events. like `finishOn: 'contextmenu'`. this line https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Draw/L.PM.Draw.Line.js#L51 would be changed to something like:
```
if(this.options.finishOn) {
      this._map.on(this.options.finishOn, this._finishShape, this);
 }
```

**Comment by themre** [comment]
![context_finish](https://user-images.githubusercontent.com/10845050/30396021-7567f290-98c8-11e7-8c90-1bc10ec3bfda.gif)
this is a sample, how it would work with right click. i can create PR if you would like. I noticed in leaflet docs this event is fired on long press on devices, so this is also covered.

**Comment by codeofsumit** [comment]
that's a neat idea. Please do a PR, I'll review next week 👍

**Comment by themre** [comment]
could you take a look at PR if there is something else i'm missing?

**Comment by cosme-benito** [comment]
The double click little bug is still happening, unfortunately. Sometimes (not always), double click will add two points which are exactly the same. This causes turf to think there's a self-intersection problem with the layer.

I worked around it by closing the polygon if the the new vertex is exactly the same as the previous vertex (in addition to closing the polygon if you clicked the first one). This seems to solve the issue.

**Comment by cosme-benito** [comment]
Unfortunately the double click bug is still happening and I'm not sure how to work around it. Unfortunately the second click generates a new vertex at a slightly different location than the original one. Sometimes this causes a self-intersect issue.

I'm tempted to ignore the last vertex when the user double clicks but that is a far from ideal solution. Anyone managed to work around this?
