### ISSUE TITLE
Is it possible to draw a hole in polygon?

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#150]
I want to draw a hole in polygon. For example, when user hold option key and draw new polygon inside existing polygon, it becomes a hole. 
something like this http://jsfiddle.net/erictheise/VaGy5/

**Comment by codeofsumit** [comment]
yes I'm going to support holes in all shapes in some way or another. It'll take a little time though

**Comment by leekosal** [comment]
Hello,

I downloaded package. So many files. I want to look for only js and css
file. How can i easily test it?
Thanks.

Regards,
Kosa

**Comment by codeofsumit** [comment]
Open terminal, go to project folder. Type

npm install && npm run build

Then there will be a dist folder with CSS and JS files in it. Thanks for trying!

**Comment by codeofsumit** [comment]
Here are two tests that I've posted on twitter yesterday:

![big test](https://user-images.githubusercontent.com/2399810/29863151-15929280-8d6f-11e7-90e8-1935695175aa.gif)
![split polygon](https://user-images.githubusercontent.com/2399810/29863152-15938352-8d6f-11e7-86bf-e5cc47861782.gif)

**Comment by codeofsumit** [comment]
merged it now. Please test it if you can just to make sure. Will be in the next release 👍
