### ISSUE TITLE
Label polygons or annotation layer

### ISSUE THREAD

**Issue by shuaihan22** [codeofsumit/leaflet.pm#153]
Hi, 
Is there a way to add custom labels to polygons? If so, how can I get certain polygon object that I draw?

**Comment by codeofsumit** [comment]
Hi,

you can add labels, but not with this library. It's just for drawing and editing the layers itself. I'm sure there are other plugins for it if leaflet doesn't offer a way itself. 

Regarding your second question:
As described in the readme file, you can listen to the pm:create event which passes an event parameter to your callback function that includes the layer object. 
I'd give you a code example but I'm in a bar on my phone right now 😅. Please read the README for examples.

**Comment by shuaihan22** [comment]
thanks, it works for the second question.
