### ISSUE TITLE
how get all objects

### ISSUE THREAD

**Issue by binjan** [codeofsumit/leaflet.pm#157]
Hi! Thank you for plugin!
I need to get all drawn objects from map.
Can I get objects similarly geoJson?
```
        geojson.eachLayer(function(layer){
...
        });
```

**Comment by codeofsumit** [comment]
leaflet has a function to get all layers on a map:

```
map.eachLayer(function(layer) {})
```
http://leafletjs.com/reference-1.0.3.html#map-eachlayer
this gives you all layers of the map.

Unfortunately you can't know if they are drawn by leaflet.pm or not.

If you want just the layers that were drawn with leaflet.pm you could listen to the `pm:create` event and save your layer reference into an array.

Hope this helps!
