### ISSUE TITLE
Get the Created layers as single layerGroup

### ISSUE THREAD

**Issue by nagasreev** [codeofsumit/leaflet.pm#158]
Hi Sir, Here is the problem i am facing
I generally use **'pm:create'** event to get the layer i created.

lets assume, i created 100 points, Lines and polygons. 
then i used the **'EDIT' tool to adjust or correct them**. Now on a click of a button, can i get the whole features i created on the map as one Layergroup.

So that i can convert that to json and save it to database

**Comment by codeofsumit** [comment]
Hi,

you should create the layerGroup yourself and add the layers you create to it.
Something like this:

```
const myLayerGroup = L.layerGroup([]);
map.on('pm:create', (e) => {
  myLayerGroup.addLayer(e.layer);
});
```

Then, even after you edit them, you can refer to your layergroup and do whatever you want with them. Grouping, storing, saving is totally up to you. Leaflet.pm just helps you create the layers - the rest is just regular javascript and leaflet.

Let me know if it helps.

**Comment by nagasreev** [comment]
Thank you sir.  It helps and will take it forward.
