### ISSUE TITLE
How to remove all leaflet.pm layers at a time from a map

### ISSUE THREAD

**Issue by dksivagis** [codeofsumit/leaflet.pm#159]
Hi , may i please know how to remove all the leaflet.pm layers in one shot.
Any thing like map.pm.removeLayers();

**Comment by codeofsumit** [comment]
There are no "leaflet.pm"-layers. You create leaflet layers with leaflet.pm.
So you can loop through all layers of the map and remove the ones you want:

```
map.eachLayer((layer) => {
  layer.remove();
});
```

As leaflet.pm just created leaflet layers, please look into the leaflet documentation to see how to handle your layers.
