### ISSUE TITLE
Possible to protect certain layers?

### ISSUE THREAD

**Issue by GeoTob** [codeofsumit/leaflet.pm#160]
Cant find anything in the readme about this, but it'd be nice if I could protect a layer from all edits and deletes.

For now I simply removed the `pm` object from the Layer instance, but that's not very elegant and leads to errors on delete:

```
Uncaught TypeError: Cannot read property 'dragging' of undefined
```

**Comment by codeofsumit** [comment]
hi @GeoTob good point.
This is something not currently in the library but let's think about how we could add this.

a) A clean solution would be to remove auto-initialization of leaflet.pm and add the layers that leaflet.pm should handle via init options. This would be a breaking change though.

b) Give layers some property, like `immutable` and leaflet.pm ignores those.

c) Add custom onClick handlers to the toolbar buttons so you could pass/overwrite the click handler, and enable edit just for the layers you want for that Edit button

d) revert the initialization somehow on some layers 🤔 

e) make leaflet.pm handle / ignore layers that don't have the `pm` object on them.

I prefer e) to be honest.
What do you think?

**Comment by GeoTob** [comment]
Thinking about how layers are added in Leaflet, I think I might prefer b) over e). To be honest though, I think both are perfectly fine.

```js
// b)
let layer = L.tileLayer(
  'http://{s}.somedomain.com/{foo}/{z}/{x}/{y}.png', 
  {pmIgnore: true}
);

// e)
let layer = L.tileLayer('http://{s}.somedomain.com/{foo}/{z}/{x}/{y}.png', {});
delete layer.pm  // extra step required / easy to forget
```

Option c) sounds sensible too: the toolbar is supposed to toggle edit mode globally, so it makes sense for users to overwrite the `onClick` behaviour if they want to restrict edit mode to certain layers.

Another way to solve this would be to add an `ignoreLayers` attribute to the toolbar options: 

```js
const options = {
  position: 'topleft',
  drawMarker: false,
  ignoreLayers: [layer1, layer2, layer3]
}
map.pm.addControls(options)
```

**Comment by codeofsumit** [comment]
@GeoTob great suggestions.
Regarding `ignoreLayers` in the Toolbar: you can trigger global edit mode via code as well. So whatever solution we come up with needs to be available through the API, and the toolbar just uses that API.

I like b) - I'll do some testing to see if I run into trouble. I'm very busy this week so this might end up on the weekend.

**Comment by GeoTob** [comment]
> you can trigger global edit mode via code as well

True, strike that suggestion :)
