### ISSUE TITLE
Assigning the controls to HTML toolbar buttons

### ISSUE THREAD

**Issue by dksivagis** [codeofsumit/leaflet.pm#161]
Hi sir, 
Its a basic question.
You have given an easy approach of assigning the events to our custom buttons and call the function from outside the map (eg attaching enable draw function to html button ==> **map.pm.enableDraw('Poly', options);**)

Most of the major plugins does not have such binding functions. is there any way we can make ourself?  (Eg: Leaflet.PolylineMeasure)

Thank you
Siva

**Comment by codeofsumit** [comment]
Hi there,

uhh not without changing the code of the other plugins I think.
They basically need to provide a proper Javascript API for all functionality, and use it themselves for their toolbars. I want leaflet.pm to be fully functional, even if the toolbar is completely disabled.
That's something you should ask for in the other plugin repos - sorry.

I'm glad you like that functionality! 👍 

Feel free to reopen if you have more questions

**Comment by dksivagis** [comment]
Great sir., Thanks for the functions to access the events easily.
