### ISSUE TITLE
Marker creation not Stopping

### ISSUE THREAD

**Issue by dksivagis** [codeofsumit/leaflet.pm#165]
Hi Sir,

I made **2 buttons** with names _'Create points'_ and _'Create polys'_

On click of  _'Create Points'_ , i enabled the marker drawing

> map.pm.enableDraw('Marker',options)

On click of _'Create Lines'_, i enabled the Polygon drawing

> map.pm.enableDraw('Poly',options)

The problem is : 
When i click   _'Create Points'_ , i am able to draw multiple marker's
Next When i click _'Create polys'_, and then click on map, the markers are still being created.
Only after clicking the _'Create polys'_ 2times,  the polygon creation starts.
I tried with `map.pm.disableDraw('Marker')` before clicking the  _'Create Lines'_ button. But not working. 

Please let me know if i am doing wrong.

**Comment by dksivagis** [comment]
Thank you Sir. I found the solution.
I used `map.pm.toggleGlobalRemovalMode();` at the starting point inside the click event function and then enabling the Drawing tools.

If this is the right approach, kindly close this issue.
thank you

**Comment by codeofsumit** [comment]
hey, good point!
Have a look at this function - this is how I handle it inside leaflet.pm
https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Toolbar/L.PM.Toolbar.js#L65

So when button A is clicked, I check for other active buttons and then trigger a click (so it deactivates other modes).

If you look closer into the linked `L.PM.Toolbar.js` file, you'll see that internally I use `this.map.pm.Draw.Line.toggle();`. This makes it easier for you to enable/disable the drawing modes.
All these classes have `toggle()`, `disable()`, `enable()` and `enabled()`. With these functions you should be able to properly build your own toolbar 👍 .

Let me know if it works.

**Comment by dksivagis** [comment]
Great Information. Thank you sir..
