### ISSUE TITLE
"pm:edit" Event is not fired on Circles

### ISSUE THREAD

**Issue by galileopy** [codeofsumit/leaflet.pm#170]
It seems that Edit.Circle doesn't fire events on `_moveCircle` & `_resizeCircle`, I added them on a fork, I don't know if this is a real issue, or if I was not able to properly capture the events, please let me know if I can PR, also, I didn't find a contributing guideline.

**Comment by codeofsumit** [comment]
hmm might be that I forgot them. Please PR - i'll either merge it or better get the idea of what needs to be done
