### ISSUE TITLE
IE11 throws on L.pm.enabled() 

### ISSUE THREAD

**Issue by thomasvoigt** [codeofsumit/leaflet.pm#173]
Hi there!

Yeah, I know, IE support is a major PITA. Alas, I couldn't find a disclaimer telling me not to use esoteric browsers (and our client really loves his IE user base), so here I am, nagging...

`L.pm.enabled()` uses `Array.prototype.find()` internally, and that only works in IE 12 (Edge) and up. 

As state tracking is quite complex from the outside, I'd very appreciate a (more) cross-browser implementation of `enabled()`. 

Thanks and best regards,
Thomas

**Comment by codeofsumit** [comment]
No worries I'll try to support as much as I can, I just don't have IE on me dev machine.
I will fix this but again, please note, I'm on vacation starting tomorrow. I hope to fix and release a new version in the week starting at 17th of July 🤞 .

**Comment by codeofsumit** [comment]
@thomasvoigt do you mind (as I don't have IE11 anywhere) checking if this branch works for you?
https://github.com/codeofsumit/leaflet.pm/tree/IE11-Array.find

Simply clone it locally and run `npm run dev`. It'll create a `dist` folder with the js and css files in it for you to try.

Does this work for IE11?

**Comment by codeofsumit** [comment]
@thomasvoigt the solution seems to be that I have to include babel-polyfill with this library. Although I wanted to avoid adding any dependencies to leaflet.pm.
Can you please also try to install `babel-polyfill` in your project and load it before your other code, (e.g. with a webpack entry addition, or import in your main file) and see if it works?

If yes, you can fix this by yourself by adding IE11 polyfills to your project.

**Comment by thomasvoigt** [comment]
Yes, `babel-polyfill` works, but nearly qadruples the library's size. That's quite a hit for [some 20 lines of code](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill). So I'd rather prefer not to...

As `Array.prototype.find` seems to be the only problematic ES6 function at the moment,  I'm fine with either:
- bundling and requiring a more lightweight polyfill for `Array.prototype.find`, e.g.  [https://www.npmjs.com/package/array.prototype.find](https://www.npmjs.com/package/array.prototype.find) (~98kB)
- including the polyfill code directly (~2kB)
- simply documenting the fact that for IE<12 a polyfill should be considered ("bring your own code")

Best regards,
Thomas

**Comment by codeofsumit** [comment]
@thomasvoigt I'm fine with including a small polyfill in the lib directly but I need you to confirm the polyfill is working. Can you please add this to your project real quick and see if it works?

```
Array.prototype.find = Array.prototype.find || function(callback) {
  if (this === null) {
    throw new TypeError('Array.prototype.find called on null or undefined');
  } else if (typeof callback !== 'function') {
    throw new TypeError('callback must be a function');
  }
  var list = Object(this);
  // Makes sures is always has an positive integer as length.
  var length = list.length >>> 0;
  var thisArg = arguments[1];
  for (var i = 0; i < length; i++) {
    var element = list[i];
    if ( callback.call(thisArg, element, i, list) ) {
      return element;
    }
  }
};
```

**Comment by thomasvoigt** [comment]
Yes, this one works, too.

**Comment by codeofsumit** [comment]
@thomasvoigt great, added it here:
https://github.com/codeofsumit/leaflet.pm/pull/177

do you have a chance to test that branch?
I'd merge it tomorrow and do the release by the end of the week 👍

**Comment by thomasvoigt** [comment]
Works like a charm, thanks!
