### ISSUE TITLE
long time for activate the vertices in editing mode

### ISSUE THREAD

**Issue by josejaner** [codeofsumit/leaflet.pm#174]
If a geojson is big, in editing mode it takes a long time for activate the vertices, I recommend selecting the element before.

Sorry for my English
Excellent plugin.. !Congratulations!

**Comment by johnsoncherian** [comment]
Hi I am facing the same issue with a large GeoJSON file. How did you handle this case.? I am pasting my code below. `var layerObj = L.geoJSON(geojsonFeature).addTo(map);
var options = {
	position: 'topleft',
	drawPolygon: true,
	editPolygon: true,
	deleteLayer: true
};
map.pm.addControls(options);
layerObj.pm.enable(options);`.
Here `geojsonFeature` is my GeoJSON data

**Comment by codeofsumit** [comment]
@josejaner how big is your geojson? Can you provide a file here so I can test?

**Comment by codeofsumit** [comment]
I'll close this now - please provide a file to test or a JSfiddle and reopen.
