### ISSUE TITLE
Not working event 'pm:drawstart'!

### ISSUE THREAD

**Issue by denny123** [codeofsumit/leaflet.pm#179]
For version 0.17.1.
Not working event 'pm:drawstart' for marker drawbutton.
P.S.: no folder 'dist' in download source, i get from https://unpkg.com/leaflet.pm@0.17.1/dist/leaflet.pm.min.js

**Comment by codeofsumit** [comment]
@denny123 can you elaborate the issue with the `dist` folder? I didn't get that

**Comment by denny123** [comment]
nevermind folder 'dist' if this source is correct, i need elaborate issue with the 'pm:drawstart' first.

**Comment by codeofsumit** [comment]
the `pm:drawstart` issue is a bug. Just fixed it. Will release later today or tomorrow 👍

**Comment by denny123** [comment]
0.17.2 version or current?

**Comment by codeofsumit** [comment]
I'll release 0.17.2 today or tomorrow that includes the fix.

**Comment by denny123** [comment]
Ok, thanks!

**Comment by codeofsumit** [comment]
@denny123 just released it

**Comment by denny123** [comment]
i see, and i see issue with 'dist' too - thanks, but i have more issue(pm:remove) - may be more create issue this -)
