### ISSUE TITLE
No dist in release zip 

### ISSUE THREAD

**Issue by sshikov** [codeofsumit/leaflet.pm#180]
>Install Manually

>Download the latest release here. Include leaflet.pm.min.js and leaflet.pm.css in your project.

There is no such files in release archive.

**Comment by codeofsumit** [comment]
hmm you're right. As I removed bower support the dist folder is created during `npm install`.
I don't want to include the dist folder in version control.
I have to check how other libs are solving this.

**Comment by codeofsumit** [comment]
@sshikov I'll change the description of Install Manually to 
>>>
Download [`leaflet.pm.css`](https://unpkg.com/leaflet.pm@0.17.1/dist/leaflet.pm.css) and [`leaflet.pm.min.js`](https://unpkg.com/leaflet.pm@0.17.1/dist/leaflet.pm.min.js) and include them in your project.

**Comment by sshikov** [comment]
Thats fine, thank you.
