### ISSUE TITLE
Not working 'pm:drawend' for markers!

### ISSUE THREAD

**Issue by denny123** [codeofsumit/leaflet.pm#182]
For version 0.17.2.
Not working 'pm:drawend' for markers and 'pm:drawend' = 'pm:create' for polygons(may be more).
Maybe set 'pm:drawend' for button how for 'pm:drawstart'?
For marker working 'pm:create'.

**Comment by codeofsumit** [comment]
yup, sorry should've added this before too - I was fixing the previous issue on the go before.
Will fix this weekend!

**Comment by denny123** [comment]
fixed on version 0.17.2?

**Comment by codeofsumit** [comment]
@denny123 it's released now
