### ISSUE TITLE
Polygon's bounding rectangle ( getBounds() ) not updated after it has been edited

### ISSUE THREAD

**Issue by adamtLICOR** [codeofsumit/leaflet.pm#183]
First off, love `leaflet.pm`!

Anyway, I'm working with a [point-in-polygon detection library](https://github.com/hayeswise/Leaflet.PointInPolygon) to detect points within `leaflet.pm` Polygons.

To test, I've drawn a bunch of red dots on the map, coloring them green if they are inside the Polygon:
![square_works](https://user-images.githubusercontent.com/16004285/28482099-88e52368-6e2c-11e7-9601-0d745fe41b35.png)

Unfortunately, it seems that editing a `leaflet.pm` Polygon by dragging its vertices via `leaflet.pm`'s Edit mode doesn't update the shape's bounding rectangle, as returned by the`getBounds()` methods, which is required by the pip library's algorithm:

![penta_does_not](https://user-images.githubusercontent.com/16004285/28482139-b923a162-6e2c-11e7-955a-751d5ae3b909.png)

I've tracked this issue down to a `leaflet.pm` Polygon not updating its bounding rectangle after being edited via dragging its vertices.

Here is the bounding box for the original square, drawn in `leaflet.pm`:

![sw_coords](https://user-images.githubusercontent.com/16004285/28482213-06aef5b2-6e2d-11e7-8377-6d8b507fe635.png)

And here is the bounding box for the updated shape, pulled into a pentagon via `leaflet.pm`'s editing tools:

![penta_coords](https://user-images.githubusercontent.com/16004285/28482241-2274dabe-6e2d-11e7-9892-76265cfbc2c5.png)

Notice that they are exactly the same, even though the Northeast bounds should have changed slightly, to accommodate the new point.

For reference, if I draw the exact same pentagon first (without editing a square to create it), everything works fine:

![full_penta_works](https://user-images.githubusercontent.com/16004285/28482276-46aaa918-6e2d-11e7-8c9a-2ce29437f2a5.png)

And, as expected, the bounding rectangle as returned by `getBounds()` is slightly different, to accommodate the northernmost point:

![full_penta_coords](https://user-images.githubusercontent.com/16004285/28482351-94931bec-6e2d-11e7-9eb7-ec23e60fe4a8.png)

Any idea why the bounding rectangle isn't updating? I'm going to continue to look into this issue (and will happily make a PR if I find anything), but I'm hoping you might be able to point me in the right direction?

**Comment by codeofsumit** [comment]
Hi there, very interesting!
Try a `pm:edit` event on the map and see if the return layer has the updated bounding rectangles:

```
polygon.on('pm:edit', function(e) {
  console.log(e.layer.getBounds());
  console.log(polygon.contains(yourGridPoints));
});
```

If that works, you probably have to re-trigger the calculation of the point-in-polygon library when a layer is edited.
If the bounds are still wrong within the event I'd have to investigate more.

Let me know!

**Comment by adamtLICOR** [comment]
Hello, again.

Unfortunately, logging out the bounds after both a `pm:edit` and `pm:dragend` event indicate that the bounds are not updated correctly within those events either. 😞

**Comment by codeofsumit** [comment]
hmm ok, I'll investigate over the weekend!
If you are able to provide a JSfiddle with your example, it'd be helpful too!
Thanks for reporting I'll keep you updated

**Comment by adamtLICOR** [comment]
Here you go: https://jsfiddle.net/Mesonyx/648yvuop/21/

To use it:
1. Draw a shape on the map, and then click the DRAW DOTS button above the map. It should fill in the entire shape with green dots.
2. Click the REMOVE DOTS button above the map
3. Edit the polygon in such a way that part of the new polygon is **outside** the original polygon's rectangular bounding box (converting a square into a pentagon, as in my initial Issue post, is the easiest way to accomplish this). 
4. Click DRAW DOTS again -- only the dots within the original polygon's bounding box will be green.

A few notes to help you make sense of the source code (in case you need it):
- It's written in `Vue.js` 2.0
- Only the last shape drawn is checked for points within it (to make your life easier, only draw one shape, and just re-run the fiddle if you need to draw another for any reason)
- I included the `Leaflet.PointInPolygon` library ahead of the `Vue.js` code, so you can see the part of the algorithm that's getting tripped up (it automatically ignores any points outside the bounding rectangle, in order to skip unnecessary calculations)

**Comment by codeofsumit** [comment]
thanks for the fiddle. Just a side thought: Is it possible that the dots (L.circle) should have `pmIgnore` due to performance reasons? Otherwise the Edit Button will try to enable all of them to edit - is this no problem in your app?

**Comment by codeofsumit** [comment]
so I made it work this far: 
![boundsissue](https://user-images.githubusercontent.com/2399810/28501896-10314ada-6fe6-11e7-93a6-0402df75d40b.gif)

As you can see, the points update correctly for:
1. editing the polygon and making it smaller
2. dragging the polygon

It's not working for
1. editing the polygon and making the polygon larger than it's original bounding box (until being dragged).

This is very weird to me. I have to investigate more.
If you want to see how I made it this far, here's the updated fiddle:
https://jsfiddle.net/648yvuop/22/

**Comment by adamtLICOR** [comment]
Hmmm -- that's interesting (the dragging fixing it, I mean).

If nothing else, I can look into simulating the dragging behavior after a vertex is updated in my app (so whatever process is fixing the bounding box behind the scenes automatically rebuilds the box)

And I should have mentioned this earlier, but making a Polygon smaller actually still "works" (because the bounding box is bigger than the new shape).

It's only ever making a Polygon bigger than its original bounding box that causes a problem.

**Comment by adamtLICOR** [comment]
I fixed it!

Kind of...

I still want to investigate further, because my workaround feels like too much hax.

But after investigating based on your fiddle, I noticed this line of code in `Drag.js`:

`this._layer.setLatLngs(newLatLngs).redraw();`

After a `pm:markerdragend` event, the **Polygon** has an up-to-date **LatLng** coord array, but an old bounding box. However, if I call `setLatLngs()` with those new coords, it updates the bounding box!

```
vm.lastShape.on('pm:markerdragend', (e) =>{
    console.log(e.target.getBounds()._northEast.lat, e.target.getBounds()._northEast.lng)
    e.target.setLatLngs(e.target._latlngs[0]).redraw()
    console.log(e.target.getBounds()._northEast.lat, e.target.getBounds()._northEast.lng)
})
```
Logging out the old and new bounding boxes show a change in size:
![screen shot 2017-07-24 at 11 34 23 am](https://user-images.githubusercontent.com/16004285/28533839-329fabc4-7064-11e7-8347-018bcb69ad3d.png)

And a **Polygon** that stretches beyond its original bounding box now properly updates to use a new bounding box:

![screen shot 2017-07-24 at 11 34 32 am](https://user-images.githubusercontent.com/16004285/28533877-51537974-7064-11e7-950f-185ec2782de1.png)

Again, this is not 100% ideal, but it's at least given me a place to look for a more "correct" improvement.

I'll keep working on this today, and potentially fork and PR if I get something that works better.

**Comment by codeofsumit** [comment]
@adamtLICOR thanks for this! I traced down the issue and also asked the question to clarify here:
https://gis.stackexchange.com/questions/249839/leaflet-redraw-doesnt-trigger-bounds-update-like-setlatlngs

I'll have a new branch ready today - it'd be really helpful if you could check the branch out and test it against your codebase. Would that be possible? I'll post the link to the branch as soon as I'm ready

**Comment by codeofsumit** [comment]
@adamtLICOR here's a new fiddle - seems to be fixed with [this branch](https://github.com/codeofsumit/leaflet.pm/pull/186):
https://jsfiddle.net/648yvuop/23/

**Comment by adamtLICOR** [comment]
Hey, **PR** looks great!

I'm going to pull this down now and test it out!

I'll report back ASAP.

Thanks again for the help!

**Comment by adamtLICOR** [comment]
I commented directly on the **PR**, too, but this new branch seems to work.

(See the **PR** for screenshots)

**Comment by codeofsumit** [comment]
fixed by https://github.com/codeofsumit/leaflet.pm/pull/186
