### ISSUE TITLE
Polygon/Line isn't editable anymore after deleting one of its points (Leaflet 1.1.0)

### ISSUE THREAD

**Issue by tkleinke** [codeofsumit/leaflet.pm#184]
After deleting a point of a polygon or a line it's not possible to create new points or move existing ones. The geometry is still draggable though. The bug only occurs with leaflet 1.1.0, with 1.0.3 everything works fine.

**Comment by codeofsumit** [comment]
Argh crap ok thanks for reporting. They changed something that broke this plugin - we noticed the problem in #183 and you just gave us the reason. Thanks!
I'll dig into it and fix it asap

**Comment by codeofsumit** [comment]
Seems like it's a bug in leaflet
https://github.com/Leaflet/Leaflet/issues/5638

**Comment by tkleinke** [comment]
Thanks for looking into it! I'll switch back to 1.0.3 for now.

**Comment by codeofsumit** [comment]
@tkleinke seems to be fixed in their latest master
https://jsfiddle.net/3v7hd2vx/363/

hope they'll release soon 🤞

**Comment by codeofsumit** [comment]
The leaflet issue is closed so I'll close this one too.
The next leaflet release will include the fix - please use 1.0.3 until then.
