### ISSUE TITLE
show radius option

### ISSUE THREAD

**Issue by tecnocoma** [codeofsumit/leaflet.pm#188]
It would be very useful to set an option for showing a tooltip with realtime radius measure (in km) while drawing circle, not only on creating but also on editing. Leaflet.draw does something similar (see http://jsfiddle.net/88bdrzkr/13/ ) but only on creating...and your plugin is much better. But lacks of this useful functionality...that others people on the web asked without answer (for Leaflet). Do you think it would be possible to add it? Thanx a lot for your effort anyway.

**Comment by codeofsumit** [comment]
@tecnocoma users of leaflet.pm used this plugin in addition to leaflet.pm in the past
https://github.com/ProminentEdge/leaflet-measure-path

I have to implement the same functionality at car2go pretty soon. If the leaflet-measure-path and leaflet.pm combo is not sufficient, I'll add it here as an option.

I'll keep you posted about that and please, try `leaflet-measure-path` in the meantime and let me know if it works for you

**Comment by codeofsumit** [comment]
@tecnocoma have you tried using leaflet-measure-path?

**Comment by codeofsumit** [comment]
@tecnocoma I'll close this for inactivity. Please reopen if you have tried leaflet-measure-path or if other users would like to see this added to leaflet.pm instead.
