### ISSUE TITLE
Some events not firing

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#190]
Hi,
I'm using latest leaflet.pm version with Leaflet 1.0.3 and some events aren't firing (markerdragend, dragend ,  ...) but create and remove events do fire. Does also someone else notices this problem?

**Comment by codeofsumit** [comment]
hi @themre - can you create a JSfiddle so I can see the issue? Then I can debug and help/fix

**Comment by themre** [comment]
http://jsfiddle.net/LnzN2/1101/
I'm trying to detect when I draw points of polygon and when I finish editing. Basically I want to detect all editing events so start and finish of edit mode would be enough (so I could get all shapes that were drawn).

**Comment by codeofsumit** [comment]
@themre how about this?
http://jsfiddle.net/LnzN2/1102/

there is no `pm:edit` for the map, it's only for the layers.
So something like this should work:

```
// listen to when a new layer is created
map.on('pm:create', function(e) {
  console.log(e)

  // listen to when a new layer is created
  e.layer.on('pm:edit', function(e) {
    console.log('edit', e)
  });
});
```

does that solve your issue?

**Comment by themre** [comment]
I will try later today,thanks. Does this fire also when dragging nodes? So I can save changes.

**Comment by codeofsumit** [comment]
It fires after you dragged a node and/or created/deleted a new node

**Comment by themre** [comment]
hi, sorry for being late. I tried it but it fires when your start and release the drag. I tried using only 
```
e.layer.on('pm:dragend', function(x) {
    console.log('dragend', x)
  });
```
on newly created layer and it doesn't fire. How can I use this?

**Comment by codeofsumit** [comment]
@themre 

```
e.layer.on('pm:edit', function(x) {
  console.log('edit', x)
});
```

fires whenever the layer **changes**.
That means AFTER you dragged an existing vertex.
Or as soon as you add a new vertex.

If you simply drag one of the "middlemarkers" (the small dot between two vertexes), you basically create AND edit a vertex so it fires when you start dragging (because you created a vertex) and when you release it (because you edited the newly created vertex).

**Comment by themre** [comment]
yeah, `pm:edit` works fine, I was just asking how to use `pm:drag` because I'm not able to call it.In the docs it says that this event is also available, just don't know in which case it is fired.

**Comment by codeofsumit** [comment]
@themre ahh ok. I thought you wanted to have events when you start and end dragging a vertex. If you want that you can use this:
```
// listen to when a marker of a polygon-vertex is being dragged
polygonLayer.on('pm:markerdragstart', function(e) {//...});
polygonLayer.on('pm:markerdragend', function(e) {//...});
```
See this fiddle as an example: http://jsfiddle.net/LnzN2/1116/
(Draw a polygon, enable edit mode and start editing it (look into the console too))

`pm:drag` is fired when you move the whole layer. See this fiddle:
http://jsfiddle.net/LnzN2/1117/
(Draw a polygon, enable edit mode and start moving it as a whole (look into the console too))

Does that help you?

**Comment by themre** [comment]
perfect. don't know why `markerdragend` didn't work, perhaps there was some typo. oh well... thanks again :)

**Comment by josejaner** [comment]
Just as there is an 'pm:drawstart' event, it would be ideal if there were an event
'pm:editstart', to enable or disable layers.

map.on('pm:editstart', function(e) {
	road.pm.enable(options);
	road.pm.disable();

        road2.pm.enable(options);
});

**Comment by codeofsumit** [comment]
@josejaner you basically want to hook into the "global edit mode" button and add you own logic, right?
I'd suggest to add your own button for that. The "global edit mode" button just loops through all map layers and fires `pm.enable()` them.

**Comment by cksadra** [comment]
can you help me? @codeofsumit
All events are turned off when dragging a layer or marker and can get coordinates ...
But when downloading coordinates from json or any ... no event fired.
