### ISSUE TITLE
possibility to fire value of edited layer with 'pm:edit' event ?

### ISSUE THREAD

**Issue by bertrandmd** [codeofsumit/leaflet.pm#192]
Hello, 

do you think is possible to add a hook on layer who been edited when fire 'pm:edit' event ?

it could be a good way to be aware of which layer been edited, especially to communicated with backend.

thanks for your reply and for your amazing plugin !!

**Comment by codeofsumit** [comment]
@bertrandmd Hi,

do you want the layer or the vertex/coordinate?

if you have:
```
layer.on('pm:edit', function(e) {//...});
```
the edited layer is obviously `layer`.

Maybe I misunderstood your question? It'd help if you can provide a code example too.

**Comment by bertrandmd** [comment]
Hi, 
thanks for your fast reply.

if you use 
```javascript
layer.on('pm:edit', function(e) {
    console.log(e)
});
```
with `e` you could not retrieve the layer who been edited ?

https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Edit/L.PM.Edit.Line.js#L327
I've changed with `this._layer.fire('pm:edit', {layer: this._layer});` and then I can refer to the updated line layer at `e.layer`.
Do you recommended another way to do this ?

thanks

**Comment by codeofsumit** [comment]
this sounds like a bug. I'll get it working again - pinky swear 🤞

**Comment by codeofsumit** [comment]
@bertrandmd ok I checked - it's available under `e.target`. Does that work for you? If not, could you provide a JS fiddle that shows the error?

**Comment by josejaner** [comment]
Based on this information, I have tried in several ways to do the following:
	road.on('pm:edit', function(e) {
		 var layer =e.target;
		 var infoJson=""+ JSON.stringify(elemento.toGeoJSON()); 
		  alert(infoJson);
	});
Do you have a different path for this?

**Comment by codeofsumit** [comment]
closed. Please reopen if the provided suggestion doesn't work and the issue is still present
