### ISSUE TITLE
Clean the trace after creating a layer?

### ISSUE THREAD

**Issue by josejaner** [codeofsumit/leaflet.pm#199]
Is it possible to clean the trace, once a new item is created?

map.on('pm:create', function(e) {
    {my logic}
    map.pm.clearDraw('Line');
});

**Comment by codeofsumit** [comment]
@josejaner you mean deleting the drawn layer?
Just like you would with regular leaflet:

```
map.on('pm:create', function(e) {
  {my logic}
  var myLayer = e.layer;
  map.removeLayer(myLayer);
});
```

**Comment by josejaner** [comment]
Thanks for your interest and help, it's an excellent project.

**Comment by codeofsumit** [comment]
did my comment solve your problem? Let me know if there is an issue with leaflet.pm! 👍
