### ISSUE TITLE
error in Maximum call stack size exceeded at Array.find

### ISSUE THREAD

**Issue by josejaner** [codeofsumit/leaflet.pm#200]
- I get this error frequently...
L.PM.Edit.LayerGroup.js?2cd0:89 Uncaught RangeError: Maximum call stack size exceeded at Array.find (native) at enabled

**Comment by josejaner** [comment]
The error is displayed when combining leftlet.pm and leaflet.polylineDecorator

**Comment by codeofsumit** [comment]
Hi @josejaner, please provide a JSfiddle, showing the error on a button click or something

**Comment by codeofsumit** [comment]
@josejaner I'll close this issue due to inactivity. Feel free to open again with a JSfiddle so I can see and reproduce the issue easily - I'm happy to debug this with you.
