### ISSUE TITLE
Native way to limit feature count?

### ISSUE THREAD

**Issue by latitudehopper** [codeofsumit/leaflet.pm#201]
I want to limit the number of features that can be created. Is there a native way within leaflet.pm?

**Comment by latitudehopper** [comment]
This is odd (probably obvious to you). Once I have edited the map, I can no longer clearLayers() or removeLayer() from my map. If I call either of these pre-edit, it works. What have I missed?

```
const map = L.map('map').setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

const markers = L.geoJson(null, {pmIgnore: false}).addTo(map);

var options = {
    position: 'topleft', // toolbar position, options are 'topleft', 'topright', 'bottomleft', 'bottomright'
    drawMarker: true,  // adds button to draw markers
    drawPolygon: true,  // adds button to draw a polygon
    drawPolyline: true,  // adds button to draw a polyline
    drawCircle: true,  // adds button to draw a cricle
    editPolygon: true,  // adds button to toggle global edit mode
    deleteLayer: true   // adds a button to delete layers
};

  markers.addData({{{record.geom}}})
  map.fitBounds(markers.getBounds())


map.on('pm:edit', function(e) {
  markers.addData(e.layer.toGeoJSON())
});
map.on('pm:create', function(e) {
  map.removeLayer(markers)
  markers.addData(e.layer.toGeoJSON())
});

map.pm.addControls(options);
markers.pm.enable(options);

function clearMap(){
  markers.clearLayers()
}
```

**Comment by codeofsumit** [comment]
can you please create a jsfiddle showing the problem and what you try to achieve? I think this is doable natively with leaflet functionality.

**Comment by latitudehopper** [comment]
HI, Sumit. I have resolved this by using Leaflet Draw. Essentially, to allow for only one geometry within the layer I am triggering a maker.clearLayers() on the events that are relevant. In draw this works but I couldn't get it to work with leaflet.pm as it only seems to work in the first instance, any further layer edits do not clear the layers. It could possibly be a code issue on my side, either way, I have worked around it. Thanks for the reply.

**Comment by codeofsumit** [comment]
ok, let me know if you need additional help 👍

**Comment by ivanjaros** [comment]
Yeah, limiting user to max number of shapes would be nice.

**Comment by themre** [comment]
I solved this by doing this:
```
 // once I start drawing I want to clear all my other layers
this.mainMap.on('pm:drawstart', (e) => {
      // you need to remove layers only from GeoJSON layer that has features
      this.editableLayers.eachLayer(layer => {
        this.mainMap.removeLayer(layer);
      });
    });
```

**Comment by codeofsumit** [comment]
@themre thanks for your input.
@ivanjaros that's definitely something you should provide via your app logic. Use the hooks of leaflet.pm and as soon as your defined limit is hit, deactivate leaflet.pm, hide the toolbar, or remove any layer that is created via `pm:create`.

**Comment by themre** [comment]
`clearLayers()` doesn't work since if has to be a group, which geoJson isn't.

**Comment by ivanjaros** [comment]
@themre so you have to somehow store the layers in specific variable to access them?

**Comment by ivanjaros** [comment]
Also, is there an alternative leaflet library I can look at instead of this one that would suit my needs better?

**Comment by themre** [comment]
yes. i'm using this with React. but for this feature I think it's enough to pass one variable `maxFeatures` and if it exists, it stores it in internal array and then remove old items once it's full.

**Comment by ivanjaros** [comment]
Thank's. I'm currently implementing previous verison of code into Vue....finally I have solved this by:

```
document.querySelectorAll('.leaflet-pm-toolbar .control-icon').forEach((element) => element.addEventListener('click', () => unsetMapArea()));

document.querySelector('.leaflet-pm-toolbar .leaflet-pm-icon-delete').addEventListener('click', (event) => event.stopPropagation());
mapObject.addEventListener('pm:create', (event) => setMapArea(event) );
```

Where the `setMapArea` will push the layer into `mapPoly` variable and the `unsetMapArea()` will `mapPoly.forEach((layer) => mapObject.removeLayer(layer));`

**Comment by themre** [comment]
no, that's ugly. especially querySelectorAll. e.g. in React I define once component is mounted:
```
   this.mainMap = L.map('mainMap', {..})

   this.mainMap.on('pm:create', (e) => {
      this.updateLayers(e.layer)
      e.layer.on('pm:edit', f => {
        this.updateGeometry(f.target)
      })
    })

updateGeometry = () => {
    if (this.editableLayers.getLayers().length === 0) {
      this.setState({areaOfInterest: null})
    } else {
      this.setState({areaOfInterest:this.editableLayers.toGeoJSON().features[0].geometry})
    }
  }

  updateLayers = (layer, isDelete = false) => {
    if (isDelete) {
      this.editableLayers.removeLayer(layer)
    } else {
      this.editableLayers.addLayer(layer)
    }
    this.updateGeometry()
  }
```
