### ISSUE TITLE
If a polygon is dragged such that the cursor leaves the map container, map is no longer scrollable

### ISSUE THREAD

**Issue by adamtLICOR** [codeofsumit/leaflet.pm#202]
1. Create a Polygon

![screen shot 2017-08-25 at 3 37 38 pm](https://user-images.githubusercontent.com/16004285/29731771-6221af7c-89ab-11e7-8784-b026acd18769.png)

2. Drag the Polygon such the the cursor leaves the map container.

![screen shot 2017-08-25 at 3 37 44 pm](https://user-images.githubusercontent.com/16004285/29731785-6cf81f4e-89ab-11e7-971c-5f63c892a881.png)

3. Click back into the map container, and find the Polygon still in the middle of a drag event.

4. After placing the polygon by clicking, the map is no longer draggable.

I believe this is caused by **_dragMixinOnMouseMove()** in *Drag.js*, which temporarily stores the state of the map's draggable status on mouse down. 

**_dragMixinOnMouseUp()** restores the map's dragging status, but isn't called if the mouse up event occurs outside the map container.

Thus, when you click back into the map container in **Step 2**, the temporary variable storing the map's draggable status is set to false (as the map isn't draggable at that moment).

I was able to fix it by moving 

> this._originalMapDragState = this._layer._map.dragging._enabled;

to **_initDraggableLayer()**, but I understand if that's not satisfactory (as it fails to take into account the user dynamically toggling the map's draggable status)

**Comment by codeofsumit** [comment]
Hey, thanks for the PR - will check it this week! Sorry for the late reply I was on vacation.
