### ISSUE TITLE
pm:remove fired when markers not related to PM removed

### ISSUE THREAD

**Issue by ivanjaros** [codeofsumit/leaflet.pm#204]
I just spen quite some time figuring out why my app started to behave so weirdly and I've finally found that the pm:remove event is fired when markers not related to PM code are removed fomr the map.

**Comment by codeofsumit** [comment]
Can you provide a JSfiddle with a repro please?

**Comment by ivanjaros** [comment]
I "fixed" it by checking if there is 'icon' in the event.layer.options. dirty af but does the job.

**Comment by codeofsumit** [comment]
@ivanjaros again: please provide a basic JSFiddle so we can take a look at the problem and fix it.

**Comment by codeofsumit** [comment]
Please reopen if the issue persists and you can provide a reproduction.
