### ISSUE TITLE
Unfocus button

### ISSUE THREAD

**Issue by ivanjaros** [codeofsumit/leaflet.pm#215]
Hi,
I would like to unfocus button(for example circle or polygon) if user moves cursor out of the map without drawing anything. What is the recommended way to do this?

**Comment by codeofsumit** [comment]
mouseleave on your container div and then disable all buttons via the leaflet.pm API.

you can get all toolbar buttons with `map.pm.Toolbar.getButtons();`.
you can get a buttons state with `button.toggled() // returns true or false`.
you can trigger a click on a button with `button._triggerClick()`.

Something like this
```
const disableAllButtons() {
  const buttons = map.pm.Toolbar.getButtons();

  for (const name in buttons) {
    if(buttons[name].toggled()) {
        buttons[name]._triggerClick();
    }
  }
}

mapContainer.on('mouseleave', disableAllButtons);
```

**Comment by codeofsumit** [comment]
reopen if you still have an issue here
