### ISSUE TITLE
How do I recreate layer from geojson?

### ISSUE THREAD

**Issue by ivanjaros** [codeofsumit/leaflet.pm#216]
I have the geojson data saved from layer that user has drawn and I want to re-create it.
I was able to create the layer properly but the style is missing(ie. layer is there but is invisible).
What is the proper way to create the layer with the PM styling?

```
            let layer;
            let style = new L.PM.Draw().options.templineStyle; // not good
            switch (foo.shape) {
              case 'Circle': layer = L.circle(foo.geo.geometry.coordinates, { ...style, radius: area.radius}); break;
              case 'Polygon': layer = L.polygon(foo.geo.geometry.coordinates, style); break;
              default: L.geoJson(foo.geo, style); break;
            }
            layer.addTo(bar);
```

**Comment by codeofsumit** [comment]
you should do it the other way around. Don't try to put leaflet.pm's style on other layers in your app.
Give leaflet.pm or the created layers in the pm:create callback your own style. And then use it accross your application.
