### ISSUE TITLE
Enable snapping only for closing the polygon

### ISSUE THREAD

**Issue by ivanjaros** [codeofsumit/leaflet.pm#217]
Hi,
I have some markers on the map and when I'm in drawing mode the snapping to these markers is undesired. How do I configure PM to snap only to the opening point when I'm closing the polygon?

**Comment by codeofsumit** [comment]
press ALT while drawing to disable snapping temporarily

**Comment by ivanjaros** [comment]
That's really not a solution.

**Comment by codeofsumit** [comment]
what solution do you prefer? Selective snapping (only for specific vertexes) is not supported right now.
Before even thinking about adding that, I need to support options for the Toolbar so you can pass e.g. `snappable: false`.
