### ISSUE TITLE
Is it possible to get access to the layer while it is being drawn?

### ISSUE THREAD

**Issue by richorama** [codeofsumit/leaflet.pm#218]
In my particular use case I would like to limit the number of vertexes in a polyline. `pm:create` gives me the polygon, but after the drawing has finished. Ideally I'd like it on `pm.drawstart`.

**Comment by codeofsumit** [comment]
hey @richorama - doesn't the `pm:drawstart` event give you the layer? Under `e.target` or something? Can't test right now.
If you want - give a little JSFiddle and we collaborate for a solution. If we need some more events in leaflet.pm to achieve that I'll have a look to implement them. But let's start with the fiddle - maybe there is a solution already.

**Comment by richorama** [comment]
@codeofsumit  thanks for the quick response!

I think target is the map:

`pm:drawstart` gives me an object with 3 properties:

```
{
  shape:"Line",
  target:  // the map,
  type:"pm:drawstart"
}
```

`pm:created` gives me an an extra property (`layer`) which is the polyline:

```
{
  layer:  // the polyline
  shape:"Line",
  target:  // the map,
  type:"pm:drawstart"
}
```

I'll take a look at jsFiddle in a minute..

**Comment by richorama** [comment]
jsFiddle: https://jsfiddle.net/cetv4pgs/2/

You'll need to open the console.

I'd be happy to create a PR for this..

**Comment by codeofsumit** [comment]
ah! Thanks for the Fiddle.
Would it be enough for you if the layer was passed inside `pm:drawstart`? I'd love a PR for this - should be an easy one.

Another `https://github.com/codeofsumit/leaflet.pm/pull/219` focuses on giving events per created vertex, which will help your usecase too I think?

**Comment by richorama** [comment]
I think passing a layer property through on `pm:drawstart` would be perfect. 

One thing I did notice is that internally a temporary layer is created for drawing, and then a new layer is created for `pm:create` event. So I was going to suggest passing the temporary layer on `pm:drawstart`, but perhaps give it a different property name (like `editLayer`) to make it obvious that it's not the final layer to be added to the map.

What are your thoughts?

Yes, the other PR will be useful - good point!

**Comment by codeofsumit** [comment]
@richorama very good point - yes, we use a temporary layer to draw. Pass that one and let's name it... 🤔  ... `workingLayer`.
The documentation in the `README.md` should include a short sentence why this is named working layer and that's it's not the actually returned layer during `pm:create`.

**Comment by richorama** [comment]
ok, thanks, stand by for a PR later today :¬)

**Comment by codeofsumit** [comment]
fixed by your PR :-)
