### ISSUE TITLE
Problem to build with grunt concat on Windows

### ISSUE THREAD

**Issue by rendrom** [codeofsumit/leaflet.pm#222]
I have a part of grunt config like this:
```
 "concat": {
            app: {
                options: {
                    sourceMap: true
                },
                files: [
                    {
                        src: [
                            "<%= nm %>/leaflet.pm/dist/leaflet.pm.css"
                        ],
                        dest: "<%= distc %>/css/app.css"
                    }
                ]
            }
}
```
And this error on build

`Warning: Unable to read "C:\Users\rendr\gisw\torus-map\torus-map\node_modules\leaflet.pm\dist\leaflet.pm.css.map*" file`

But after the `*` symbol delete from leaflet.pm.css

103: `/*# sourceMappingURL=leaflet.pm.css.map/`

The build is normal

**Comment by codeofsumit** [comment]
so you're trying to include the sourcemap for leaflet.pm? I don't think this works that easily - why do you need that?

**Comment by rendrom** [comment]
grunt.concat tries to include it himself, i think. Then see /*# sourceMappingURL=leaflet.pm.css.map*/ in leaflet.pm.css

**Comment by codeofsumit** [comment]
ah ok I understand. Will try to disable sourcemaps for the production build.
