### ISSUE TITLE
Fire event for line/polygon marker vertices on create/select

### ISSUE THREAD

**Issue by newmanw** [codeofsumit/leaflet.pm#224]
Add an event to DRAWN and EDIT when a vertex is created or selected.

Discussion here: https://github.com/codeofsumit/leaflet.pm/pull/219

**Comment by codeofsumit** [comment]
will do

**Comment by codeofsumit** [comment]
@newmanw do you mind trying out this PR?
https://github.com/codeofsumit/leaflet.pm/pull/227

Does it work for you? Check it's README.md for the documentation on how to use it

**Comment by newmanw** [comment]
@codeofsumit at a quick glance I think that will work.  To grab the click or mouse up event would look something like this:

```
map.on('pm:drawstart', function(e) {
    var layer = e.workingLayer;
    layer.on('pm:vertexadded', function(e) {
        e.marker.on('click', function(clickEvent) {
            // handle vertex click 
        }):
    });
});
```

**Comment by codeofsumit** [comment]
@newmanw yes if you want to do something when a marker is clicked - sure!

**Comment by newmanw** [comment]
@codeofsumit 'click' was the initial question here: https://github.com/codeofsumit/leaflet.pm/pull/219

This works great for getting the vertex markers when creating them, but how would I go about getting all the vertex markers when an edit starts?  Again I am trying to listen for click on the vertex markers as I would like to show the lat/lng of the marker that was clicked.

Would it be easier to add some more specific vertex marker events like pm:vertexclicked? IE the drag event are really just vertex events.

https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Edit/L.PM.Edit.Line.js#L403-L412

IMHO from the client side this is much easier to deal with.

**Comment by Dan-Wood** [comment]
@codeofsumit I know this is pretty old, but I can't find anything to indicate the functionality was made or not?

We have a log scale for Altitude/Depth on each vertex, this works perfect when creating a line with vertex's, however I'm having trouble getting an onclick event happening on the vertex's when in edit mode.

This is pretty much the exact same issue as @newmanw has described.

You can't bind an onclick event to the vertex markergroup as you [clear it on disable()
](https://github.com/geoman-io/leaflet-geoman/blob/259eecc56f340ff3d99641786b00da01c4bbbbef/src/js/Edit/L.PM.Edit.Line.js#L91) and [here on init()](https://github.com/geoman-io/leaflet-geoman/blob/259eecc56f340ff3d99641786b00da01c4bbbbef/src/js/Edit/L.PM.Edit.Line.js#L182)

You could set the pm:vertexClick event when you create the new markers.
