### ISSUE TITLE
Vertex marker events no longer include an index

### ISSUE THREAD

**Issue by newmanw** [codeofsumit/leaflet.pm#225]
Vertex marker events used to include an _index property, giving an index into the coordinates array.  I completely understand that this was intended to be a private variable.  However now when listening to those events (ie pm:markerdragend) there is no way to tell which vertex was modified.

Looking deeper it looks like the leaflet id is used to find the markers position in the array.  Since the vertex markers are not available to the client the client cannot employ the same logic.

Would it be possible to attach this information to the event?

**Comment by codeofsumit** [comment]
@newmanw I'll find a way to include it. I'd also have to give a `ringIndex` now because of the hole support in polygons though.

**Comment by codeofsumit** [comment]
@newmanw you were talking about the `pm:markerdragstart` event right?
