### ISSUE TITLE
size is TEN TIMES BIGGER since including turf

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/leaflet.pm#228]
turf is the dependency to calculate the necessary things to support the Cutting feature.
Turf thinks about replacing it's big dependency that's causing this size: https://github.com/Turfjs/turf/issues/88

![image](https://user-images.githubusercontent.com/2399810/31335760-3e313e54-acf4-11e7-9407-91e7c92cdf13.png)

Another option would be to replace turf with martinez. Martinez still has some problems though and I wasn't able to make holes work with it due to this: https://github.com/w8r/martinez/issues/44

Afaik, turf thinks about replacing their big dependency `jsts` with martinez too which would be my favorite option.

Let's see 🤞

**Comment by DenisCarriere** [comment]
👍 💯 support this, feel free to send PR's to both libraries, TurfJS is also looking forward to implement `martinez`.

Also we're in the process of converting to ES6 modules to enable bundlers like Rollup to be more efficient (🤞 coming soon... https://github.com/Turfjs/turf/pull/960)

**Comment by codeofsumit** [comment]
@ivanjaros asked if we could exclude turf if the cutting feature is not used.

Here is what I'm currently thinking about:

1. Split leaflet.pm into modules to allow separate import of features to reduce file size
2. wait for turf to replace jsts
3. replace turf (I did not find a suitable replacement yet)

I'm in favor of 2. or 3. and I'll start searching for a replacement again this week as turf moved the `remove jsts` milestone behind the next major version release (5.0).

In apps where I use `leaflet.pm` myself I started lazy loading it. I mostly use Webpack and React / Vue. If there is a Map component of some sort, it's VERY easy to lazy load it so leaflet and leaflet.pm are not in the initial bundle to be downloaded.

**Comment by codeofsumit** [comment]
Maybe the recent merge of https://github.com/Turfjs/turf/pull/960 helps here with it's released in Turf 5.0?
Turf 5.x seems to be released on Github
https://github.com/Turfjs/turf/releases

But not on npm?
Will investigate and if the turf update brings an improvement to our filesize I'll release asap!

**Comment by DenisCarriere** [comment]
@codeofsumit Still a few more things that need to be done before we release Turf 5.0 on npm. At the moment there's a few modules that are published for testing purposes.

**Comment by DenisCarriere** [comment]
Almost there... posted a comment which might solve the issue very soon.

https://github.com/codeofsumit/leaflet.pm/pull/255#issuecomment-346936341

🤞

**Comment by smeijer** [comment]
This is the only thing I don't like about migrating from `leaflet-draw` to `leaflet.pm`.

```
leaflet-draw:   67.56 kB      https://unpkg.com/leaflet-draw@1.0.2/dist/
leaflet.pm:    421.64 kB      https://unpkg.com/leaflet.pm@0.24.0/dist/
```

**Comment by codeofsumit** [comment]
@smeijer Turf already brought down `intersect`.
Now it's only `@turf/difference` that has no 6.x version on npm that is still big. If we can replace or update that, this library will go down to 80kb.

![image](https://user-images.githubusercontent.com/2399810/39470298-1c6e270c-4d3d-11e8-8004-a701868d2363.png)

@DenisCarriere is there a specific reason that difference has no 6.x version on npm?

**Comment by smeijer** [comment]
According to NPM, `@turf/difference` received an update to `6.x`.

https://www.npmjs.com/package/@turf/difference/v/6.0.1

I hope this also triggers the review of some PR's, and continued development of this awesome `leaflet.draw` alternative.

**Comment by DenisCarriere** [comment]
@smeijer @codeofsumit `@turf/difference` is updated to `6.x` and doesn't contain any large dependencies.

Maybe make sure you refresh your `yarn.lock` or any dependencies that might still have an older version of it.

https://unpkg.com/@turf/difference@6.0.1/

**Comment by DenisCarriere** [comment]
Fixed via PR https://github.com/codeofsumit/leaflet.pm/pull/300
