### ISSUE TITLE
Update circle position when drag circle center 

### ISSUE THREAD

**Issue by mkondur** [codeofsumit/leaflet.pm#230]
When you drag circle center marker, the circle doesn't update its position

![circle_bug](https://user-images.githubusercontent.com/7535008/30909819-b941dea8-a382-11e7-88b8-0f010808bb13.gif)

**Comment by codeofsumit** [comment]
@mkondur oh wow.
Works fine for me on the demo page: leafletpm.now.sh.
Can you give me a link where it's not working for you?
If it's the demo page, I'd need browser info.
What would also help is:
open dev tools for that browser and check if there are JS errors - if yes, please screenshot them in here.
Also type `L.PM.version` into the console and check that it's the latest release: `0.20.0`

**Comment by mkondur** [comment]
@codeofsumit it's not working for me. Tested on Chrome 61.0.3163.100, Firefox 55.0.3 and Safari 11.0.
I tested it on demo page: leafletpm.now.sh where L.PM.version is 0.20.0 and also in my project where L.PM.version is 0.17.3 and there is the same effect when I click on circle center marker and drag it to another position and circle stays at the old position. There are no JS errors

**Comment by codeofsumit** [comment]
@mkondur hmmm very weird. I just went to my coworkers, Linux, Windows 7 and Mac and tried it in Firefox, Chrome and Safari. It's all working 🤔 .

Any ideas what else we could try?

**Comment by mkondur** [comment]
I'm working on Mac.

Step by step what I'm doing:
1. Choose to draw a circle
2. Click on map to start drawing
3. When circle center marker appear I click on it and drag to another position and then move mouse to draw circle.

Solution:
Disable to drag center marker when draw a circle or update circle position when drag this marker

**Comment by codeofsumit** [comment]
ha! Thanks, now I was able to reproduce!
Will fix it - the marker shouldn't be draggable during draw - it's for editing only.
