### ISSUE TITLE
Calling `enable()` does not set the draw button to active

### ISSUE THREAD

**Issue by richorama** [codeofsumit/leaflet.pm#231]
When in edit mode, if you call:

```js
map.pm.Draw.Poly.disable();
```

...for example, is will update the draw button accordingly.

But when you call:

```js
map.pm.Draw.Poly.enable();
```

... the map enters draw mode, but the button is not updated.

fiddle: https://jsfiddle.net/qo5kwfww/1/

**Comment by codeofsumit** [comment]
thanks for the fiddle.

`Draw.Poly` is for polygon. But the button you have in the Toolbar is for polyline. I can see that this might be confusing.
Here's the fiddle working correctly :-)
https://jsfiddle.net/qo5kwfww/2/
