### ISSUE TITLE
FR: upload geometry button

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#234]
Would any one be interested in a upload geometry button? for example uploading KML or CSV file and apply geometry on the map? perhaps I can start this feature once I get some time.

**Comment by codeofsumit** [comment]
@themre thought about this too but IMO this is a different plugin or application logic. Same with "export". It'd add a LOT of logic that has nothing to do with drawing, including
* validation
* file handling
* format transformations
etc...

it's especially hard as each application probably has different validations, properties and requirements for their geodata.
I've built this kinda stuff a couple of times now and IMO this is out of scope for this plugin.

I'll close the issue but if you want to continue the discussion, let's do it here :-)

**Comment by themre** [comment]
yes, you're probably right. it would be probably best to build some separate plugin which we could add inside PM toolbar.
