### ISSUE TITLE
CDN min.js error

### ISSUE THREAD

**Issue by gunturbudi** [codeofsumit/leaflet.pm#236]
When I include the js into the source code, it produces this error:

> Uncaught SyntaxError: missing ) after argument list.

Then i look at the end of the source code, it seems not complete.

Thanks

**Comment by codeofsumit** [comment]
hey @gunturbudi.
The CDN from the README.md works fine in my testing: `https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.min.js`.

Are you using that CDN? If yes, please provide a JSFiddle that shows the error / provide a CDN Link where script is not complete.

**Comment by codeofsumit** [comment]
please reopen with a JSFiddle
