### ISSUE TITLE
Get list of vertexes coordinates

### ISSUE THREAD

**Issue by JacobusS** [codeofsumit/leaflet.pm#237]
Hi, I'm quite new to Leaflet and Javascript so please excuse my ignorance. First of, this is truly amazing, it looks so good and work great.
I want to get a list of coordinates all the vertexes of a polygon once drawn also just a side note, what is the layer name or are all the features placed in a group layer? thanks.

**Comment by codeofsumit** [comment]
hey there

from the documentation:
```js
// listen to when a new layer is created
map.on('pm:create', function(e) {
    e.shape; // the name of the shape being drawn (i.e. 'Circle')
    e.layer; // the leaflet layer created
});
```

`e.layer` is a regular leaflet layer and you can get all information there via the usual leaflet functions: http://leafletjs.com/reference-1.2.0.html#polyline-getlatlngs

**Comment by JacobusS** [comment]
That is fantastic, thanks so much.
