### ISSUE TITLE
NPM size

### ISSUE THREAD

**Issue by ivanjaros** [codeofsumit/leaflet.pm#238]
I was baffled by the size of my compiled JS project.
With little debugging I found that the leaflet.pm npm package is a massive **0.5MB minified** and it does not even include the leaflet library. So I wonder why is it so huge and can it be slimmed down?

**Comment by codeofsumit** [comment]
yes :-( - see this issue: https://github.com/codeofsumit/leaflet.pm/issues/228

**Comment by ivanjaros** [comment]
Thanks. Since I do not use cutting, is there a way to exclude that library?

**Comment by codeofsumit** [comment]
mhh not right now - let's move this convo to #288 - I just commented there what's in my mind. Please share your thoughts too!
