### ISSUE TITLE
New feature: prevent polygon self-intersection while editing

### ISSUE THREAD

**Issue by ashmigelski** [codeofsumit/leaflet.pm#239]
Hey

In our project we deal with simple polygons (shape consisting of straight, non-intersecting line segments)
and using Leaflet.Draw mostly because of `allowIntersection` feature.
You can see it in action on examples page https://leaflet.github.io/Leaflet.draw/docs/examples/full.html
1. Create a poly
2. Toggle edit mode
3. Drag a vertex to cross any segment - vertex will be deleted 

I want to migrate to leaflet.pm but without same feature it's absolutely impossible. Is there any chance to add such functionality or any workaround how to implement it using events?

Thanks for answer and amazing job!

**Comment by codeofsumit** [comment]
hey @ashmigelski. Cool feature! Yes, I can implement this.
Whoever I'll need a week or two I think.

Until then, you could to this yourself. If you check the readme there are lots of events that you can listen to to implement this on the app-side. But if you can wait a bit, you don't have to code it yourself 👍

**Comment by codeofsumit** [comment]
started it.
![intersect](https://user-images.githubusercontent.com/2399810/31385376-5541be32-adc3-11e7-9588-285422ffc5e1.gif)

**Comment by codeofsumit** [comment]
Style change is also there:
![intersect](https://user-images.githubusercontent.com/2399810/31386752-3be99b08-adc8-11e7-9824-6737f8d40bc4.gif)
![intersectpoly](https://user-images.githubusercontent.com/2399810/31386753-3c3c6b8a-adc8-11e7-868c-2921c339b500.gif)

**Comment by ashmigelski** [comment]
Looks good! Thanks for such fast reaction :+1: Cant wait to see edit mode :)
Please give me to know if I can help with code or testing

**Comment by codeofsumit** [comment]
this is how it looks in edit mode

![demo](https://user-images.githubusercontent.com/2399810/31426339-3aa1b7b2-ae63-11e7-87b8-e305687ab1f2.gif)

I'm currently trying to figure out how to "reset" the polygon if the user edits the polygon and causes a self-intersection. Because leaflet.pm has immediate changes, there is no "undo" right now 🤔

**Comment by codeofsumit** [comment]
nevermind, got it 👍 

![demo](https://user-images.githubusercontent.com/2399810/31426677-9617f1fa-ae64-11e7-98e6-adc54821c8cc.gif)

**Comment by ashmigelski** [comment]
That's it!
What about situation when we load invalid polygon and then start editing? Method `isValid()` can be useful to check either polygon can be saved

**Comment by codeofsumit** [comment]
ah yes! Thanks for that usecase. 
Here is how it's handled - bear with me on that one.

Let's say you allow self intersection during draw.
But then, on the `pm:create` event, you enable editing but set `allowSelfIntersection` to false:
```
map.on('pm:create', function(e) {
    e.layer.pm.enable({ allowSelfIntersection: false });
    console.log(e.layer.pm.selfIntersection());
});
```

this is exactly your usecase? Editing starts with a self intersection but you disallow self intersection for editing.
Upon `enable`, the self intersection option gets checked and the layer becomes red immediately.
As there is no previous state, I can't reset it of course.

The function `layer.pm.selfIntersection()` returns `true` or `false` so you can trigger other actions in your app.

Does that cover this usecase for you? Can you work with this?

**Comment by ashmigelski** [comment]
Yeap it's ok
I'll try to test feature branch and give your more info
Thanks again!

**Comment by codeofsumit** [comment]
@ashmigelski I committed everything. Would be great if you could test #241 and let me know how it goes.

**Comment by ashmigelski** [comment]
Just check #241, still looks good)

Found another use case: delete vertex that change polygon state
* delete vertex that add self-intersection
![case_1](https://user-images.githubusercontent.com/4904519/31431780-5443d58c-ae7d-11e7-996a-fce1aca63321.png)
* delete vertex that remove self-intersection
![case_2](https://user-images.githubusercontent.com/4904519/31432152-7b310c86-ae7e-11e7-9d21-d7db1458e6e4.png)

Also interested in styling so that 'red' color in code is not good https://github.com/codeofsumit/leaflet.pm/pull/241/files#diff-a53f0deadd9500d627e1c8db2d8d79e8R186  
I can do PR with styling after merge #241

**Comment by codeofsumit** [comment]
@ashmigelski both should be taken care of. Can you check the latest branch state?

**Comment by codeofsumit** [comment]
@ashmigelski Ok both cases should be handled now. Do you mind checking again?

**Comment by ashmigelski** [comment]
Everything works fine for me (both cases and styling via css)
For now can't find any issues.. Time to merge ;)

**Comment by codeofsumit** [comment]
@ashmigelski no I'd like to handle holes in this PR too and I'm looking at it currently. Good to hear everything works so far 👍  - thanks for testing

**Comment by codeofsumit** [comment]
okay holes seem to be handled too
![holes_intersect](https://user-images.githubusercontent.com/2399810/31499910-5e0a062e-af66-11e7-8b33-5023d6beb8cd.gif)

**Comment by ashmigelski** [comment]
Wow! I'll try to test holes today or tommorow

**Comment by codeofsumit** [comment]
I just added a `pm:intersect` event:

```
// if allowSelfIntersection is false: listen to when a self-intersection is detected
// e.intersection includes a geoJSON of the intersection
polygonLayer.on('pm:intersect', function(e) {//...});
```

Helpful for marking the intersection if you wish.

**Comment by ashmigelski** [comment]
Ok, holes works!
Found unexpected behavior when holes are nested
![not_work](https://user-images.githubusercontent.com/4904519/31539576-a7d82f8c-b011-11e7-8b9e-2d695297ea60.png)
Also have a question: when I have a polygon with 3 point deleting one of them convert polygon into polyline and looks quite strange. Is it possible to set min vertices =  3 for polygon?

**Comment by codeofsumit** [comment]
it's out:
https://github.com/codeofsumit/leaflet.pm/releases/tag/v0.22.0
