### ISSUE TITLE
Unexpected behavior with React

### ISSUE THREAD

**Issue by sairus2k** [codeofsumit/leaflet.pm#242]
Something broke when creating line or polygon. Without console errors.

[jsfiddle example](https://jsfiddle.net/2wary6a5/)

How to reproduce:

1. Create line or polygon.
2. Enable edit mode.
3. Zoom in or zoom out - tile layer not zooming.

Versions:
React 16.0.0
Leaflet 1.2.0
leaflet.pm 0.21.0

Not reproduce on the leaflet.pm version 0.19.0.

**Comment by codeofsumit** [comment]
thanks for reporting and the JSfiddle. Will fix asap and hopefully release this weekend or sooner!

**Comment by codeofsumit** [comment]
was caused by the same problem that another bug had. Will release the fix this week!
