### ISSUE TITLE
Leaflet.PM not working on Chrome for Android

### ISSUE THREAD

**Issue by opoto** [codeofsumit/leaflet.pm#243]
Hi

I noticed Leaflet.PM does not work on Chrome (61) for Android (7) (at least the demo).

To reproduce:
- Open https://leafletpm.now.sh/#/ in Chrome on an Android device
- Click/select any editing tool (line, marker...)
- Click on map: nothing is drawn

Actually I noticed similar issue with Leaflet.Editable, might be an issue with Leaflet event management.
Any idea on how to fix or workaround this problem?

Thanks

**Comment by codeofsumit** [comment]
hmm 🤔   - it works fine for me.
![demo](https://user-images.githubusercontent.com/2399810/31426036-fb8160c4-ae61-11e7-9d05-c7b9505ccb51.gif)

Are there any JS errors in the console for you?

**Comment by codeofsumit** [comment]
ah sorry, Android. Hmm I don't have an Android Device but I just tried it on a Nexus 5 emulator (Chrome Dev Tools) and it worked too.

Are you able to debug on your Device? E.g. DevTools? JS errors would be good to see

**Comment by opoto** [comment]
Hello
There is nothing displayed in the console, it stays blank.
As the code is obfuscated I do not know how to investigate further.

**Comment by themre** [comment]
It works on my android,chrome,only dragging isn't handled.

**Comment by codeofsumit** [comment]
Works fine on iPhone - including dragging 🤔 🤔 .
Can you guys reproduce a test case with the Chrome DevTools emulator and leafletpm.now.sh?

**Comment by opoto** [comment]
After extra tests, I managed to draw on Chrome Android, but I have to do VERY quick taps, usual taps being considered as map dragging instead of map clicks. Is there some timer to configure to be more permissive on the tap duration?

**Comment by codeofsumit** [comment]
mhh not in leaflet.pm and nothing that I know of in leaflet.
These are the leaflet events on a map:
http://leafletjs.com/reference-1.2.0.html#map-click

They don't have dedicated mobile events afaik 🤔

**Comment by opoto** [comment]
Ok, I agree this issue is not clear enough, I let you close it if you want.
