### ISSUE TITLE
 path of the drawn polygon

### ISSUE THREAD

**Issue by avrezvanov** [codeofsumit/leaflet.pm#244]
Hello! Great component!
I can not understand how to get the path of the drawn polygon? Is this possible?
Thank you

**Comment by codeofsumit** [comment]
hey there. Thanks! Glad you like it.

You can listen to the `pm:create` event.

This will work:
```
// listen to when a new layer is created
map.on('pm:create', function(e) {
    e.shape; // the name of the shape being drawn (i.e. 'Circle')
    e.layer; // the leaflet layer created
});
```

Then, you can use the same techniques to get your information on the leaflet layer just as you're used to :-)

This is the relevant section in the README:
https://github.com/codeofsumit/leaflet.pm#drawing-mode

reopen the issue if something is not working/clear
