### ISSUE TITLE
no events after dragging rectangle marker

### ISSUE THREAD

**Issue by chplog** [codeofsumit/leaflet.pm#245]
There seems to be an issue eventing after editing rectangles. I'd like to call a function after a rectangle has changed. It works only with the dragend-event. The markerdragend-Event doesn't work. It seems, that it is simply not fired...

**Comment by codeofsumit** [comment]
hey @chplog - can you provide a JSFiddle that shows the problem? I'll have a busy weekend bug if you can prodie a JSFiddle in the next days I can check and fix it next week 👍

**Comment by chplog** [comment]
Unfortunatley I wasn't able to get JSFiddle to work with leaflet and pm, but nevertheless I created a small test application. map.pm is undifined. Seems to me, that JSFiddle does not initialize PM.
When a Geometry is created, it is bound to several events to watch the update process. Have a closer look at the conosle messages when you update a polygon, a rectangle and a circle.  There are no events, when it comes to marker dragging on rectangles and circles.

https://jsfiddle.net/chplog/msL0r13v/79/

**Comment by themre** [comment]
perhaps you can try this example and modify it: http://jsfiddle.net/LnzN2/1103/

**Comment by codeofsumit** [comment]
@themre @chplog I added a JSfiddle template to the Issue Template 👍 
http://jsfiddle.net/LnzN2/1332/

**Comment by chplog** [comment]
Great. Thank you both! (however, my jsfiddle looked pretty much the same to me... mysterious...)

http://jsfiddle.net/chplog/rc7rtw1q/6/

I'm missing dragend events, after resizing a rectangle or a circle.
