### ISSUE TITLE
Execute a function on toggle of edit mode.

### ISSUE THREAD

**Issue by melz007** [codeofsumit/leaflet.pm#246]
Hi.

First of all thank you for this awesome plugin.

I am saving the geometry of all the shapes after editing them. For now I am using the "pm:edit" function and it is working fine but i wanted to know if I could fire a function on the toggle of the edit mode button on the map so that I could save all of the shapes at once.

Thanks.

**Comment by codeofsumit** [comment]
hey @melz007, mhh not yet - will implement asap!

**Comment by melz007** [comment]
Thanks
