### ISSUE TITLE
Disable Removal mode

### ISSUE THREAD

**Issue by blacktopol** [codeofsumit/leaflet.pm#247]
Does leaflet.pm have any way of disabling Removal mode programmatically? 
map.pm.toggleGlobalRemovalMode() allows it but I can't define does Removal mode active now.
Does leaflet.pm have something like disableGlobalRemovalMode() or method for checking Removal Mode state?

**Comment by codeofsumit** [comment]
yes, 

```js
map.pm.globalRemovalEnabled();
```
returns `true` when global removal mode is enabled. It currently returns `undefined` or `false` when not. The next release will fix this and it always returns `false` when disabled. But you can check against `true` now already.
