### ISSUE TITLE
Add unique id to layer on add (to identify which was edited/removed)

### ISSUE THREAD

**Issue by ChaudhryAtif** [codeofsumit/leaflet.pm#248]
Haven't looked too much into the code and all, but I'm hoping there's a way.

I have a list of circles which include pre-loaded and newly added circles. Is there a way to add an identifier to the layer so when removing/editing the layer(s), I can appropriately remove it from my list and perform any additional logic, such as making an API call.

![image](https://user-images.githubusercontent.com/7082580/32706134-9065b414-c7e0-11e7-9148-a79ec3d600fa.png)

Since this library takes a lot from leaflet.draw, here's a base demo in it to go off of for now:
[jsFiddle](https://jsfiddle.net/obsjzrwy/)

I can try and replicate the demo in leaflet.pm. Probably in a couple days.

**Comment by codeofsumit** [comment]
You can add whatever you want to any layer. It is a regular leaflet layer and adding necessary properties for your own logic is something you can do.

You can do `layer.myId = 'lalala'` or you use the leaflet ID that is generated by leaflet for each layer `layer._leaflet_id`.

**Comment by ChaudhryAtif** [comment]
Thanks Sumit! That worked!

Here's a working demo (open console): [jsFiddle](https://jsfiddle.net/4gjwotgf/)
