### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lat' of null

### ISSUE THREAD

**Issue by galileopy** [codeofsumit/leaflet.pm#249]
I'm not sure if this error is due to leaflet.pm or is leaflet itself that has the bug, but certainly it didn't appear until I added leaflet.pm to my package.

The error appears when you add a polyline that has an array of arrays of [lat,lng], which leds me to believe it has something to do with the lack of support to MultiPolylines in leaflet.pm itself.

[Fiddle]( http://jsfiddle.net/t5s1yn3z/)

**Comment by galileopy** [comment]
this  might be related, not sure though, https://github.com/Leaflet/Leaflet/issues/3280

**Comment by galileopy** [comment]
leaflet.pm bug report, in case is weird edge case, https://github.com/codeofsumit/leaflet.pm/issues/249

**Comment by codeofsumit** [comment]
yes, looks like that's exactly the reason. I'll investigate further and maybe I can add MultiPoly support within the next two weeks if there is demand now

**Comment by perliedman** [comment]
👋 Hi everyone,

just to add to this, while checking https://github.com/Leaflet/Leaflet/issues/3280, it looked like at least the first problem is https://github.com/codeofsumit/leaflet.pm/blob/47336a37fa4d36a0a3137292b6b074c97321f0c8/src/js/Edit/L.PM.Edit.Line.js#L194, which assumes that things that are not polygons (which I assume are polylines) are not nested arrays, so it will assume each entry is a `LatLng`, which isn't true for MultLine.

If it makes you feel better, I actually discovered just now that Leaflet's `Polyline` actually support MultiPolyline as well...

**Comment by codeofsumit** [comment]
thanks @perliedman. Yes I think with the support of holes, the groundwork for MultiPolylines and MultiPolygons is already in leaflet.pm. I specifically excluded them but apparently with some errors.
I'll sort it out 👍

**Comment by codeofsumit** [comment]
just to give an update to this: obviously I wasn't able to make it work within 2 weeks. I'll get on it asap. I'm on a business trip right now and hope to get some time for this next week.

**Comment by maleta** [comment]
I had this error when updating marker location with method `setLatLng` and my workaround for this was to remove existing marker and create new.

**Comment by seanbeaton** [comment]
@codeofsumit, did you have any luck with this?

**Comment by seanbeaton** [comment]
Just an update with the issue I was having - turns out the multipoly lines weren't the issue. A few of the lat long pairs I was passing to leaflet were [null, null], causing everything to break and that error to be printed to the console. 

To anyone else having this issue, it might be worth verifying any and all lat/long coordinates being used by leaflet are valid.

**Comment by mpschaeuble** [comment]
@codeofsumit Any progress on this issue?

**Comment by ewkonzo** [comment]
@mpschaeuble The commit really helped thanks.... But since someone don't want to merge it to main.... You did suggest multipolygons can also be handled as a LayerGroup of polygons, is this current supported? if so how can it be archived?

**Comment by mpschaeuble** [comment]
@ewkonzo Nice to hear that my patch helped someone else. No, as far as I remember handling multipolygons as a LayerGroup of polygons would just have been a different solution/implementation approach I could imagine to get multipolygons supported in Leaflet.pm.

**Comment by ewkonzo** [comment]
@mpschaeuble thanks it did help me get through a presentation, all was good using your build. but somehow the error _Cannot read property 'lat' of null_ kept magically finding its way later while working with the layer... so I am now converting the multi-polygons to polygons in my geojson...  then back to multi-polygon when submitting them to the back-end this has caused lots of other unrelated problems...  I am still using your solution i am undecided on which approach is worse.

**Comment by codeofsumit** [comment]
Should be resolved now. MultiPolygon and MultiLineString Support was just released 👍
