### ISSUE TITLE
Add an hook for circle draw event for mousemove after seting center

### ISSUE THREAD

**Issue by ThomasG77** [codeofsumit/leaflet.pm#251]
I didn't found any event hook for getting mouse position coordinates after drawing the center.
I'm only aware of a drawstart and a drawend but I want to get an event while drawing in order to get center and use it for returning radius and display it in a tooltip. This would be quite similar to existing [Leaflet.draw](https://leaflet.github.io/Leaflet.draw/docs/examples/full.html) (see screenshot)
![selection_772](https://user-images.githubusercontent.com/642120/32984837-2cf1d354-ccae-11e7-8213-f4d8fbed045c.png)

IMO, the hook would be enough as it would not bloat the library: it would be the dev responsibility to care about distance calculation or tooltip.

I may miss the event. Otherwise, I've done a naive implementation for creation when moving only the radius (not done for edit level) in this branch https://github.com/ThomasG77/leaflet.pm/tree/hook-circle-move

To test it,
```
git clone https://github.com/ThomasG77/leaflet.pm.git
git checkout hook-circle-move
npm install
npm run build
```

Then open the modified existing demo, open the console and try to draw a circle on the first map `map2`

What is your opinion about this feature request? My naive implementation?

**Comment by codeofsumit** [comment]
hey @ThomasG77, I have to check this out in detail. I hope I can get back to you on this during the weekend! 👍

**Comment by codeofsumit** [comment]
hey @ThomasG77, how does this sound for you?

```js
// listen to the center of a circle being added
map.on('pm:drawstart', function(e) {
  var circle = e.workingLayer;

  // this fires only for circles
  circle.on('pm:centerplaced', function(e) {
    console.log(e);
  });
});

// listen to when the center of a circle is moved
map.on('pm:create', function(e) {
  var circle = e.layer;

  // this fires only for circles
  circle.on('pm:centerplaced', function(e) {
    console.log(e);
  });
});
```

**Comment by ThomasG77** [comment]
From my understanding, your solution solves the issue for listening to center change, whereas what I want is listening when radius change. We would need to create another event with a signature like

```
circle.on('pm:radiuschanged', function(e) {
  console.log(e);
});
```
So what you implemented is overall useful but do not solve the issue.

**Comment by codeofsumit** [comment]
@ThomasG77 if you want both changes, isn't `pm:edit` sufficient?

**Comment by ThomasG77** [comment]
You are right: I really missed the point here.
Nothing is required on your side.

Thanks for your patience

**Comment by codeofsumit** [comment]
Awesome! Let me know if something else comes up 👍

**Comment by ThomasG77** [comment]
Sorry, I come back...
```
@ThomasG77 if you want both changes, isn't pm:edit sufficient?
```
Only if you edit the circle after creation. On first creation, I'm not able to listen to change.
My branch was solving this behavior (see below GIF in action for demonstration).

![peek 25-12-2017 20-14](https://user-images.githubusercontent.com/642120/34342456-d6498a9a-e9b0-11e7-8f7a-76f664364537.gif)

I want to confirm that I did not miss the point again before you may reopen.

**Comment by hamza-sabri5** [comment]
I am sorry but I read this page multiple times but it seems I am missing something but I don't know what!

I am creating a circle and I got its reference using the workingLayer from the event when start drawing, and I attached some event listeres with it like pm:snap, pm:unsnap, and pm:centerplaced.

But I cannot attach pm:edit with it, to be more accurate I attached it but it isn't notified when I start drawing the circle 
could someone help, please!

or is there a way to do directly without the need to calculate the radius every time something like "pm:radiuschanged"

**Comment by Falke-Design** [comment]
@hamza-sabri5 what exactly do you want to achive?

**Comment by hamza-sabri5** [comment]
@Falke-Design  thanks for your quick response.
what I am trying to achieve is, I want to know the value of the radius while drawing the circle itself something like the first image on this page.

I want to be able to show the user the current radius while he is still drawing

**Comment by hamza-sabri5** [comment]
@Falke-Design 
@ThomasG77 
@codeofsumit 

I found that if I did the following 
circle.on("pm:centerplaced",()=>{
    circle.on("pm:snapdrag",()=>{
        console.log(circle._mRadius);
    });
   });

I can then get notified every time the mouse moves after placing the center and then I can get the radius but is it the right way to do it? I mean it works but is it the best way?

**Comment by Falke-Design** [comment]
I recommand to use this:
```
const getCircleDrawRadius = ()=>{
  console.log(map.pm.Draw.Circle._layer.getRadius());
}

map.on('pm:drawstart',(e)=>{
  if(map.pm.Draw.Circle._hintMarker && e.shape === "Circle") {
    map.pm.Draw.Circle._hintMarker.on('move', getCircleDrawRadius);
  }
})
map.on('pm:drawend',(e)=>{
  if(map.pm.Draw.Circle._hintMarker) {
    map.pm.Draw.Circle._hintMarker.off('move', getCircleDrawRadius)
  }
})
```

**Comment by hamza-sabri5** [comment]
@Falke-Design 
Oh, didn't know that they have an event listener called "move".
thanks

**Comment by hamza-sabri5** [comment]
@Falke-Design 
I was wondering if you can help me with one more thing!
you see now I am having the radius and I am printing it out, but I want to show it as a tooltip when the user starts drawing like something move with the curser when he is moving just like the first picture

**Comment by hamza-sabri5** [comment]
that's really good, but now I want to display that radius to the user while he is drawing.
I know that the default tooltip is coming from 
"map.pm.Draw.Circle._hintMarker._tooltip._content" but how can I change it?
when making it equal a new value it just prints it but doesn't change it for the user

**Comment by Falke-Design** [comment]
Set the tooltip content with: `map.pm.Draw.Circle._hintMarker._tooltip.setContent("current radius is "+map.pm.Draw.Circle._layer.getRadius().toFixed(2));`

**Comment by hamza-sabri5** [comment]
@Falke-Design 
thank you thank you thank you thank you..., thank you so much.

a great lib by the way thank you for your help and your contribution with the lib.

**Comment by kapetanidis-nikos** [comment]
I have a similar issue. I draw a Rectangle and while I am drawing it I want to display in the tooltip the square meters the drawn area covers.

I am able to calculate the drawn area in sq meters and display it on the tooltip but the value shown seems to not re-render when it changes.

This is what I am trying to do, but as I said the tooltip doesn't seem to render when my state that holds the drawn area changes.
![screenshot-2025-01-14-17-14-27](https://github.com/user-attachments/assets/b6467326-d2ab-4bf1-90ef-65bab45a1c14)

Here is the code and as I can see in my logs the the component re-renders every time the mouse moves while drawing, but the value displayed in the tooltip doesn't.

```javascript  
useEffect(() => {
    if (clickPosition && cursorPosition) {
      const bounds = new LatLngBounds([clickPosition, cursorPosition]);
      const rectangleArea = calculateBboxAreaSqm(bounds);
      setDrawnArea(rectangleArea);

      console.log("Render");

      const customTooltipText = {
        tooltips: {
          finishRect: `Έκταση σε τμ: ${drawnArea.toFixed(2)}`,
        },
      };

      map.pm.setLang("en", customTooltipText, "en");
    }
  }, [clickPosition, cursorPosition, map]);```
