### ISSUE TITLE
When start draw rectangle, points are added on the map

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#252]
I tried demo page and when I click Draw rectangle, points are added here:
![image](https://user-images.githubusercontent.com/10845050/33071136-a7823d4e-ceba-11e7-9570-f48c870774e8.png)

**Comment by codeofsumit** [comment]
😂  haha what is that about. How did you even find this!
Will fix it asap 😅

**Comment by themre** [comment]
I started near that location and so I noticed that :) thanks for your fast
response!

21. nov. 2017 4:20 pop. je oseba "Sumit Kumar" <notifications@github.com>
napisala:
