### ISSUE TITLE
FR: move from webpack to rollup

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#254]
Leaflet just migrated to rollup and latest version 0.51 noticed large optimization of bundle (up to 60%). should we try rollup? probably also related to https://github.com/codeofsumit/leaflet.pm/issues/228

**Comment by themre** [comment]
WIP https://github.com/codeofsumit/leaflet.pm/pull/256

**Comment by codeofsumit** [comment]
as mentioned in #256 I think bundle size of dependencies should be optimized upstream. I'll close this issue for now but let's further discuss that in #256 and if we agree on doing it here in leaflet.pm, I'll reopen this.
