### ISSUE TITLE
When in "Edit Mode," right-clicking counts as a mousedown event (and causes unexpected dragging)

### ISSUE THREAD

**Issue by adamtLICOR** [codeofsumit/leaflet.pm#260]
This can be seen even in the [demo](https://leafletpm.now.sh/#/).

1. Draw a Rectangle or Polygon
2. Enter "Edit Mode"
3. Right-click on the Polygon (which should bring up the default web browser context menu)
4. Right or left click somewhere on the opposite end of the map
5. The shape jumps (and then propagates normal click behavior)

**EXAMPLE:**
![right_click_bug_1](https://user-images.githubusercontent.com/16004285/33624179-19f475fa-d9b9-11e7-8f25-74a454772b49.png)
![right_click_bug_2](https://user-images.githubusercontent.com/16004285/33624181-1b5a91a4-d9b9-11e7-99cb-f57b5407da9c.png)

This isn't a huge deal by iteself, but creates a lot of unexpected behavior for complex use-cases. 

For example, I've bound a 'right-click' event in my application to delete a shape while in "Edit Mode." Because the 'right-click' counts as a mouse down for the purposes of dragging, it deletes the shape, but leaves the guide dots (as it still thinks it's "dragging" the shape, too)

![green](https://user-images.githubusercontent.com/16004285/33624257-69ccd2a2-d9b9-11e7-9088-1d9c558982cc.PNG)

Is it expected behavior for right-click to count as a "mouse-down" event? I can look at changing my application instead, if that's the case!

**EDIT:**
It appears the weirdness is exacerbated for Polygons. Right-clicking and then zooming with the mousewheel causes a similar issue, wherein the guide dots are still bound, but the polygon itself is not:

![poly_bug_1](https://user-images.githubusercontent.com/16004285/33624551-5db8fcd8-d9ba-11e7-9bb7-95d929229a79.png)

![poly_bug_2](https://user-images.githubusercontent.com/16004285/33624554-610e084c-d9ba-11e7-8203-46cf84a277d9.png)

**Comment by adamtLICOR** [comment]
I do have a fix for this (that seems to work), but I won't PR if right-click-to-drag functionality is expected or desired.

**Comment by codeofsumit** [comment]
hey @adamtLICOR. Let me get back to you on this on friday evening / saturday.
