### ISSUE TITLE
0.23.0 causing webpack build issues

### ISSUE THREAD

**Issue by fridgerator** [codeofsumit/leaflet.pm#261]
Hello, I work with @Mesonyx 

After updating to 0.23.0 our webpack build is failing with the following error: `Unexpected token name «n», expected punc «;»` when building our applications vendor.js file.

If I downgrade back to leaflet.pm 0.22.0, I no longer see that error.

I noticed in the leaflet.pm.min.js file there is still es6 syntax: `for(let n in e)`

My webpack skills are not very good, but should the min.js distributed file contain es6?

I was able to get around this by loading the leaflet.pm.min.js file through babel on our production builds.

Thanks!

**Comment by jpknapp** [comment]
Hey @fridgerator,
I was also having this issue, you're right, it's because the build is es6
I got it to work by adding this to the leaflet.pm webpack config, and making a new build:
```
modules: {
  loaders: [{
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015'],
        }
      }],
...
}
```

**Comment by codeofsumit** [comment]
thank you for reporting this. Will check and fix asap!

**Comment by mpschaeuble** [comment]
Took me now several hours to figure out that this is the reason for my failing test execution in phantomjs of an angular-cli build :-( Couldn't figure out to transpile 3dr-party libraries with angular-cli, therefore downgrading to 0.22.0.
Would be really helpful to fix this issue asap, thanks!

**Comment by codeofsumit** [comment]
hey everyone. Thanks for being so patient. Can someone try out this ☝️  commit and verify that the build is not failing? It works for me but a second test would be helpful.
If I get a +1 on it, I'd release asap

**Comment by hoeck** [comment]
Checked out 8cd2a8a and built it but the resulting `dist/leaflet.pm.min.js` is full of `let` keywords i.e. not valid ES5 and will fail in Phantomjs as well as when piped through UglifyJS (such as in our production build).

**Comment by codeofsumit** [comment]
Can you delete your node_modules folder, do a fresh npm install and try again?

**Comment by hoeck** [comment]
Did that before already a couple of times to be sure. Now I did it again but this time used plain `npm` and now it *works*.

Guess my mistake was using `yarn` initially to install the dependencies & create the build. Sorry for the delay.

So 👍 from my side for your fix! Thanks!
