### ISSUE TITLE
Touch event support

### ISSUE THREAD

**Issue by mpschaeuble** [codeofsumit/leaflet.pm#263]
On mobile devices with touch input only, most of the functionality of this plugin seems not to work. For example I've not been able to draw a circle or a polygon on the map. Leaflet itself is working really nice on touch devices.

Are there any plans to support touch input in the future?

**Comment by jhhosbond** [comment]
Really interesting lib. Nice work! As @mpschaeuble mentions - are there any plans regarding mobile / touch support?

**Comment by codeofsumit** [comment]
yes. I always thought it works 🤔  Will check and add support.

**Comment by codeofsumit** [comment]
I tested everything. Circle and Rectangle were broken and it will be fixed in the next release 👍
