### ISSUE TITLE
Failed to minify the code from this file: leaflet.pm.min.js

### ISSUE THREAD

**Issue by MarinusDR** [codeofsumit/leaflet.pm#264]
We think your pm is fantastic, but we get an error when building our react-app:
"Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file: 
 	./node_modules/leaflet.pm/dist/leaflet.pm.min.js:1:513  "
Is it possible to publish the package  pre-compiled (retaining ES6 Modules)?

**Comment by codeofsumit** [comment]
Hi @MarinusDR - I will release a new version soon that should fix this.

**Comment by MarinusDR** [comment]
Sounds good! Thank you!

**Comment by codeofsumit** [comment]
@MarinusDR can you test the latest release please?
https://github.com/codeofsumit/leaflet.pm/releases/tag/0.23.1
https://www.npmjs.com/package/leaflet.pm

Please reopen if you still have issues

**Comment by MarinusDR** [comment]
Hei Sumit,

I installed your latest version 0.23.1 and it works fine.
Thank you so much for your quick response and fix.
Very good!



Vennlig hilsen

Rieni de Rijke
rieni.derijke@norkart.no<mailto:rieni.derijke@norkart.no>
+47 990 45 157

[cid:79A5DF46-CF35-40C1-95E8-5CF195F1F34B]

Fåberggata 155
Postboks 393
N-2602 Lillehammer

+47 67 55 14 00
norkart.no<http://www.norkart.no/>

Fra: Sumit Kumar [mailto:notifications@github.com]
Sendt: 4. januar 2018 12:20
Til: codeofsumit/leaflet.pm <leaflet.pm@noreply.github.com>
Kopi: Rieni de Rijke <rieni.derijke@norkart.no>; Mention <mention@noreply.github.com>
Emne: Re: [codeofsumit/leaflet.pm] Failed to minify the code from this file: leaflet.pm.min.js (#264)


@MarinusDR<https://github.com/marinusdr> can you test the latest release please?
https://github.com/codeofsumit/leaflet.pm/releases/tag/0.23.1
https://www.npmjs.com/package/leaflet.pm

Please reopen if you still have issues
