### ISSUE TITLE
Edit, Delete in bulk with save/discard

### ISSUE THREAD

**Issue by ChaudhryAtif** [codeofsumit/leaflet.pm#266]
In Leaflet draw, it is possible to edit (move, resize), and delete multiple shapes and then you can either save the changes, or discard them. Is a similar feature of editing/deleting multiple and being able to save/discard them available in this library?

**Comment by codeofsumit** [comment]
hi @ChaudhryAtif, no it's not in the library and for now I'd consider this application logic in your code.
For example when the user starts editing, you save the current coords of that layer. Let the user edit it. Then provide a "save" and "discard changes" button.
I use leaflet.pm myself in different applications where that logic needs to be slightly different.

I hope leaflet.pm has all the events and hooks necessary to make this straightforward to implement for you (if not, open an issue for whats missing) but for now this is out of scope for this library.
