### ISSUE TITLE
Remove last vertex

### ISSUE THREAD

**Issue by MarinusDR** [codeofsumit/leaflet.pm#267]
How can one remove the last added vertex? 
Is there a key -function for it, just like the ALT-key when snapping?

**Comment by sasfeat** [comment]
@MarinusDR workaround:
```javascript

map.on('pm:drawstart', function(e) {
            this.workingLayer = e.workingLayer;
        },this);

removeLastVertex(){
    this.workingLayer.pm.enable();
    let markers = this.workingLayer.pm._markers;
    let m = markers[markers.length - 1];
    let e = {target:m};
    this.workingLayer.pm._removeMarker(e);
    let ls = this.workingLayer.pm._map.pm.Draw.Line._layerGroup._layers;
    let d = Object.keys(ls).pop();
    ls[d].remove();
    delete ls[d];
    this.workingLayer.pm._map.pm.Draw.Line._syncHintLine();
    this.workingLayer.pm.disable();
}
```

**Comment by codeofsumit** [comment]
definitely a useful feature - will add it 👍

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed

**Comment by codeofsumit** [comment]
there are enough upvotes. I will implement this.
