### ISSUE TITLE
Last marker remains on map

### ISSUE THREAD

**Issue by mkondur** [codeofsumit/leaflet.pm#271]
![bug](https://user-images.githubusercontent.com/7535008/34994668-955d89c0-fad4-11e7-8376-a0673e9f9ac1.gif)

When editing polyline when removing markers on right mouse click last marker still shown on map. I think it will be better to remove this marker when markers count less then 2

**Comment by codeofsumit** [comment]
thanks for the gif. You're totally right. This should be in place already though, which makes me think this is a bug.

**Comment by codeofsumit** [comment]
this was already included, but there was something wrong with the demo. It's fixed now. If you have this problem in your project, please create a JSfiddle where this problem is reproducable.
