### ISSUE TITLE
Spherical vs projected

### ISSUE THREAD

**Issue by mpschaeuble** [codeofsumit/leaflet.pm#272]
According to my understanding, when drawing a circle, its a spherical circle as it gets oval when drawn near the poles. However, polygons/lines are drawn on the projection otherwise they would be curved when drawn over big distances. This behaviour is a bit confusing and contradictory to me.

Ideally, lefalet.pm would allow two drawing modes: spherical and projected. What do you think?

**Comment by codeofsumit** [comment]
uh, very interesting topic. I've not yet looked into this. I agree but I'm afraid I won't have enough time to go into this in the near future. I'll leave the issue open though 👍

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed
