### ISSUE TITLE
Feature request: support geometry rotation

### ISSUE THREAD

**Issue by mpschaeuble** [codeofsumit/leaflet.pm#273]
It would be really cool to have rotation as an editing feature similar to Leaflet.Path.Transform (https://github.com/w8r/Leaflet.Path.Transform).

**Comment by codeofsumit** [comment]
how would you think of the rotation anchor? Could be centered, on a vertex or an arbitrary point. Do you think this should be editable too?

**Comment by mpschaeuble** [comment]
For my use case it would be totally fine to rotate only around the shape's center. But you are right, the rotation center could be any point in theory.

**Comment by Victornade** [comment]
Hi CodeofSummit,

First of, what an amazing work you made there ! Thanks a lot !

It would also be very interesting for me to enable rotation around the center of a Polygon ! Are you planning to implement it ?

Again, thank you very much for Leaflet.pm

**Comment by codeofsumit** [comment]
@Victornade thank you!
I will implement it but unfortunately I can't commit to a timeline as I'm very busy at work lately.

Other than that I'm always happy about Pull Requests.

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed

**Comment by abouroubi** [comment]
Is there any news about this ? It's third (#354) and forth in the feature requests.
If not do you think that Leaflet.Path.Transform can be used at the same time as leaflet-geoman ?

**Comment by Falke-Design** [comment]
@abouroubi we have this feature in our mind but it is not so easy to implement and we have currently no time for this, but we are open for a PR.

And yes you can use Leaflet.Path.Transform with Geoman togther, I used it in a other project but it is not offical supported.

**Comment by Falke-Design** [comment]
This feature is added with the Release 2.11.0
