### ISSUE TITLE
hintlineStyle option when allowSelfIntersection is false

### ISSUE THREAD

**Issue by SteveCline** [codeofsumit/leaflet.pm#275]
When option allowSelfIntersection is false, the hintlineStyle options are overwritten. In my code snip below change allowSelfIntersection back to true to see effect.

```
//Sample Code for the JSFiddle
map.pm.enableDraw('Poly', {hintlineStyle: {
    color: 'green',
    dashArray: [5, 5],
  }, allowSelfIntersection: false});
```

**Comment by codeofsumit** [comment]
could you please create a JS fiddle and provide the link to it so I can see the problem right away?

**Comment by SteveCline** [comment]
@codeofsumit,

https://jsfiddle.net/sbq24xqc/15/
