### ISSUE TITLE
add layer methods

### ISSUE THREAD

**Issue by SteveCline** [codeofsumit/leaflet.pm#276]
I have a few improvement methods that would be super helpful:

Similar to this:
```
// toggle edit mode
polygonLayer.pm.toggleEdit(options);
```
It would be nice to see these methods on individual leaflet layers to isolate add and delete from other layers on the map.
```
polygonLayer.pm.enableDraw();
polygonLayer.pm.disableDraw();
//Instead of this on all layers: map.pm.toggleGlobalRemovalMode(); to isolate individual layers
polygonLayer.pm.toggleRemove();
```

**Comment by codeofsumit** [comment]
@SteveCline this isn't in the library because it's easily done with leaflets own functionality.

``` js
layer.on('click', () => {
  layer.remove();
});
```

Is that sufficient?

**Comment by SteveCline** [comment]
@codeofsumit that is not sufficient unfortunately, say you have a map with multiple leaflet geoJson layers, but you want to isolate a layer and only edit, delete, or add features to that one layer at a time.

These methods would be super helpful, I hope you will consider!

Thanks again!

**Comment by SteveCline** [comment]
The layer.remove() will remove the entire layer, not just a single feature from the entire geoJson feature collection.

**Comment by codeofsumit** [comment]
@stevecline can you provide a jsfiddle showing the usecase?

**Comment by codeofsumit** [comment]
Closing this until a jsfiddle is provided to get a better understanding

**Comment by Falke-Design** [comment]
I think this is very similar to #583

**Comment by Falke-Design** [comment]
This feature is added with the Release 2.11.0
