### ISSUE TITLE
Working demo with clean code needed 

### ISSUE THREAD

**Issue by answerquest** [codeofsumit/leaflet.pm#283]
Hi, Great work. Can you point to a working demo on your Readme page? I cloned your repo on my machine. The `index.html` doesn't do anything despite having the .js and all included. The `demo/index.html` just shows 3 maps but no drawing toolbar etc. Even on your [demo site](https://leafletpm.now.sh/) there's just an [app.js] in the source code and I can't find any of the clean code you have given in the readme.

I found that your default branch is not master. I cloned the master branch, opened the demo/index.html and now even the map doesn't load.

I'm following the instructions in the Readme, but honestly a proper working demo file makes a world of difference for folks that aren't at the plugin-making level.

**Comment by cosme-benito** [comment]
In order for the demo/index.html you work you need the "dist" folder, which shouldn't come with the repository. Do you have the dist/leaflet.pm.min.js and dist/leaflet.pm.css files? If not then you need to build the project.

This is (part of) what you should be seeing when you open demo/index.html:

![image](https://user-images.githubusercontent.com/9701517/37040562-12f824fa-2152-11e8-9205-ee8ea74fb481.png)

The build process was simple, I had no problems at all. I had already installed NodeJS so all I had to do was

```
npm install
npm run build
```

Hope that helps.
