### ISSUE TITLE
pm:drawstart event don't work in programatically mode

### ISSUE THREAD

**Issue by ermakof** [codeofsumit/leaflet.pm#288]
I enable drawing mode programatically. Event pm:drawstart don't triggered. 
Example on jsfiddle: https://jsfiddle.net/ermakof/ehsc6vp4/16/

**Comment by slashy** [comment]
You're enabling drawing mode before you bind the event, thus the event can't trigger. If you first bind the event and then enable draw mode it works as supposed.

I updated your example to show how it works: https://jsfiddle.net/ehsc6vp4/33/

**Comment by ermakof** [comment]
Thanks so much!
