### ISSUE TITLE
Is this a Leaflet issue? "import {LatLng} from '../LatLng';"

### ISSUE THREAD

**Issue by leenbean16** [codeofsumit/leaflet.pm#289]
Not sure how I could debug this, 
but I am getting the "type error: cannot read property 'lat' of null."
then I look inside the source tab in the console and hover over the code:

          import {LatLng} from '../LatLng';

From the file /src/geo/projection/Projection.SphericalMercator.js

and I get a popup with "Unexpected token {"

**Comment by codeofsumit** [comment]
`/src/geo/projection/Projection.SphericalMercator.js` is not a file of `leaflet.pm` and your import is also not related to this plugin.

I guess you wanted to open that issue on this repo?
https://github.com/Leaflet/Leaflet
