### ISSUE TITLE
Problem with FeatureCollection

### ISSUE THREAD

**Issue by TPABHuKOB** [codeofsumit/leaflet.pm#290]
Hi there, thanks for awesome libary!
Im found problems while using leaflet.pm, here a demo via JSfiddle https://jsfiddle.net/TPABHuKOB/4nyhdq6r/ 
We have a list of geojson features, which we render as Leaflet objects.
Because geoJSON specification lacks a Circle object, we store it as Point and then use pointToLayer() function.  If i try run pm.enable() with this circle object its throw an error
```
Cannot read property 'addLayer' of null at e._initMarkers 
```

**Comment by codeofsumit** [comment]
Ok so this doesn't seem to be a problem with pointToLayer but more the with the featureCollection.

I've tried it and this should work:

``` js
L.geoJson(geoJsonData, {
    pointToLayer: (feature, latlng) => {
        if (feature.properties.customGeometry) {
            return new L.Circle(latlng, feature.properties.customGeometry.radius);
        } else {
            return new L.Marker(latlng);
        }
    },
    onEachFeature: (feature, layer) => {
        layer.addTo(map);
    },
});
```

**Comment by codeofsumit** [comment]
I was able to fix it 👍, will be in the next release!
