### ISSUE TITLE
Can't disable marker moving/deletion

### ISSUE THREAD

**Issue by augustoborn** [codeofsumit/leaflet.pm#292]
http://jsfiddle.net/sw5sjbgg/2/

If I create a marker, even if I pass options like:

```
var marker_options = {
    draggable: false,
    preventMarkerRemoval: true,
};
```

They only prevent moving and deletion during the first editing "session". If click the "edit" button twice, I'm able to delete and move the marker. Also, the marker is deletable through the "remove" button.

Is this expected behaviour? How can I disable moving and deleting markers?

**Comment by codeofsumit** [comment]
hi @augustoborn, no that's not expected. Thanks for reporting. Will be fixed in the next version
