### ISSUE TITLE
Help with detecting polygon

### ISSUE THREAD

**Issue by RobHayes512** [codeofsumit/leaflet.pm#298]
With my application, I only want the user to be able to save if they have closed off the line to form a polygon, I don't want them to be able to save if they just have a line(s) somewhere that don't connect to form a polygon. Is there a way to detect this?

**Comment by codeofsumit** [comment]
To detect whenever a new shape is finished (so a new layer gets created) you can use this:

```
// listen to when a new layer is created
map.on('pm:create', function(e) {
    e.shape; // the name of the shape being drawn (i.e. 'Circle')
    e.layer; // the leaflet layer created
});
```

See the readme for more details
