### ISSUE TITLE
Circle don't behave like other shapes regarding styles

### ISSUE THREAD

**Issue by Dahkon** [codeofsumit/leaflet.pm#304]
Hello,
I got an issue with circle shape only.
When enabling edit mode for circle I can't set the default style to be used. It works for others shapes.

Where mode = "circle" and options is a pathOptions object :
`map.pm.enableDraw(mode, options);`

Settings the defaults style before also doesn't work : 
`map.pm.setPathOptions(options);`

But setting styles with the layer method is setting the style correctly.
`layer.setStyle(options);`

Thanks,

**Comment by codeofsumit** [comment]
Hi @Dahkon, I tried to reproduce this but I don't see how this works in other layers 🤔.
Can you provide a JSfiddle or something that shows that this works with a polygon, but not with a circle please 🙏?

**Comment by codeofsumit** [comment]
nevermind, I misread. You mean the options should be there when drawing a shape. I fixed it - will be in the next release

**Comment by Dahkon** [comment]
Just in case the fiddle requested : 
https://jsfiddle.net/n3gL6wty/

Circle stay blue, others shapes are drawn red. 
;)

**Comment by codeofsumit** [comment]
Fixid by #313
