### ISSUE TITLE
Bug on drag markers on edit mode.

### ISSUE THREAD

**Issue by ichiro18** [codeofsumit/leaflet.pm#310]
Hello! I find bug on drag marker on edit mode :) 
The construction ``this._layer.setLatLngs(n).redraw(),`` is not stable. 

Because of it, an **error** occurs:
>  TypeError: this._layer.setLatLngs(...) is undefined
leaflet.pm.min.js:1:87388
updatePolygonCoordsFromMarkerDrag
leaflet.pm.min.js:1:87388
_onMarkerDrag
leaflet.pm.min.js:1:87554
fire
leaflet-src.js:593:5
_onDrag
leaflet-src.js:7246:2
fire
leaflet-src.js:593:5
_updatePosition
leaflet-src.js:5848:2
_updatePosition self-hosted:975:17 

**Solution:** 
Change this construction to a more explicit: `this._layer.setLatLngs(e), this._layer.redraw()`
**PROFIT :)**

Pls, fix this error, I want to use your brilliant product via NPM 👍

**Comment by ichiro18** [comment]
Oooh!!! The same error when drag a shape.
I use v0.25.0

**Comment by codeofsumit** [comment]
@ichiro18 I can not reproduce this error on the demo page:
https://leafletpm.now.sh

I don't see any errors when dragging markers or shapes - please provide a reproduction of the bug on JSFiddle, plunker or similar.

**Comment by ichiro18** [comment]
@car2go, Ok, i will try.
I think that this error appears when importing leaflet.pm via ES6-style import

**Comment by codeofsumit** [comment]
@ichiro18 I'm using leaflet.pm with ES6 style import in multiple apps - compiled with webpack and babel afterwards. I'm closing the issue for now - please reopen it when you can provide any kind of reproducible case so I can see and fix it 👍
