### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by fwk1010** [codeofsumit/leaflet.pm#311]
when I open in chrome,there are a mistake:
**Uncaught TypeError: Cannot read property 'addControls' of undefined
    at demo.js:61**

How to fix it?Thanks.

**Comment by codeofsumit** [comment]
Hi @fwk1010, 

current `develop` branch, the `demo/index.html`?
It does work for me. Can you provide some more details what exactly you're doing?

**Comment by fwk1010** [comment]
well,there are three examples in <code>demo/index.html</code>.I want to use <code>Editing A Polygon</code> and <code>Editing A Layer Group</code>,but they do not work.
@codeofsumit 
Thank you for your prompt reply.

**Comment by codeofsumit** [comment]
they do work fine for me - are there any errors in the console?

**Comment by codeofsumit** [comment]
@fwk1010 please run `npm run build` in the plugin folder and try again.

**Comment by codeofsumit** [comment]
Please reopen if the issue persists.
