### ISSUE TITLE
Set default vertex for draw polygon

### ISSUE THREAD

**Issue by ichiro18** [codeofsumit/leaflet.pm#315]
Hello! How can I continue drawing on the vertices specified by software?
E.g, i remove vertex from polygon and i'll continie draw.

**Comment by codeofsumit** [comment]
Hi, I’m not sure I understand what you’re trying to accomplish. 

You’re in drawing mode and want to remove the last vertex you’ve drawn, then continue drawing?

**Comment by ichiro18** [comment]
I need to develop 4 cases:
1) Edit vertex latlng in draw mode
2) Edit vertex latlng in edit mode
3) Delete vertex with unclose polygon and continue drawing
4) Edit vertex latlng on edit mode with unclose polygon and continue drawing

I think redraw polygon after edit, but i can't set default latlngs for vertex in draw mode

**Comment by codeofsumit** [comment]
Ok these are four completely different features. 

1. Edit vertices during draw, I created a new issue for it: #317 - please upvote it
2. This is already possible 
3. Is suggested here: #268, please upvote it
4. I probably won’t add this. You can do everything in edit mode, including adding new vertices. There is no need to “unfinish” a polygon and putting it back to drawing mode. If you disagree, please create a separate feature request for it 👌 

I think I will tackle 3. soon.
