### ISSUE TITLE
Cannot add point to polygon with a touch device

### ISSUE THREAD

**Issue by manuamador** [codeofsumit/leaflet.pm#318]
Hi, 
Thanks for your wonderful plugin.
One problem on touch devices. If a GeoJSON is loaded. With polygons and a pop up is opened with a click for every poly in the GeoJSON. Then it is impossible to add a point in the polygons when drawing a polygon as every click fired the open popup.
Is there a work around ?
Thanks.

**Comment by codeofsumit** [comment]
Hi @manuamador, would love to take a look - could you please provide a JSfiddle that shows the problem?

**Comment by codeofsumit** [comment]
As the issue is quite old now, please reopen with a repro if this is still an issue
