### ISSUE TITLE
Undo/Redo Options

### ISSUE THREAD

**Issue by agrimgupta92** [codeofsumit/leaflet.pm#320]
Is there any plan to add the option to undo/redo in polygons/polylines? I see from previous issues that you plan to add them. Can you please tell when the feature will be ready or suggest a temporary/hacky way to get it to work?
Update: I was able to get "undo" working as this pull request does this: https://github.com/codeofsumit/leaflet.pm/pull/284
Is it possible to add redo also?

**Comment by codeofsumit** [comment]
@agrimgupta92 I can't give any timelines, I work on leaflet.pm when I find the time.
a solution to add redo is to do this inside your application. Whenever the user changes something, or "undoes" something, save the layer and show a "redo" button. When the user clicks it, overwrite the layer with the saved one.

I will add #284 soon, I'm not sure about redo though.

I will mark this issue as a feature request, especially for Redo. Anyone who is also interested in this, please give it an upvote 👍

**Comment by Falke-Design** [comment]
Hey guys,
let us discuss how this should work.

1. For which modes / shapes should be undo / redo able to called?
2. Should be undo / redo called per layer / mode or on the complete project? The problem will be, that if undo is called over the project, we need to save the order when which layer was changed, this is not so easy
3. How often should be `undo` able to call? 
...

**Comment by henrikmaa** [comment]
This is my idea of how it should work

Modes:
- Cancel Edit: reset the object back to LatLng of pm:enable
- Undo: Revert to last vertex change(store position on vertex click #692), ideally this should be possible to revert multiple changes.

**Comment by Falke-Design** [comment]
We have added a `cancel` action to all modes in Geoman Pro. For now, this feature will not be included in the free version, and we will not be adding undo or redo functionality.

https://geoman.io/docs/leaflet/changelog/pro#v2140-adding-cancel-to-modes
