### ISSUE TITLE
Layers are not removed in pm obj

### ISSUE THREAD

**Issue by lio590** [codeofsumit/leaflet.pm#323]
It seems that there is a problem when you are removing layers / markers, they are removed from the layerGroup but not from the associated pm obj. So for exemple when you try to disable the layer you get an error " Cannot read property 'disable' of undefined" because inded the layers are not available anymore.
![sshoot](https://user-images.githubusercontent.com/35266377/43208564-0331798e-902b-11e8-9db2-1260a64f4f3f.jpg)

Here the codepen.io https://codepen.io/lio590/pen/xJrmjy
How to reproduce:
1- add 3 or 4 markers
2- click on "edit mode" and then click on the markers> you will see a popup with delete> click delete, delete few othem 
3- click on "disable markerLayer" and you will see in the log the error related to my diagnostic above

**Comment by lio590** [comment]
I have implemented a workaround however since teh layers are added "automatically" to pm they should be removed automatically as well. Not a big deal thought

**Comment by codeofsumit** [comment]
I simplified your codepen to isolate the issue.
The error is thrown as soon as you draw a marker. Unfortunately if I use the exact same code locally, it works so I'm still searching for the issue

**Comment by lio590** [comment]
Let me check

**Comment by lio590** [comment]
The error is hown only when you remove the marker and if you don't remove it from pm, if you do > no error please check https://codepen.io/lio590/pen/MBOZzy?editors=0010
Let me know if you have any question

**Comment by codeofsumit** [comment]
@lio590 please use the simplified example:
https://codepen.io/codeofsumit/pen/qyVMeo?editors=0010

The error is also thrown if I include the library into another project. And I even know how to fix it - but the error is still not thrown in my test suite 🤔  I want to write a test against this.

If you want, you can check out this branch:
https://github.com/codeofsumit/leaflet.pm/pull/326/files

run `npm run dev` and in another window `npm run cypress`, launch the `marker.spec` test and try throwing the error too. I was not able to do this today, will try again in a few days but any help is welcome.

**Comment by lio590** [comment]
Ok will try tomorrow :)
