### ISSUE TITLE
Cut from polygon using two points

### ISSUE THREAD

**Issue by dyachkov** [codeofsumit/leaflet.pm#325]
Hey,

Can I somehow cut polygon into two polygons using two points? Now, if I try to cut using `Point1 -> Point2 -> Point1` then nothing happens (`pm:cut` not fires). As I understand it is because two points do not form polygon. If so is there any solution for this? 

Thanks!

**Comment by codeofsumit** [comment]
Hi @dyachkov, thanks for the feature request - that is not possible yet. I'm changing the title to reflect this feature request and close the issue for more people to vote on it so I can prioritize building new features.

**Comment by Dastnbek** [comment]
Hi!

**Comment by codeofsumit** [comment]
@Dastnbek Cancel? Do you mean "undo" by any chance? If yes, you have to implement that yourself. Listen to the leaflet.pm events when cutting/dragging occur, save the current state of your polygon. When you user clicks your "undo" button, replace the new layers coords with your saved one

**Comment by codeofsumit** [comment]
Alright, this feature took us many many many weeks (and was quite expensive). Thats why this is currently only released inside Leaflet-Geoman Pro.
https://geoman.io/leaflet-geoman-pro

See the Splitting Feature in Action:
https://twitter.com/TweetsOfSumit/status/1295697712600449025

We hope to make this feature available to the OSS community in the future as well!
