### ISSUE TITLE
Guides for 90 degree

### ISSUE THREAD

**Issue by mohammedzamakhan** [codeofsumit/leaflet.pm#327]
Is there a way where I can have extra guide to show 90 degree to the user when he is in the quadrant of 45degrees to the last line.

I do not want leaflet.pm to add it, but if I can know if there is a event or something that can help me build it myself.

![screen shot 2018-08-01 at 11 46 41 am](https://user-images.githubusercontent.com/2327532/43536046-35cf4ab4-9581-11e8-8913-1ae9f0080e62.png)

the quadrants would be like this, but we would not be showing that in the UI
![screen shot 2018-08-01 at 11 50 21 am](https://user-images.githubusercontent.com/2327532/43536076-4daa9ff8-9581-11e8-92be-118e7355c7fe.png)

**Comment by codeofsumit** [comment]
mh good question. I would try it like this:

```js

map.on('pm:drawstart', function(e) {
    var layer = e.workingLayer;
    layer.on('pm:vertexadded', function(e) {
        // e includes the new vertex, it's marker
        // the index in the coordinates array
        // the working layer and shape
    });
});

```

in `vertexadded` you should get the latest coordinate that is added to the shape. You can place your guide in reference to it. Does this help?

**Comment by mohammedzamakhan** [comment]
I want the 90 degree guide only while dragging, these events are only called after you add.

**Comment by codeofsumit** [comment]
Could you place it at the cursor after dragstart?

**Comment by mohammedzamakhan** [comment]
When the angle between the blue dotted line and the violet dotted like is really less, we also want it to snap to the purple perpendicular guide.

**Comment by codeofsumit** [comment]
Ok sounds like you’d need an additional event. Shouldn’t be that hard. Marked as feature request! Feel free to submit a PR if you would like to help

**Comment by hoanphi2201** [comment]
@codeofsumit  @mohammedzamakhan  Any update for this feature.

**Comment by Falke-Design** [comment]
@hoanphi2201 there are no updates on this, and it will not implemented soon from our side. You can use the Sub-Library https://github.com/Falke-Design/PMOrtho it is working with the latest version 2.9.0

Same Feature Requests: #559, #327

**Comment by dailyprice** [comment]
This has been added as a feature in Geoman Pro: [Link to docs](https://www.geoman.io/docs/changelog/pro#v2110-added-snapguides )
