### ISSUE TITLE
Cancel operation

### ISSUE THREAD

**Issue by mohammedzamakhan** [codeofsumit/leaflet.pm#328]
Suppose I select Delete and clicked on a polygon that I didn't intend to by mistake, is there a way I can just cancel this operation? Like how Leaflet.draw gives the options?

**Comment by codeofsumit** [comment]
not yet. Seems like a useful feature thanks for the suggestion. Open for upvotes

**Comment by mohammedzamakhan** [comment]
Why would you close the issue, when you need upvotes?

**Comment by codeofsumit** [comment]
https://github.com/codeofsumit/leaflet.pm/blob/develop/README.md#feature-request

**Comment by codeofsumit** [comment]
I'm removing this from the Feature Requests as this will be covered by Undo/Redo https://github.com/geoman-io/leaflet-geoman/issues/320
