### ISSUE TITLE
Text Label

### ISSUE THREAD

**Issue by dior1** [codeofsumit/leaflet.pm#332]
Hi, would it be possible to add a Text Label to the Map? No Marker or something, only a Text.
kind Regards

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed

**Comment by agishk** [comment]
Any update open how to add text label?

**Comment by Falke-Design** [comment]
Hey guys please check #1120
