### ISSUE TITLE
The cutting line remains red when it no longer intersects with itself.

### ISSUE THREAD

**Issue by rafal-jaworski** [codeofsumit/leaflet.pm#333]
Steps to reproduce:
![image](https://user-images.githubusercontent.com/28957750/44454317-7a2ddb00-a5fb-11e8-87ad-326857081f56.png)
![image](https://user-images.githubusercontent.com/28957750/44454323-7dc16200-a5fb-11e8-9f54-17c54a496f22.png)
![image](https://user-images.githubusercontent.com/28957750/44454329-80bc5280-a5fb-11e8-8fca-6c3110008ea4.png)

**Comment by codeofsumit** [comment]
Thanks for reporting - will fix it!

**Comment by codeofsumit** [comment]
will be fixed in the next release 👍
