### ISSUE TITLE
How to listen to "pm:remove" event for a single layer

### ISSUE THREAD

**Issue by cihaniko** [codeofsumit/leaflet.pm#335]
I want to remove the layers / markers.
map.on ('pm: remove', function (e) {}) listens on all map layers. But I just want to listen a layer. I am trying to e.layer.on ('pm: remove' function {}) for this, it does not work.

**for example :** 
`map.on('pm:create', function(e) {

      // l want listen to remove on the new layer 
       e.layer.on('pm:remove', function(x) {
            console.log(' I want remove layer event ', x)
       });
});
map.on('pm:remove' , function(e){

	console.log("map layers remove event" , e);
});`
example JSFiddle : http://jsfiddle.net/LnzN2/4456/ 

If  removebutton when triggered in PmToolbar  , how to listen to  e.layer.on('pm:removed') ?

**Another question** 
 when called clearlayers() method in FeatureGroup etc.  The Map.on (pm: remove) event is triggered. my question is, can a different event be fired when a single layer is removed with removeButton in the toolbar? 

thanks, good works.

**Comment by codeofsumit** [comment]
Try the standard leaflet event:
https://leafletjs.com/reference-1.3.4.html#layer-remove

To the other question:
currently: no, `pm:remove` is fired whenever a layer is removed from the map - no matter in which way. I will open a feature request to add to the event _how_ the layer was removed.
