### ISSUE TITLE
Multiple Polygon Edit Controls

### ISSUE THREAD

**Issue by mohammedzamakhan** [codeofsumit/leaflet.pm#336]
I have three different types of polygons, and I want to have three different controls to edit different types of polygons. Is there anyway I can do it using leaflet.pm?

**Comment by codeofsumit** [comment]
Sure

**Functionality**
1. You can group your types of polygons into LayerGroups or FeatureGroups and call `group1.pm.enable` to make a specific group editable.
2. Or you store them in variables and loop over them: `group1.forEach((layer) => {layer.pm.enable()});`

**Controls**
You can do any kind of button in your application that calls the functionality methods, including adding controls to the map. That's not leaflet.pm functionality though.
Here is one way to add a button do a map: https://github.com/CliffCloud/Leaflet.EasyButton

**Comment by mohammedzamakhan** [comment]
I tried doing `group1.pm.enableDraw('Poly')`, but I got an error, how do I draw a polygon in a particular group?

**Comment by codeofsumit** [comment]
You have to add them to the group **after** the layer was created.

something like this:
```
group1 = L.FeatureGroup();
group2 = L.FeatureGroup();

map.on('pm:create', (e) => {
  if(e.layer.something === 'somethingElse') {
    // add to group1
  } else {
    // add to group2
  }
});
```
