### ISSUE TITLE
Adding a hint at location where it will snap, if you get close

### ISSUE THREAD

**Issue by mohammedzamakhan** [codeofsumit/leaflet.pm#342]
I wan't to add a hint for the users who are drawing the shapes where it will snap if you go closer to that point.

Is there anything I can do in my application to enable this?

![screen shot 2018-10-02 at 11 43 07 am](https://user-images.githubusercontent.com/2327532/46363421-94b29580-c638-11e8-9228-13cbe1d2bc18.png)

**Comment by mohammedzamakhan** [comment]
so lets suppose the snapping distance is 3, and to show hints the distance is 4, we will show this hints if the distance is in between 3 and 4, and if its gets less than 3, it directly goes and snaps

**Comment by codeofsumit** [comment]
that's cool! Will close until it has more upvotes or until needed for myself 👍 
Cool idea!
