### ISSUE TITLE
When edit a circle my layers group gets cleared

### ISSUE THREAD

**Issue by henev** [codeofsumit/leaflet.pm#345]
So I create a `layers = new leaflet.FeatureGroup()` to store any new shapes I draw like `this.layers.addLayer(e.layer);`. The thing is that when I draw a circle and then toggle global edit mode my layers disappear from my array (but not from the map). I guess it has something to do with this line of code:

https://github.com/codeofsumit/leaflet.pm/blob/700699ca1663514aee0e394350fb827c5330293e/src/js/Edit/L.PM.Edit.Circle.js#L51

Why is the circle `_initMarkers()` different and is clearing layers instead of markers and how my layers are connected to the circle layer group? Very strange behavior.

Any ideas?

**Comment by codeofsumit** [comment]
@henev hmm good point, sounds like a bug. Will investigate 👍  - thanks for reporting!

**Comment by codeofsumit** [comment]
it seems like this is the same problem as #290 🤔
And it is VERY weird. Still investigating...

**Comment by codeofsumit** [comment]
I was able to fix it 👍, will be in the next release!
