### ISSUE TITLE
Limit to one shape

### ISSUE THREAD

**Issue by powersofsmithy** [codeofsumit/leaflet.pm#347]
Is there a way to limit the drawing to one shape, or remove previous shapes when drawing a new shape?

Thanks

**Comment by codeofsumit** [comment]
sure, listen to the `pm:draw` event and then disable the functionality or remove the previously drawn shapes.

**Comment by powersofsmithy** [comment]
i'm listening to the pm:draw event, but I can't get the event to fire.

 map.on('pm:draw', function (e) {
        debugger;
    });

**Comment by codeofsumit** [comment]
as soon as you finish drawing of a shape via leaflet.pm, the event is fired.

If the event doesn't fire in that scenario for you, please create a JSfiddle recreating the problem so we can investigate together.

**Comment by powersofsmithy** [comment]
i get pm:create fired when the shape is drawn, but not pm:draw

**Comment by codeofsumit** [comment]
ah sorry, my bad. There is no `pm:draw` event. How did you come up with it? The events for drawing mode are listed here:
https://github.com/codeofsumit/leaflet.pm#drawing-mode

**Comment by powersofsmithy** [comment]
it was from your suggestion to use pm:draw.

> Is there a way to limit the drawing to one shape, or remove previous shapes when drawing a new shape?
> 
> Thanks

**Comment by codeofsumit** [comment]
LOL omg 🤦‍♂️ . I definitely need vacation. Sorry about that.

`pm:created` is the event. Please check the README, it is up to date and functions better than my brain today 😅 .
