### ISSUE TITLE
Drawing on mobile

### ISSUE THREAD

**Issue by fg5002** [codeofsumit/leaflet.pm#350]
Dear Sumit,

First let me congratulate to your work.
To me, this is the first really useful mobile friending map editing plugin.

I am using an L.divIcon, let's say cursor, to draw precisely on map. It works well, but I have some problems at drawing:

- There is a strange behaviour: cursor doesn't snap until I click marker button on toolbar.
- Due to the rare occurences of the self intersected lands on earth, is it possible to disable self intersection polygon by default, as it can see when editing a polygon whith hole?
- To finish the Line/Poligon is nearly impossible to hit the last/first point with the cursor, I need to do it with finger. It would be great if the cursor could snap to those points.

![screenshot_1_proc](https://user-images.githubusercontent.com/44635286/47782928-b4a1ab80-dd01-11e8-8b85-43d29f930462.jpg)

To sync the L.divIcon at edit mode is beyond my knowledge, therefore I have made a workaround by modifying your marker-icon and marker-icon-middle classes to make the cursor. It works, but I really missing the tip of the cursor.
Is it possible to implement the same cursor or at least a 'tip'?

![screenshot_2_proc](https://user-images.githubusercontent.com/44635286/47783653-92a92880-dd03-11e8-939d-45fadedc9a0e.jpg)

[drawingjs.txt](https://github.com/codeofsumit/leaflet.pm/files/2534136/drawingjs.txt)
[drawingcss.txt](https://github.com/codeofsumit/leaflet.pm/files/2534137/drawingcss.txt)

Thanks for your patient, this is my first time here :)

Regards,

**Comment by codeofsumit** [comment]
Hi @fg5002, thank you for the kind words and using my plugin.
Regarding the self intersection:
> Due to the rare occurences of the self intersected lands on earth, is it possible to disable self intersection polygon by default, as it can see when editing a polygon with hole?

Pass your options right from the beginning like this:
```js
const options = {
  allowSelfIntersection: false,
}
map.pm.enableDraw('Poly', options);
map.pm.disableDraw('Poly');
```

This should preserve these options for later drawings (so self intersection is never allowed.

Regarding your other points, it would be really great if you could create a small map on http://jsfiddle.net/ with your custom icon so I can see it in action and experience the problems myself.
I can help you much better then :-)

**Comment by fg5002** [comment]
Hi @codeofsumit , thank you for your quick reply.

Regarding self intersection, I have tried, but it has no effect since my icon only fires a click on map.

JSFiddle: http://jsfiddle.net/53z4ub2y/4/

Please note, that at drawing only the marker's behaviour is the same as on mobile.
On mobile I can't draw circle yet even without custom icon. After the first point it dies.

Also I found a strange thing: when I cut a rectangle with a triangle, as the image shown below, the results will be one rectangle and a triangle with an outer hole, instead of three independent polygons.

![strange](https://user-images.githubusercontent.com/44635286/48184543-ab809200-e332-11e8-9f70-9e6f8f2e3028.jpg)

**Comment by codeofsumit** [comment]
@fg5002 can you please test your issues again with the latest version and let me know which ones you're still experiencing?

- [ ] Draw Circle on mobile not working
- [ ] Self Intersection on Mobile
- [ ] Problems finishing a shape on mobile

> also I found a strange thing: when I cut a rectangle with a triangle, as the image shown below, the results will be one rectangle and a triangle with an outer hole, instead of three independent polygons.

This is expected. If you cut a polygon, it will become a MutliPolygon. You can extract it's features to create separate polygons but in general, this is still one shape, just with a whole in it.

Draw Circle and Finishing a Shape should be fixed. Let me know 👍

**Comment by codeofsumit** [comment]
I think most of this is fixed. I will close the issue for now. Please reopen (or create a new dedicated issue per problem) once you discover problems
