### ISSUE TITLE
Tooltips and Toolbar Title language options

### ISSUE THREAD

**Issue by m1dst** [codeofsumit/leaflet.pm#353]
I couldn't find a way to set tooltips for the control buttons.  Did I miss a config setting to provide them?  If not it would be really great to support tooltips via configuration so we can support multiple languages.

**Comment by codeofsumit** [comment]
no, they're missing right now but I'm working on them RIGHT NOW.

**Comment by codeofsumit** [comment]
I changed the title of this issue. The next release will have titles in the toolbar and tooltips to help users what to do - however, they're in english only.

I will use this issue as a feature request to make this configurable so you can customize the titles and messages.

(Remember, I close Feature Requests so they can gather upvotes and I can still see Bugs & Questions)

**Comment by wishinghand** [comment]
So there's currently no way to rename existing tooltips?

**Comment by codeofsumit** [comment]
@wishinghand not yet

**Comment by ukhack** [comment]
I meet the same problem.

**Comment by VCodepp** [comment]
Is there an improvement on this topic?

**Comment by codeofsumit** [comment]
this is a duplicate of #376 which was just implemented through #424.
Will be in the next release 👍
