### ISSUE TITLE
How to draw a Rectangle at an angle

### ISSUE THREAD

**Issue by mohammedzamakhan** [codeofsumit/leaflet.pm#354]
Is there any way I can create rectangle at an angle like this one?

<img width="660" alt="screen shot 2018-11-07 at 3 19 11 pm" src="https://user-images.githubusercontent.com/2327532/48161580-82afbc80-e2a0-11e8-8c9b-0c56d6fcc6a1.png">

**Comment by mohammedzamakhan** [comment]
![rectangle tool](https://user-images.githubusercontent.com/2327532/48225027-42fcd980-e361-11e8-9850-842f8584e688.gif)

**Comment by mohammedzamakhan** [comment]
@codeofsumit can this be implemented using leaflet pm?

**Comment by codeofsumit** [comment]
Hi @mohammedzamakhan, not right now, no. But it's a nice feature to have. I think it could be done with a rotating feature but I have to think about it. Will close to wait for upvotes in order to prioritize it

**Comment by Falke-Design** [comment]
This feature is added with the Release 2.11.0
