### ISSUE TITLE
Drow Polygon

### ISSUE THREAD

**Issue by devzonetrack** [codeofsumit/leaflet.pm#355]
How to draw polygon/polyline from existing points?

**Comment by mohammedzamakhan** [comment]
What do you exactly mean by the question?

**Comment by codeofsumit** [comment]
@devzonetrack 

you can either edit the existing polyline/polygon and add new points to it.
![polyedit](https://user-images.githubusercontent.com/2399810/48602936-16eee300-e975-11e8-887b-62d179ffd36b.gif)

Or you can draw a new polygon and let it snap to the existing vertexes or the other polygons
![polydraw](https://user-images.githubusercontent.com/2399810/48602957-266e2c00-e975-11e8-8fd4-c1662bdfa656.gif)

There is no other option right now.
