### ISSUE TITLE
bug when moving a circle

### ISSUE THREAD

**Issue by matthieugayon** [codeofsumit/leaflet.pm#357]
On the default jsfiddle http://jsfiddle.net/LnzN2/1332/ , zoom out to the first level of zoom, draw a circle, then toggle edit mode and drag the circle's center from one pole to the other, and get back to your initial position, the circle's radius changed (most likely increased dramatically).

**Comment by codeofsumit** [comment]
are you talking about this? Wow...
![circlebug](https://user-images.githubusercontent.com/2399810/48602767-8912f800-e974-11e8-9fe7-2fb866da5e1c.gif)

Will check, thanks for reporting. If you have more details I could debug this with, feel free to report them here. Would appreciate it 👍

**Comment by themre** [comment]
could be that leaflet.pm handles area in projections? so size closer to the pole seems smaller but is very large whereas on the equator is larger but area could be smaller.

**Comment by codeofsumit** [comment]
@themre was also thinking about this but the jumping of the size seems buggy still 🤔

**Comment by codeofsumit** [comment]
would be great to get some help on this. Why is this happening? How can we prevent it? Is this actually an issue for users?

**Comment by ashmigelski** [comment]
I inspected code and found where problem in [this._resizeCircle](https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Edit/L.PM.Edit.Circle.js#L100) method

It is called in 2 situations:
- when you drag outer marker (it's ok)
- when you drag center marker: it calls `this._layer.setLatLng(center);` in handler and fire 'move' event [internally in leaflet](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/CircleMarker.js#L38)

I tried to filter event in `this._resizeCircle` to handle only mouse events, result looks better
```diff
    _resizeCircle(evt) {
+        // check if real mousemove, not synthetic call
+        if (evt.originalEvent) {
            this._syncHintLine();
            this._syncCircleRadius();
+        }
    }
```

**Comment by codeofsumit** [comment]
This improved the situation but I think it's not entirely fixed.

**Comment by codeofsumit** [comment]
Now behaves as expected.

![circle](https://user-images.githubusercontent.com/2399810/52883953-e7669700-316c-11e9-94a5-9f2b33c6c169.gif)
