### ISSUE TITLE
allowSelfIntersection on polygons

### ISSUE THREAD

**Issue by matthieugayon** [codeofsumit/leaflet.pm#358]
Looks like the intersection computation is slightly offset. I can't repeat it on the default jsfiddle, but in my implementation (I'm using different tiles and I'm basically adding the created polygons to a geoJson layer group)

<img width="568" alt="screen shot 2018-11-15 at 21 02 31" src="https://user-images.githubusercontent.com/3694172/48582533-175f8d80-e925-11e8-865c-b2f30a875fa5.png">
<img width="605" alt="screen shot 2018-11-15 at 21 02 39" src="https://user-images.githubusercontent.com/3694172/48582537-19295100-e925-11e8-9e36-b6bc18cfd357.png">

Here is my implementation : 
```javascript
componentDidMount() {
    this._map = L.map(this._mapNode, { center: mapCenter, zoom: 2 })
    this._map.pm.addControls(mapControls)

    L.tileLayer(
			'http://tiles.quaidorsay.fr/tile/forte{r}/{z}/{x}/{y}.png',
			{ attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors' }
		).addTo(this._map);

		this._map.pm.enableDraw('Poly', {
			snappable: true,
    	snapDistance: 20,
			allowSelfIntersection: false
		});
		this._map.pm.disableDraw('Poly')

		this._geojsonLayer = new L.GeoJSON().addTo(this._map);
		this._geojsonLayer.pm.enable({
    	allowSelfIntersection: false
		})

		this._geojsonLayer.on('pm:dragend', this.cleanAndKeepEdit)
		this._geojsonLayer.on('pm:vertexadded', this.cleanAndKeepEdit)
		this._geojsonLayer.on('pm:vertexremoved', this.cleanAndKeepEdit)
		this._geojsonLayer.on('pm:markerdragend', this.cleanAndKeepEdit)

		this._map.on('pm:create', (e) => {
			this._geojsonLayer.addLayer(e.layer)

			if (e.shape && e.shape === 'Circle') {
				this.setState({ mode: 'circle' })
				this._map.pm.addControls({
					drawPolygon: false,
					drawCircle: false
				})
				this.updateOutputShape()
			}
			else {
				this.setState({ mode: 'poly' })
				this.cleanLayers()
				this._map.pm.addControls({
					drawCircle: false
				})
			}
		})

		this._map.on('pm:remove', (e) => {
			// prevent cleanLayers in the cleanLayers fct to trigger this fct
			if (this.state.blockRemoval) return
			// if no layer information
			if (!e || !e.layer) return
			// if event fired from underlying removal of temp layer from leaflet.pm
			if (!e.layer.feature && !e.layer._mRadius) return

			this._geojsonLayer.removeLayer(e.layer)
			this.updateOutputShape()

			if (!this.hasLayer()) {
				this.setState({ mode: 'all' })
				this._map.pm.addControls({
					drawCircle: true,
					drawPolygon: true
				})
			}
		})
	}
```

**Comment by matthieugayon** [comment]
@codeofsumit I could actually repeat on the jsfiddle, see the screenshot bellow and notice I set the allowSelfIntersection to false for the Polygons. I could repeat it by zooming out to the first level of zoom, then creating the condition for an intersection and zooming in to see what happens at the edge of the intersection.

This is exactly what's going on in my implementation, except that it's a bit more obvious on mine. 

<img width="1278" alt="screen shot 2018-11-16 at 13 37 44" src="https://user-images.githubusercontent.com/3694172/48621918-6e0cac00-e9a5-11e8-9346-cc09277145ab.png">

**Comment by codeofsumit** [comment]
@matthieugayon I'm unable to reproduce this. Can you please post a link and an step-by-step description how to reproduce the issue?

**Comment by matthieugayon** [comment]
@codeofsumit I'll do so asap

**Comment by codeofsumit** [comment]
please reopen with a reproduction link 👍
