### ISSUE TITLE
How to finish a draw by click in a button?

### ISSUE THREAD

**Issue by matheussiba** [codeofsumit/leaflet.pm#361]
I don't know if here is the right place for asking this kind of things.
But I'm wondering how could I do in order **to finish a draw** by instead of clicking in the `first node` or using `dblclick, contextmenu, mouseout` events, I'd like to use a `button`. 
What would be the simplest way for doing that?

**Comment by codeofsumit** [comment]
HI @matheussiba, the next version of leaflet.pm has that.
It's [already in the code here](https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Toolbar/L.Controls.js#L94) and will look like this:

![removelastvertex](https://user-images.githubusercontent.com/2399810/49162963-4c5bdf00-f32c-11e8-948c-fc9ccde65426.gif)

If you want to create your own button, create it and call the `_finishShape()` function of the respective `Draw` class. Problem will be finding out that class so you might have to do some looping (e.g. loop across classnames, check if Drawing is enabled, if yes, finish it). Every class has the `_finishShape()` function do finish it so you can do it 👍
