### ISSUE TITLE
Remove last vertex with directly function call

### ISSUE THREAD

**Issue by swapster** [codeofsumit/leaflet.pm#369]
How can I remove the last added vertex without using control buttons on the map?
Is there any ways to do this?
I've tried something like this:
```javascript
map.on('pm:drawstart', function (e) {
   e.workingLayer.on('pm:vertexadded', function (e) {
      this._map.pm.Draw.Line._removeLastVertex.apply(this.pm)
   })
})
```
but got an error:
`TypeError: Cannot read property 'getLayers' of undefined`
If I just call `this._map.pm.Draw.Line._removeLastVertex()`, I got another error:
`TypeError: Cannot read property 'getLatLngs' of undefined`
So, as I understand, the problem is in context of the `_removeLastVertex` function.
Can I somehow fix this, with `apply()` or anything?
Thanks.

**Comment by codeofsumit** [comment]
if you are in drawing mode, simply call 
```js
map.pm.Draw.Line._removeLastVertex();
```
or
```js
map.pm.Draw.Poly._removeLastVertex();
```
and it removed the last vertex

**Comment by n1kkou** [comment]
> if you are in drawing mode, simply call
> 
> ```js
> map.pm.Draw.Line._removeLastVertex();
> ```
> 
> or
> 
> ```js
> map.pm.Draw.Poly._removeLastVertex();
> ```
> 
> and it removed the last vertex

In the latest version is map.pm.Draw.Polygon._removeLastVertex();
