### ISSUE TITLE
GeoJSON with points throws Uncaught TypeError: Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by xmojmr** [codeofsumit/leaflet.pm#37]
If GeoJSON layer contains points then `pm` logs console error `Uncaught TypeError: Cannot read property 'enabled' of undefined` when it sees the L.Marker type of layer.

To reproduce use this: http://plnkr.co/edit/ZjLXPgIWpcAq2k9xIKoJ?p=preview

Expected behavior: `map.fitBounds(geoJsonLayer.getBounds())` gets called
Actual behavior: `map.fitBounds(geoJsonLayer.getBounds())` is not called because call to `geoJsonLayer.addData(json)` throws an exception

**Comment by codeofsumit** [comment]
argh just saw this. Will take care of it this weekend (and thanks for the PR)

**Comment by do13** [comment]
Did you find time to look deeper into this?
I've seen similar issues in combination with leaflet-search plugin.

Stacktrace:
leaflet.pm.js:640 Uncaught TypeError: Cannot read property 'enabled' of undefined
enabled @ leaflet.pm.js:640
(anonymous function) @ leaflet.pm.js:611
fire @ Events.js:1
addLayer @ FeatureGroup.js:1
setLayer @ leaflet-search.src.js:175
onAdd @ leaflet-search.src.js:117
addTo @ Control.js:1
addTo @ leaflet-search.src.js:134
addControl @ Control.js:1
(anonymous function) @ (index):141
dispatch @ jquery-git.js:5093
elemData.handle @ jquery-git.js:4901

https://jsfiddle.net/fqaj20or/

@xmojmr fix doesn't resolve the problem in my case

**Comment by codeofsumit** [comment]
merged your PR - sorry for the delay.
New release is here: https://github.com/codeofsumit/leaflet.pm/releases/tag/v0.6.3
you can update via `bower install`
