### ISSUE TITLE
Failed to add marker through toolbar

### ISSUE THREAD

**Issue by pkuwwt** [codeofsumit/leaflet.pm#375]
I use leaflet.pm in my webpack project, however, I failed to add marker through toolbar.

When I click the marker icon in the toolbar, an error occurs in the console:

GET data:image/png.......=“)marker-icon.png net:ERR_INVALID_URL

So there is the additional “)marker-icon.png appended to the url, which seems a problem of ‘leaflet/src/layer/marker/Icon.Default.js’.

Maybe it is a problem of leaflet, or a bug of leaflet.pm.

Leaflet version: 1.4.0
Leaflet.pm version: 1.2.1

**Comment by codeofsumit** [comment]
@pkuwwt have you tried adding a marker without leaflet.pm? Just with regular leaflet.
`L.marker([51.5, -0.09]).addTo(map)` - if the same error occurs, it's probably not a problem with this plugin but your leaflet setup.

My guess it's this issue:
https://github.com/Leaflet/Leaflet/issues/4968

If I'm wrong, let me know and I will reopen this issue 👍

**Comment by pkuwwt** [comment]
Yes, it is the problem of leaflet. Thanks
