### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by ttill** [codeofsumit/leaflet.pm#376]
It would be great if the strings used in leaflet.pm could be customized to allow for e.g. localization. Leaflet.draw has [`L.drawLocal`](https://github.com/Leaflet/Leaflet.draw#customizing-language-and-text-in-leafletdraw) through which texts can be overwritten. Something similar would be great.

Thanks for this awesome plugin!

**Comment by codeofsumit** [comment]
Great suggestion. Added as a feature request. **Please upvote if you want this implemented**!

**Comment by codeofsumit** [comment]
I'm on it!

**Comment by codeofsumit** [comment]
Alright, the PR #424 should be ready. Anyone willing to test the branch? Documentation is in [its README](https://github.com/codeofsumit/leaflet.pm/tree/i18n-support#customize).

**Comment by ashmigelski** [comment]
Looks good!

Playing with russian, tooltips switched off
![i18n](https://user-images.githubusercontent.com/4904519/56584251-145b7e00-65e4-11e9-88db-6b464edddbff.gif)

Custom translation also works for me
