### ISSUE TITLE
Feature: add 'icon' in drawing options

### ISSUE THREAD

**Issue by alisabondarev** [codeofsumit/leaflet.pm#388]
Add 'icon' for enableDraw("Marker", options) so it will be easy to redefine the marker, the default value can be "new L.Icon.Default()".

I want to use Leaflet.AwesomeMarkers plugin instead of default marker.

Thanks!

**Comment by codeofsumit** [comment]
nice feature! Will add it in the future. Closing for now until more upvotes are on it (to help me prioritize).

**Comment by tor0405** [comment]
Need this aswell!

**Comment by Falke-Design** [comment]
@codeofsumit Why not use the default `markerStyle` option?

```
var icon = L.icon({
    iconUrl: 'https://placekitten.com/200/287'
})

map.pm.enableDraw('Marker',{markerStyle: {icon: icon}})
```

**Comment by codeofsumit** [comment]
Will this be compatible with the AwesomeMarkers plugin? I have not used it myself yet

**Comment by codeofsumit** [comment]
Just talked to @Falke-Design. Changing the default marker icon is already possible by passing standard leaflet marker options to the `enableDraw` function (see README).

Is this specifically about AwesomeMarker Plugin compatibility? Because that's a different story.

**Comment by Falke-Design** [comment]
AwesomeMarkers are also compatible with Geoman.

```
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.awesome-markers@2.0.5/dist/leaflet.awesome-markers.css">
<script src="https://cdn.jsdelivr.net/npm/leaflet.awesome-markers@2.0.5/dist/leaflet.awesome-markers.min.js"></script>
```
```
// Creates a red marker with the coffee icon
var redMarker = L.AwesomeMarkers.icon({
  icon: 'coffee',
  prefix: 'ion',
  markerColor: 'red'
});

map.pm.enableDraw('Marker',{markerStyle: {icon: redMarker}})
```
