### ISSUE TITLE
Error in console when remove last vertex

### ISSUE THREAD

**Issue by ashmigelski** [codeofsumit/leaflet.pm#392]
Found error in console after click `Remove last vertex`.

**Steps to reproduce:**
- start draw polygon
- click on map to add first point
- click on `Remove last vertex` in toolbar
- check console, error will there

![peek 2019-01-24 12-26](https://user-images.githubusercontent.com/4904519/51668660-c7134480-1fd3-11e9-960f-fa7c3c53d8d2.gif)

PS leaflet.pm works very well for me! Thanks

**Comment by codeofsumit** [comment]
Thanks for reporting it. Please try version 2.0.1 - should be fixed 🤞

**Comment by ashmigelski** [comment]
Updated to version 2.0.1
`removeLastVertex` fixed! 

But I found same issue with 'Finish' button
![peek 2019-01-25 13-42](https://user-images.githubusercontent.com/4904519/51741272-87b62800-20a7-11e9-8867-4c36946bcf18.gif)

**Comment by codeofsumit** [comment]
hm I don't get that error @ashmigelski 🤔
The shape is not finished (which is correct) but for me it doesn't throw an error.
Do you also see that on the demo page?

**Comment by codeofsumit** [comment]
@ashmigelski nevermind, I found it. Fixed. Will be in the next release, thanks for reporting 👍

**Comment by ashmigelski** [comment]
Nice to hear
I leave screenshot about my error here, it's about `allowSelfIntersection: false`
![error](https://user-images.githubusercontent.com/4904519/51753128-18056480-20ca-11e9-9fef-466d4c3f1fcc.png)

Thanks again!
