### ISSUE TITLE
how to get edited polygon coordinates like forEach function from geojson layer with the pm:update/edited function

### ISSUE THREAD

**Issue by monepa** [codeofsumit/leaflet.pm#398]
The leaflet pm is amazing and i was very helped by it. but I have difficulty when I want to get the coordinates of the geojson layer that I edited. I made a geojson layer from the data in the database like the following

function GeoDbDisplayData() { 
        db.transaction(function (tx) {
            tx.executeSql('SELECT*FROM table_geo', [], function(tx, results){

                var n = results.rows.length, i;
                for(var i=0; i<n; i++){
                    var geom = results.rows.item(i);

                    var id = geom.id;
                    var polygon = geom.polygon;

                    var polpars = JSON.parse(polygon);
                    
                    var geojsondrw = {
                        "type": "Feature",
                        "properties": {"id": ""+id+""},
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": polpars
                        }
                    };

                    var str = JSON.stringify(geojsondrw);
                    var polfordisplay = JSON.parse(str);  

                    var polygonLayer = L.geoJson(polfordisplay).addTo(map);

                    polygonLayer.on('pm:update',({ lyr }) => {
                        var polyedit = polygonLayer.toGeoJSON();
                        var polstr = JSON.stringify(polyedit);
                        var poldb = JSON.parse(polstr);
                        console.log(polstr); //Here i need only edited polygon/parcel coordinates, not all in polygonLayer geojson
                    })

                });
                         
            }
                
        });
    });
};

what did i do wrong?
Thanks.

**Comment by codeofsumit** [comment]
```js
polygonLayer.on('pm:update',({ lyr }) => {
  var polyedit = polygonLayer.toGeoJSON();
  var polstr = JSON.stringify(polyedit);
  var poldb = JSON.parse(polstr);
  console.log(polstr);
})
```

1. There is no `pm:update` event. It's `pm:edit`.
2. You are using `polygonLayer` (the old layer) inside the callback instead of `lyr` (the new layer).
2. You can use standard leaflet functions to get coordinates from layers. Like `lyr.getLatLngs();`

Try this:

```js
polygonLayer.on('pm:edit',({ lyr }) => {
  var coords = lyr.getLatLngs();
  var polyedit = lyr.toGeoJSON();
  console.log(coords);
  console.log(polyedit);
})
```

**Comment by monepa** [comment]
Thank you for the response, I will try it and will inform you about the results as soon as possible

**Comment by monepa** [comment]
hi again, after trying your advice I still haven't found it, with results  "Uncaught TypeError: Cannot read property '0' of undefined". Thanks for your help
