### ISSUE TITLE
pmIgnore:true doesn't working with remove button

### ISSUE THREAD

**Issue by cihaniko** [codeofsumit/leaflet.pm#401]
Hi there,

I'm drawing polygon with programatically or with toolbar. I'm giving the "pmIgnore:true" and added to Featuregroup. "PmIgnore" works very well when I want to drag or edit, but this polygon was deleted when I wanted to delete it from the toolbox with the delete button. However, if "pmIgnore: true" should not be deleted.
Or is there a place I missed?

The other problem when I want to delete the polygon. If pmIgnore: true and polygon is in a featureGroup, is the featuregroup being remove from the map layers.  why is it deleting featuregroup ? 

Jsfiddle=http://jsfiddle.net/86o79g0s/1/
Make a drawing polygon. After, this polygon remove with remove button in toolbar

I need help.
Best regards.

**Comment by codeofsumit** [comment]
thanks for reporting, will be fixed in the next release 👍
