### ISSUE TITLE
Wrong Demo link

### ISSUE THREAD

**Issue by Falke-Design** [codeofsumit/leaflet.pm#404]
The Demo link is wrong. [https://leafletpm.now.sh/](https://leafletpm.now.sh/)
Right one is: [https://geoman.io/studio](https://geoman.io/studio)

**Comment by codeofsumit** [comment]
Hi @Falke-Design, thanks for the report.
`leafletpm.now.sh` redirects to `geoman.io/studio`

If it doesn't for you, there might be a browser-cache issue.
Additionally, I have now deployed a redirect on the website so `/editor` (the old link) is redirecting you to `/studio`. 
Please let me know if you still have issues.

**Comment by Falke-Design** [comment]
https://leafletpm.now.sh/
> 402: Payment required

What is going wrong?

**Comment by codeofsumit** [comment]
@Falke-Design urgh, my provider had some issues and I had to redeploy all apps. Sorry about that, should be fixed. Does it work again for you?
Thanks for reporting!

**Comment by Falke-Design** [comment]
Yes it works now 👍
