### ISSUE TITLE
Right Click by Marker drawing deletes the hint Marker

### ISSUE THREAD

**Issue by Falke-Design** [codeofsumit/leaflet.pm#405]
On right click by Marker drawing, the hint Marker disappears. In the fiddle I use a custom Icon to demonstrate it better, but it also happens with the default Marker if the cursor is fast enough to catch the marker.

https://jsfiddle.net/falkedesign/7qg05xr9/

I think the Code in Draw.Marker.enable() should be:
```
 this._map.eachLayer((layer) => {
            if (layer instanceof L.Marker && layer.pm && !layer._pmTempLayer) {
                layer.pm.enable();
            }
});
```
and not:
```
this._map.eachLayer((layer) => {
            if (layer instanceof L.Marker && layer.pm) {
                layer.pm.enable();
            }
});
`

**Comment by codeofsumit** [comment]
Thanks for reporting. Will be fixed in the next release 👍

**Comment by VCodepp** [comment]
@codeofsumit  Hi, I have a question on this. I want to make a selection of icons that I set before I start drawing a marker. How can I do that . Is there such a feature?
