### ISSUE TITLE
How do I save the polygon and re-render it with pm in the future?

### ISSUE THREAD

**Issue by ukhack** [codeofsumit/leaflet.pm#408]
I can save data like this:
{shape: "Poly", layer: e, type: "pm:create", target: e, sourceTarget: e} 
to mysql;
but how i re-render it with leaflet.pm ? I want to edit it with leaflet.pm in the future;

**Comment by codeofsumit** [comment]
Hi @ukhack. 
This is event data
```js
{shape: "Poly", layer: e, type: "pm:create", target: e, sourceTarget: e}
```

You should store your *layer* in your database, ideally as geoJSON or another format that suits you.

Something like this:
```js
const event = {shape: "Poly", layer: e, type: "pm:create", target: e, sourceTarget: e};
const layer = event.layer;

const saveMeToDB = layer.toGeoJSON();
```
