### ISSUE TITLE
re : how to get edited polygon coordinates like forEach function from geojson layer with the pm:update/edited function #398

### ISSUE THREAD

**Issue by monepa** [codeofsumit/leaflet.pm#409]
hi again, after trying your advice I still haven't found it, with the results of "Uncaught TypeError: Cannot read property '0' of undefined". My issues is "how to get edited polygon coordinates like forEach function from geojson layer with the pm:update/edited function" #398

**Comment by codeofsumit** [comment]
@monepa in your previous issue you asked to get the coordinates of an edited polygon.
In this issue I get the feeling you are asking to get the edited coordinates (so which specific coordinates have changed). Can you please explain once again what you are trying to do?

```js
polygonLayer.on('pm:edit',({ lyr }) => {
  var coords = lyr.getLatLngs();
  var polyedit = lyr.toGeoJSON();
  console.log(coords);
  console.log(polyedit);
})
```

Does this 👆  code throw that error?

In any case, I have a strong feeling that this is not a leaflet.pm issue.
You will get the layer and it's coordinates in the `pm:edit` event like I described in #398.
When you have the coords, and you need to find out which once have been edited [you can diff the new and the old coords](https://stackoverflow.com/questions/8572826/generic-deep-diff-between-two-objects). 

Or you could utilize events like `pm:vertexadded`, `pm:vertexremoved`, `pm:markerdragstart`, etc as documented.

Hope this helps.

**Comment by codeofsumit** [comment]
Also, I am subscribed to these issues. Please don't open a new one if you have the same issue. Answer here, even if it's closed. If I don't answer for a day, it's because I manage this in my spare time. Opening a new issue won't make me appear faster 😉

**Comment by monepa** [comment]
Thank you for the response, the main problem is how to edit geojson layers created from the database with the function 
var polygonLayer = L.geoJson (databaseSelectFunction results).addTo (map); 
and not from the function 'pm: create'. In this case with an edit function such as the foreach function in the leaflet draw (leaflet: edit) to get the new coordinates of the editing polygonLayer and then that will be used to update the coordinates in the database. Thank you for your help again.

**Comment by monepa** [comment]
//Insert data(polygon/multipoligon) from database as GeoJSON
var polygonLayer = L.geoJson(data ,{      
				onEachFeature: function(feature, layer) {				
			}      
		}).addTo(map);
	});

//Edit GeoJson layer
polygonLayer.on('pm:edit', ({ layer }) => {

	//here I need help to get edited polygon / multipolygon coordinates

})

**Comment by codeofsumit** [comment]
you're on the right track.
Add your geojson to the map as you showed above. Then you attach the `pm:edit` event.

```js
var oldGeo = data;
polygonLayer.on('pm:edit', ({ layer }) => {
  var newGeo = layer.toGeoJSON();

  // now you can compare the coordinates of oldGeo and newGeo and either overwrite the complete geoJSON object in your database, or pick the changed coords only and save them to the DB. I'd suggest you just overwrite all coordinates.
});
```

**Comment by monepa** [comment]
I've tried your advice.
to make it easier for me to use the following script :
`var states = [{
    "type": "Feature",
    "properties": {"party": "Republican"},
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [-104.05, 48.99],
            [-97.22,  48.98],
            [-96.58,  45.94],
            [-104.03, 45.94],
            [-104.05, 48.99]
        ]]
    }
}, {
    "type": "Feature",
    "properties": {"party": "Democrat"},
    "geometry": {
        "type": "Polygon",
        "coordinates": [[
            [-109.05, 41.00],
            [-102.06, 40.99],
            [-102.03, 36.99],
            [-109.04, 36.99],
            [-109.05, 41.00]
        ]]
    }
}];

var polygonLayer = L.geoJSON(states, {
}).addTo(map);

//var oldGeo = states; // from your DB
polygonLayer.on('pm:edit', ({ layer }) => {
  var newGeo = layer.toGeoJSON();
  console.log(newGeo);
});`
unfortunately the result is an error : 
demo.js:192 Uncaught TypeError: Cannot read property 'toGeoJSON' of undefined
    at e.polygonLayer.on (demo.js:192)
    at e.fire (leaflet.js:5)
    at e._fireEvent (leaflet.pm.min.js:1)
    at e.fire (leaflet.js:5)
    at e.disable (leaflet.pm.min.js:1)
    at leaflet.pm.min.js:1
    at Array.forEach (<anonymous>)
    at e.disableGlobalEditMode (leaflet.pm.min.js:1)
    at e.toggleGlobalEditMode (leaflet.pm.min.js:1)
    at Object.afterClick (leaflet.pm.min.js:1)
What is wrong? Thanks

**Comment by codeofsumit** [comment]
@monepa hard to tell with that info. It would be best if you create a JSFiddle that shows your problem and a clear definition of what you're trying to do. Then, I can better debug and help you. Here I can only guess and it doesn't seem to be a problem with leaflet.pm itself.
