### ISSUE TITLE
middleMarker can't drag in Leaflet 1.0.0-rc.2

### ISSUE THREAD

**Issue by wstygk** [codeofsumit/leaflet.pm#41]
when middleMarker become normal marker , it can't drag in Leaflet 1.0.0-rc.2.

**Comment by codeofsumit** [comment]
@wstygk thanks for the report.

Looks like the event changes messed something up. What still works is when you click to add a middle marker, and then drag.
The instant drag doesn't work - I'm working on a fix now!

**Comment by codeofsumit** [comment]
This seems to be a leaflet bug. The drag is stuck when changing the marker inside a dragstart event.
https://github.com/Leaflet/Leaflet/issues/4824

I'm on it, maybe I have a workaround until it's fixed by leaflet

**Comment by codeofsumit** [comment]
Ok this was already reported here:
https://github.com/Leaflet/Leaflet/issues/4484

**Comment by codeofsumit** [comment]
Fixed
