### ISSUE TITLE
Which listening method should be used for the event at the end of graphics editing?

### ISSUE THREAD

**Issue by dopayz** [codeofsumit/leaflet.pm#412]
Which listening method should be used for the event at the end of graphics editing?
for example：
        
![image](https://user-images.githubusercontent.com/30381975/54653551-0eaade00-4af6-11e9-9fe1-3066cae664aa.png)

**Comment by codeofsumit** [comment]
There is no event at cancel. You can use `pm:edit` to listen to events during edit but when cancelling, there is no event yet. What you can do is check the toolbar button status on click on the map or add click event listeners to those cancel buttons and then check against that.

Hope it helps.
