### ISSUE TITLE
Polygon - minimum points

### ISSUE THREAD

**Issue by LaserUnicorns** [codeofsumit/leaflet.pm#415]
Right now it is possible to create polygon with just 2 points - and obviously it looks like a straight line. Is this desired behavior? In my app i need polygons that contain at least 3 points. Can you adjust this check - https://github.com/codeofsumit/leaflet.pm/blob/b5fac29429ce9ae9c7f8223474aa96627cae3403/src/js/Draw/L.PM.Draw.Polygon.js#L23
or add the ability to provide required minimum points to finish polygon?

**Comment by codeofsumit** [comment]
No I guess it's not the desired behaviour. Can you test this branch if it works for you?
https://github.com/codeofsumit/leaflet.pm/pull/421
