### ISSUE TITLE
Modifies the editor's problem with objects not found

### ISSUE THREAD

**Issue by DaHuLuBa** [codeofsumit/leaflet.pm#419]
![1554776696(1)](https://user-images.githubusercontent.com/32380005/55769053-de7dac00-5ab1-11e9-9e51-58a09181280f.jpg)

Ask about the layer This object is what I contacted the context of the api really did not find

**Comment by codeofsumit** [comment]
sorry I don't get the issue? `layer` in the README is an example variable name referencing to your variable of a layer. Let me know if you still have issues.

**Comment by DaHuLuBa** [comment]
So layer, the name of my layer variable, which is this.map, okay

**Comment by DaHuLuBa** [comment]
emmm。Hello, can you continue to help me

**Comment by DaHuLuBa** [comment]
![image](https://user-images.githubusercontent.com/32380005/57423259-d72ef700-7245-11e9-91ec-895223c66381.png)
This example I obviously know is a strength after the map object, and I on his operation is also in the above.But layer this object I don't know where does it come from
![image](https://user-images.githubusercontent.com/32380005/57423410-7e139300-7246-11e9-835c-6124ef0c4001.png)
I thought the layer object was this, but that would give me an error

**Comment by codeofsumit** [comment]
I need to see more code. I don't understand what you're trying to do and I can't see what you're doing wrong if you only copy things from the documentation.

**Comment by DaHuLuBa** [comment]
No, what I want to do is use the edit function, but what is the object of this event that I don't know

![image](https://user-images.githubusercontent.com/32380005/57496867-b9c26180-7307-11e9-9d4c-df2d515e76ae.png)

![image](https://user-images.githubusercontent.com/32380005/57496925-01e18400-7308-11e9-94a7-7be5cf7b8d2f.png)

**Comment by codeofsumit** [comment]
@DaHuLuBa you again just showed the docs to me. I need to see YOUR code 🙏 .

If you create layers through the drawing tools and want to put those events to it, try this:

```js
map.on('pm:create', {layer} => {
  layer.on('pm:edit', e => { console.log(e) })
  layer.pm.enable();
});
```

**Comment by DaHuLuBa** [comment]
I reported the error as you said

![image](https://user-images.githubusercontent.com/32380005/57517812-3d9d3d80-734a-11e9-957c-a78a67afe5c3.png)

**Comment by DaHuLuBa** [comment]
I made it. I made it. Thank you.Thank you very much

![image](https://user-images.githubusercontent.com/32380005/57518213-21e66700-734b-11e9-99f8-b6d3b9f51a31.png)
