### ISSUE TITLE
Cutting not all underlying polygons

### ISSUE THREAD

**Issue by semeness** [codeofsumit/leaflet.pm#420]
Hi Sumit! Is there is any way to "cut" not all underlying polygons, but only upper one or only one that I'm edditing right now?

**Comment by codeofsumit** [comment]
not yet. Let's put this as a feature request. Will close the issue and wait for more upvotes on this.

**Comment by mike16889** [comment]
I need this as well. Maybe a way of calling cut on the layer, so instead (as well) of `map.pm.Draw.Cut.enable();` have something like `layer.pm.Cut.enable();` would only let the cut shape affect that layer. Could also be called on a layerGroup to allow cutting a group of layers

**Comment by Falke-Design** [comment]
linking: #250

**Comment by Falke-Design** [comment]
This feature is added with the Release 2.11.0
