### ISSUE TITLE
删除所有图层

### ISSUE THREAD

**Issue by zhangrrkesu** [codeofsumit/leaflet.pm#423]
请问如何删除添加的所有点线面的图层，而不是一个一个点击删除

**Comment by codeofsumit** [comment]
Please reopen an issue formulated in English, otherwise I can’t understand and help you :)

**Comment by tookun** [comment]
@zhangrrkesu: here is the google translation if you want to reopen your issue:
"How can I delete the layers of all the dotted lines that I added instead of clicking one by one?"
