### ISSUE TITLE
Uncaught TypeError: _this.map.pm.setLang is not a function

### ISSUE THREAD

**Issue by vodniciarv** [codeofsumit/leaflet.pm#430]
I use leaflet.pm in Nuxt application:
```
mounted () {
      if (process.client) {
        const checkMapObject = setInterval(() => {
          if (this.$refs.map) {
            this.map = this.$refs.map.mapObject
            this.map.pm.addControls({
              position: 'topleft',
              drawCircle: false
            })
            this.map.pm.setLang('de')
         }, 100)
      }
    }
```
and in browser console get error:
![Screenshot_1](https://user-images.githubusercontent.com/14403446/57049565-3eb2d880-6c81-11e9-905b-6ad0572e433b.png)

https://github.com/codeofsumit/leaflet.pm/issues/376

**Comment by vodniciarv** [comment]
https://github.com/codeofsumit/leaflet.pm/issues/376

**Comment by codeofsumit** [comment]
`setLang` is not released yet. Will be in the next release in a few days/weeks

**Comment by zled** [comment]
I have the same problem on june,27,2019 with leaflet.pm 2.1.0 version . 
I can see **setLang** function inside   leaflet.pm.min.js but then in chrome dev. tools ... Uncaught TypeError: map.pm.setLang is not a function  at initMap (protoSigafEdit.aspx:1432).  
I have no include statement for the language json files and didn't find examples.

**Comment by codeofsumit** [comment]
@zled please provide a jsfiddle showing this Problem Dominican debug and help you out 👍
