### ISSUE TITLE
Out of memory cutting programmaticaly Polygons

### ISSUE THREAD

**Issue by stronquens** [codeofsumit/leaflet.pm#435]
Hello, i'm creating a map editor with zones and holes.
I have a problem with your library.
When i draw a new polygon with the tools in the toolbar and then i use the cut tool, all goes well. But when i draw a Polygon programmatically with this code:

      let polygon = L.polygon(coords, { color: "green" });
      polygon.addTo(map);

Then, when i use the cut tool to modify the Polygon that i drawed, i have a lot of problems.

The major problem is when i have cutting a triangle in the perimeter of the polygon, the page inmediately crash and the devtools pause the execution due to the limit of the memory.

Only have this problem when the polygon has holes. If the polygon dont has holes, the cutting tool works well.

<img width="539" alt="example" src="https://user-images.githubusercontent.com/7658542/57527106-6c59ea80-732f-11e9-8be2-1186ceef98d3.png">

**Comment by codeofsumit** [comment]
Interesting 🤔 , thanks for reporting. Can you recreate this in JSFiddle and link it here so we have a reproducible problem that we can investigate together?

**Comment by stronquens** [comment]
Ok, I will try. When I have time along this week I will post it.

**Comment by codeofsumit** [comment]
Alright. If you can recreate the issue on jsfiddle to show the problem (no need to expose company internals), I can help you. Alternatively, I’m able to give dedicated support to companies. Feel free to contact me through sumit@raum.sh
Closing the issue for now.
