### ISSUE TITLE
Add a way to edit or add new button actions in PMButton

### ISSUE THREAD

**Issue by matt0987** [codeofsumit/leaflet.pm#438]
Hi,

In PMButton's _makeButton function, you define an object actions that provide the actions to perform for the button actions.

To add to these actions, I'm currently overriding PMButton with
`L.Control.PMButton = L.Control.PMButton.extend({`
`    _makeButton(button) {`
`        ...`
`        const actions = {...};`
`        ...`

But i think it would be easier, safer and more future-proof if these actions were defined outside the function so we could go
`L.Control.PMButton.actions = {...}`
or
`L.Control.PMButton.setActions(...)`
etc

**Comment by codeofsumit** [comment]
Great suggestion! Marked as a feature request. Please upvote the above post to help me prioritize feature requests.
