### ISSUE TITLE
Typo error in your Documentation

### ISSUE THREAD

**Issue by dksivagis** [codeofsumit/leaflet.pm#440]
Hi sir,

There is a typo error in the documentation.  The example code given to draw a polygon on the map is **map.pm.enableDraw('Polygon', options)**.  

But the above one is giving an error as the right one is **map.pm.enableDraw('Poly', options)**
The newcomers/freshers might get confused here.

So please change the Type error. Thank you.

![poly](https://user-images.githubusercontent.com/6330294/57999788-46cd9d80-7af4-11e9-9240-14259e8b69dc.png)

**Comment by Shne** [comment]
this https://github.com/codeofsumit/leaflet.pm/blob/654e919d1730b23f1702c59a70ddeadce1199c8d/src/js/Draw/L.PM.Draw.js#L27 and this https://github.com/codeofsumit/leaflet.pm/blob/654e919d1730b23f1702c59a70ddeadce1199c8d/src/js/Draw/L.PM.Draw.Polygon.js#L8 suggests that it is actually 'Polygon'. And that also works for me in my code.

In your bolded lines, you are missing the quotation marks around both 'Polygon' and 'Poly', perhaps that has something to do with what is causing your issues?

**Comment by dksivagis** [comment]
Sorry , forgot Quotation marks. I updated my issue.  Even i used with quotations, it did not work for me.

**Comment by codeofsumit** [comment]
It was `Poly` in the past. Now it's `Polygon` but I have built in [a fallback](https://github.com/codeofsumit/leaflet.pm/blob/654e919d1730b23f1702c59a70ddeadce1199c8d/src/js/L.PM.Map.js#L33).
=> Both work.

@dksivagis can you please provide a reproduction on jsfiddle where `map.pm.enableDraw('Polygon', options).` doesn't work?

**Comment by codeofsumit** [comment]
Closed until a reproducible example is provided.
