### ISSUE TITLE
Feature request - Add support to drawing single markers.

### ISSUE THREAD

**Issue by JeremyOL** [codeofsumit/leaflet.pm#445]
Add the option to choose if we want to draw multiple markers (as do it now) or single marker.

Click button per marker drawn.

**Comment by codeofsumit** [comment]
Not sure what you want to achieve. Do you want to disable drawing mode when a marker is drawn? Or do you want to limit the number of markers that can be drawn?

**Comment by JeremyOL** [comment]
> Not sure what you want to achieve. Do you want to disable drawing mode when a marker is drawn? Or do you want to limit the number of markers that can be drawn?

Yes, i want to disable drawing mode when a marker is drawn.

**Comment by codeofsumit** [comment]
you can already do that. Something like this should work:

```js
// disable marker draw after a marker is drawn
map.on('pm:create', e => {
  var layer = e.layer;
  if(layer instanceof L.Marker) {
    map.disableDraw('Marker');
  }
});
```

Let me know if that helps.

**Comment by JeremyOL** [comment]
> you can already do that. Listen to when a layer is created, check if it's a Marker, then disable draw programmatically.
> 
> Something like this should work:
> 
> ```js
> // disable marker draw after a marker is drawn
> map.on('pm:create', e => {
>   var layer = e.layer;
>   if(layer instanceof L.Marker) {
>     map.disableDraw('Marker');
>   }
> });
> ```
> 
> Let me know if that helps.

Thank you, it works but is :
`map.pm.disableDraw('Marker')`

**Comment by codeofsumit** [comment]
ah yes of course 😄
