### ISSUE TITLE
How to use remove-last-vertex and cancel methods in custom class?

### ISSUE THREAD

**Issue by Dastnbek** [codeofsumit/leaflet.pm#451]

**Comment by codeofsumit** [comment]
custom class? You mean when you extend leaflet.pm with your own classes? You can see what functions are called in the source of these actions:
https://github.com/codeofsumit/leaflet.pm/blob/develop/src/js/Toolbar/L.Controls.js#L83

If that did not help you, please provide a more detailed description of what you're trying to do.
