### ISSUE TITLE
Online demo different to the one in the repo

### ISSUE THREAD

**Issue by renege** [codeofsumit/leaflet.pm#456]
Hi,

The Demo is great: https://leafletpm.now.sh/
But when I download the repository and check the demo folder.. it just shows three maps without any controls. 
Is it even possible to Generate a Map the same as the demo-example?

@codeofsumit

**Comment by renege** [comment]
Hello @codeofsumit ?

**Comment by codeofsumit** [comment]
I'm here. I will go through all issues soon. Had wedding and honeymoon last month so I've been off ;)

**Comment by codeofsumit** [comment]
@renege no, the demo folder in the repo and the demo website https://leafletpm.now.sh/ are different projects. You can't recreate the page https://leafletpm.now.sh/ / geoman.io within the repo.
If you want to develop on leaflet.pm, I recommend to launch `npm run cypress` and do it through cypress.
