### ISSUE TITLE
No map is showing and no  export to Json

### ISSUE THREAD

**Issue by renege** [codeofsumit/leaflet.pm#457]
Hi,

What is wrong with my code? I'm not seeing a map appearing: https://codepen.io/anon/pen/ZdBdJZ#anon-login

And where is the option to save the output to GeoJSON? I only found a way to load one.

**Comment by codeofsumit** [comment]
Hi, you're missing the basic leaflet map setup and the tile layer. Please see the leaflet documentation on how to do that.
This library does not provide a way to export to geojson.
