### ISSUE TITLE
Edit events pm:editstart, enable draw and edit on LayerGroups

### ISSUE THREAD

**Issue by saschahofmann** [codeofsumit/leaflet.pm#458]
I am currently trying to migrate from leaflet.draw to leaflet.pm due to your support of editing multi-polygons. Right now, I am struggling to recreate some of the former behaviors. Mainly firing events on entering and ending the editing mode. I basically would like to fire an event the moment the edit button is toggled and once editing finishes. I haven't managed to fire an event with _pm:edit_ and am not quite sure what the expected time this event fires would be (I suppose at the end of editing)? It also seems to me that the only way to end editing is by pressing _Cancel_, which I would expect to undo the performed changes.

I would also like to enable editing only on one particular LayerGroup but it seems to me that _.disable()_ only works on layers?

**Comment by codeofsumit** [comment]
There is an open feature request for this, see
https://github.com/codeofsumit/leaflet.pm/issues/463. Please upvote the issue if you want this to be implemented 👍
