### ISSUE TITLE
Different Markers?

### ISSUE THREAD

**Issue by RZR666** [codeofsumit/leaflet.pm#459]
Is it possible to have different markers, I'd settle for two different colours but if there's a way of working with AwesomeMarkers then that would help.

Thanks.

**Comment by codeofsumit** [comment]
Cool suggestion! I'll mark this as a feature request and will gather upvotes!

**Comment by Falke-Design** [comment]
Same request as #388 so I remove the `feature request` tag from this issue.

Icons can be changed like that:
```
var icon = L.icon({
    iconUrl: 'https://placekitten.com/200/287'
})

map.pm.enableDraw('Marker',{markerStyle: {icon: icon}})
```
