### ISSUE TITLE
setLang function not working.

### ISSUE THREAD

**Issue by zled** [codeofsumit/leaflet.pm#461]
I have a problem with language API with leaflet.pm 2.1.0 version .
I can see setLang function inside leaflet.pm.min.js but then in chrome dev. tools ... Uncaught TypeError: map.pm.setLang is not a function at initMap (protoSigafEdit.aspx:1432).
I have no include statement for the language json files and didn't find examples.

**Comment by codeofsumit** [comment]
`map.pm.setLang('de');` should work fine. Please provide a JSfiddle showing where the function throws that error so I can investigate and fix it

**Comment by codeofsumit** [comment]
Closed until a reproduction is provided.
