### ISSUE TITLE
Pane Support: Polygon edit handles aren't on the same pane as polygon.

### ISSUE THREAD

**Issue by Qrokqt** [codeofsumit/leaflet.pm#462]
I need to have an editable polygon on a different leaflet pane, but it isn't clear from the docs on how to do that. I created a pane with ```map.createPane('draw').style.zIndex = 999;``` and I added a polygon to it ```L.polygon([[40, -76], [41, -73], [40, -73]], {pane: 'draw'})``` but when I turn on drawing for the polygon ```poly.pm.enable()``` the handles are drawn to some other pane.

**Comment by codeofsumit** [comment]
I have not worked with panes yet so there is nothing built for the purpose to supporting it. I'll flag this as a pane feature request to collect upvotes. Thanks for the suggestion!

**Comment by Falke-Design** [comment]
Is now supported in 2.9.0
