### ISSUE TITLE
How to know when delete is done, or editing is finished?

### ISSUE THREAD

**Issue by KrishnaPG** [codeofsumit/leaflet.pm#463]
When a series of `delete` operations are done, finally user clicks `cancel` (or after series of `edits` finally `finish`). From the docs it looks like currently there is no way to identify when the user is `done with deleting` or `done with editing`.

When `onRemove` handlers have high cost functions (such as recalculating all the visible polygons on the screen etc.), it is usually beneficial to batch the operations and do the calculations just once for the whole batch of delete layers. In the Leaflet.draw, the editing and delete operations raise events (e.g. `L.Draw.Event.DELETED`) that inform the list of all layers that were affected for that operation since it began (e.g. `const deletedLayers = event.layers;`)

#### Suggestion: 
Please raise an event on _finish_ of the delete and edit operations, in addition to the existing individual edit and delete events. This gives a chance to group the deleted layers and perform the processing on the group as a batch once the user is done with deleting / editing (and changes the mode to something else)

**Comment by codeofsumit** [comment]
So something like `pm:drawend` but for the other modes? Like `pm:editend` and `pm:deleteend` to know when a mode gets disabled?

That makes sense. I'll flag this as a feature request until we have more upvotes 👍

**Comment by codeofsumit** [comment]
@Falke-Design can you link the PR and release that fixed it here please?
