### ISSUE TITLE
Polygons should require a minimum of 3 vertices

### ISSUE THREAD

**Issue by smeijer** [codeofsumit/leaflet.pm#465]
A polygon should have at least 3 vertices to be a valid polygon. A polygon with 2 vertices should be drawn as a line, as 2 points don't make a valid ring.

```
Point: 1 vertex
Line: 2 vertices
Polyline: 2 or more vertices
Polygon 3 or more vertices
```

And yet, we check here for a minimum of 2. Can we fix that? Optionally make it configurable to have backward compatibility?

https://github.com/codeofsumit/leaflet.pm/blob/cc69298e6c2d921cec99ea6687debf2b7165c66e/src/js/Draw/L.PM.Draw.Polygon.js#L24-L27

*edit*, or actually 4. If you also count the closing vertex. A polygon is always circular, where the last vertex equals the first.

**Comment by codeofsumit** [comment]
Yes, will get fixed. Thanks for reporting

**Comment by codeofsumit** [comment]
Hm this should already be the case. Have you tried it? On the demo page and in my tests, it only finishes the polygon if there are 3 or more vertices.

![polygon](https://user-images.githubusercontent.com/2399810/63748941-a2a18280-c8aa-11e9-82d4-12fea12378b8.gif)

The code doesn't check for a minimum of 2. It checks for a maximum of 2 and if `true` does NOT finish the shape.

Let me know if you encounter problems
