### ISSUE TITLE
Can I save created objects as a GeoJSON file?

### ISSUE THREAD

**Issue by Krukarius** [codeofsumit/leaflet.pm#480]
I am wondering about saving this drawings in some format i.e GeoJSON. What code should I implement to get it working?

**Comment by codeofsumit** [comment]
Hi @Krukarius, that has nothing to do with this library. However, I've added an export feature on the demo page and geoman.io where you can export (and import) all drawn layers.

![image](https://user-images.githubusercontent.com/2399810/63686858-50595680-c803-11e9-9d93-e7bfd56119b0.png)

**Comment by Krukarius** [comment]
Looks like great option, thanks for this.

Best regards,

**Comment by ZakBen1** [comment]
Hello, sorry im new to this so might need slight explanation, 
But i cant find the code to import or export our drawings ? i checked the 4 html in the demo file :(
Thank you in advance

**Comment by Falke-Design** [comment]
@ZakBen1 Import / Exporting are default functions of Leaflet with GeoJSON. Here a tutorial: https://leafletjs.com/examples/geojson/
