### ISSUE TITLE
The new version of 2.1.0 has an error that unable to identify the map

### ISSUE THREAD

**Issue by zpzgiser** [codeofsumit/leaflet.pm#483]
Thank you  for your providing.Here I find an error.I use the leaflet.pm of 2.0.3 can well done my work, but when I update the leaflet.pm to the version of 2.1.0, I can find some error like "unable to identify the map in the leaflet.pm.mini.js". I have no idea about it. Please resolves it .Thanks.

**Comment by codeofsumit** [comment]
Please provide a jsfiddle showing the problem

**Comment by zpzgiser** [comment]
I am so sorry for your waiting. I have test again about the plug-in of 2.1.0  that it is working successfully.
