### ISSUE TITLE
v2.1 is missing snapIgnore

### ISSUE THREAD

**Issue by bumbummen99** [codeofsumit/leaflet.pm#486]
I have found that the 'snapIgnore' option is not working with the latest published version (2.1.0), also the appropriate code is missing from the dist file. A locally built 2.1.0-beta.6 does include the necessary code.

**Comment by codeofsumit** [comment]
Yes, the option is merged but not yet released. I'm working on the release right now. I want to do it via Github Actions and have troubles with it. As soon as I get GitHub Actions working I will release 2.2.0 which will include the changes.

**Comment by bumbummen99** [comment]
I just wanted to add that the check also has a small logical error but you were tto fast for me with 6b07cc1. Thank you for this awesome repo and the fast reply!

**Comment by codeofsumit** [comment]
I appreciate you taking the time to point these things out 👍 ❤️
