### ISSUE TITLE
How do I programmatically create a marker?

### ISSUE THREAD

**Issue by RZR666** [codeofsumit/leaflet.pm#490]
I have tried the below,

```
this.map.pm.enableDraw('Marker', { snappable: false });
this.map.pm.Draw.Marker._createMarker({ latlng: gps, icon: icon });
this.map.pm.disableDraw('Marker');
```

but I'm having no luck?  Is it possible?

**Comment by RZR666** [comment]
the below works, but how do I use a custom icon?

```
this.map.pm.enableDraw('Marker', { snappable: false }); 
this.map.pm.Draw.Marker._createMarker({ latlng: gps });
this.map.pm.disableDraw('Marker');
```

**Comment by codeofsumit** [comment]
Do you want to draw a marker with a custom icon or simply create a marker? Because of you want to create a marker with code, you don’t need leaflet.pm. 
Leaflet will be sufficient. 

In any case, please provide a JSfiddle with your usecase so I can debut and help you better.
