### ISSUE TITLE
Accesing nested parent layer data

### ISSUE THREAD

**Issue by RobertCristian** [codeofsumit/leaflet.pm#491]
First of all I want to thank you for this great tool. 

I was wondering, is there any way to access the parent shape/layer data when there are nested layers/shapes? For example, I draw a smaller polygon in a bigger polygon, is there any way to access the bigger polygon data? Or basically these layers don't have any idea at all that they are nested?

I tried to look in the event object of `pm:created` but with no success.

**Comment by codeofsumit** [comment]
@RobertCristian Hi and thanks for using leaflet.pm.

If you draw polygons "nested" like this:

![image](https://user-images.githubusercontent.com/2399810/64735946-d5be5580-d4e9-11e9-9a6f-939da877e51c.png)

they're not really nested. They are on top of each other and as you mentioned correctly, they don't know each other and have no correlation to each other. So there is no "parent-child" relationship.

What I would recommend is to store both references of the layers as provided via the `pm:created` event and use geospatial calculation scripts to check if one polygon is inside the other.
Like [Turf](https://turfjs.org/) or similar tools. With that info, you can create a parent-child relationship on your own with the layer references, if that's needed.

Hope this helps.
