### ISSUE TITLE
Edit Mode - Keep Snapped Items Together

### ISSUE THREAD

**Issue by solutegrate** [codeofsumit/leaflet.pm#493]
I have read through everything and I can't find a way to keep items together when moving an marker.

Example:

I have (2) Lines snapped to (1) Marker. I would love a keyboard shortcut to:

1. I hold down ex. "Ctrl"
2. Click and drag the marker
3. The (2) lines snapped to the marker should move with the marker.

I hope this make sense.

**Comment by codeofsumit** [comment]
Yes this makes perfect sense. I'm thinking about this already 👍 . I'll flag your issue as a Feature Request and close the issue. Others can upvote this which helps me prioritize it but it's definitely something I want to build soon - thanks for bringing it up!

**Comment by solutegrate** [comment]
Awesome! By the way, this plugin is bad ass! I'll be contributing financially for sure. Thanks for everything and can't wait for this feature to be available.

Although, I did think about this:

When dragging the marker with the lines snapped to it, would it drag from the previous vertex of the line or would it drag from the first vertex of the line?  This one option could render different results.

**Comment by codeofsumit** [comment]
Take a look at this:
![pinning](https://user-images.githubusercontent.com/2399810/65375984-288ece80-dc9b-11e9-930e-bca03ad7cb56.gif)

**Comment by bumbummen99** [comment]
@codeofsumit This looks kind of the same as my WIP right now, will that be the pinning feature of the pro version?

**Comment by cjauvin** [comment]
@bumbummen99 I'd be really interested to know more about your WIP, is it #489 ?

**Comment by bumbummen99** [comment]
@cjauvin It is also based on that PR but the logic behind it is a bit more complex and not included. Basically, i store all layers for snapped dragging into a dedicated LayerGroup. When i drag a layer, i simply iterate all layers in that group and check their latlang or latlangs for matching/snapped ones. I then check if they are the same with some precision offset. If i find any matches i disable snapping for them (important) and update their respective latlang on marker drag. You will have to disable snapping during dragging as you would just snap your dragging layer to the layers you would want to drag too constantly. Also editing has to be disabled as it will spawn additional markers (the handles). On drag end i simply take the temp list of snapped layers and re-enable snapping and editing for them. If your layers are not editable all the time you can skip disabling it.

I think the solution itself is not perfect nor pretty and it will be slower with an increasing amount of layers, I also still have to figure out a way to circumvent this limitation and maybe get rid of the iteration needed to find snapped layers.

Maybe @codeofsumit also has an idea on it

**Comment by cjauvin** [comment]
@bumbummen99 Thanks for your detailed answer. I'm very new to Leaflet and Geoman so please bear with me, as my current understanding of how it works is very shallow. The feature I have in mind to implement (or wish for!) would be a special mode of the "Edit" function where moving a single point that is "shared" between two or more features would modify all of them at once. Although it seems closely related, I'm not sure it's exactly what you describe. Actually what I have in mind is pretty much identical to the gif above, except that I'd possibly implement it with an additional submenu item in the "Edit" menu (something like "keep shared points together"), in order to not interfere with the default interaction method, and also, it would probably not include the "additional handles" that appear with the default edit mode, as it wouldn't make sense in such a setting. I hope what I say is relatively clear! :smile:

**Comment by cjauvin** [comment]
Forget what I said about the non-need for "middle markers" in what I propose.. I just realized not having them wouldn't make sense.

**Comment by cjauvin** [comment]
Please see: https://github.com/geoman-io/leaflet-geoman/pull/537

**Comment by codeofsumit** [comment]
Hello all,
over the past months where I haven't been active here, I have been talking to businesses that use Leaflet-Geoman extensively in their teams and projects. As I have reiterated in another issue, I want to dedicate more time to this library and a `Pro` version is exactly how I want to do this.
*More advanced features in a paid version that will trickle down to the open source library over time.*.

Pinning Shared Vertexes is the first feature I will offer in the Pro version of Leaflet-Geoman and I'm actively working on it right now.
In the GIF below, you can see Pinning and Snapping available via an "Options Toolbar" (also exclusive to the Pro version for now) and Pinning works exactly as described here.

![options-toolbar](https://user-images.githubusercontent.com/2399810/74103722-ed5c4180-4b4e-11ea-9d5d-b77327a8e9a9.gif)

If the Pinning options is set on a layer, any vertex you drag from that layer will move any other vertex from any other layer that is equal to it.

If you are interested in Leaflet-Geoman Pro ⭐, consider becoming a [Github Sponsor and Leaflet-Geoman Supporter](https://github.com/sponsors/codeofsumit).

I expect the first version to ship in the next weeks with this feature included. I will update this Issue accordingly.

**Comment by codeofsumit** [comment]
Hi all,

This feature is now released in Leaflet-Geoman Pro ⭐️. I have [written a detailed article here](https://geoman.io/blog/pinning-now-in-leaflet-geoman-pro) to introduce the feature.

![](https://blog.raum.sh/content/images/2020/02/pinning-demo.gif)

**[Leaflet-Geoman Pro ⭐️ is available here](https://geoman.io/leaflet-geoman#pro)**. Customers of the Pro version are helping me to focus more time on this open source library.

**Comment by cjauvin** [comment]
Thanks! I can't really comment on how you implemented it (obviously I cannot look at the code since it's a pro feature), but just by looking at the gif above, I would suspect that the implementation I experimented with in my previous PR (https://github.com/geoman-io/leaflet-geoman/pull/537) for a very similar feature, was somehow more efficient, because the polygon lines weren't as "laggy" when moving vertices in pinned mode. Is that possible?

**Comment by codeofsumit** [comment]
@cjauvin thanks for the hint. So far I think the performance is on par:

![snap-lag](https://user-images.githubusercontent.com/2399810/77406744-6806b680-6db5-11ea-9a43-427f4e67a434.gif)

But of course, this always depends on how many layers you have on the map that have to be recalculated and it doesn't mean the performance can't be improved. Just as the last release of Leaflet-Geoman brought an over 3000% performance increase in editing large datasets, I will continuously work to make the library more efficient and faster.

I'm gonna check on the particular usecase in the GIF above to see if I can get a bit more juice out of it 👍
