### ISSUE TITLE
option to change toolbar position

### ISSUE THREAD

**Issue by themre** [codeofsumit/leaflet.pm#93]
hi,
is there an option to change toolbar position? e.g. position: 'topright'. thanks!

**Comment by codeofsumit** [comment]
@themre not yet, but I'm going to implement it - probably ready next week.

**Comment by codeofsumit** [comment]
@themre done! Update to 0.12.0 and you'll have a configurable position of the toolbar

**Comment by themre** [comment]
Thanks!
